HW01_ManasyanAL
pluralia/fp-fall-2023 pull request #1
Opened 2023-10-01 10:53 UTC by Artem9999999999999999999999

Add HW solutions

2023-10-02 11:29 UTC, pluralia requested changes
Все хорошо -- нужно поправить по мелочи:
1. побольше хвостовой рекурсии
2. не использовать `error`

Молодец, что посмотрел про рекорды и использовал `and` для тестов!

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +elemByIndex :: [a] -> Int -> a
Что, если пришел индекс, больший длины списка?

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
Будет ли работать эта функция на списках большой длины?

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +-- | Тесты
Чтобы запустить все тесты сразу:
```haskell
testAll = and [
      testChSucc
    , testChAdd1, testChAdd2
    , testChMult1, testChMult2, testChMult3
    , testChPow1, testChPow2
    , testChPrev1, testChPrev2
    ]
```

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +move p dx dy = Point {x = x p + dx, y = y p + dy}
Можно паттерн-матчиться по рекордам:
```haskell
move (Point {x, y}) dx dy = Point { x = x + dx, y = y + dy }
```

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +binTreeOfInts :: IntTree
Было бы классно увидеть другую структуру у дерева, но да ладно ;)

2023-10-02 11:29 UTC, pluralia commented on hw1_solution.hs
> +-- | Тесты
В последнем задании так и сделано 👍

2023-10-02 11:36 UTC, pluralia commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
Будет ли работать `True &&& False &&& False`?

2023-10-02 13:11 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
Так не заработает. Подумал, что можно через bool и список bool, например:
```
infixr 3 &&&&
(&&&&) :: Bool -> [Bool] -> Bool
(&&&&) acc [] = acc
(&&&&) False _ = False
(&&&&) acc (x:xs) = (&&&&) (acc && x) xs

ghci> True &&&& [True, False, True] 
False
```

Но как сделать это красиво, как обычный оператор пока не придумал

2023-10-02 13:15 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
Будет, но не очень быстро. Попробовал через хвостовую рекурсию, вышло так:

```
mapList :: (a -> b) -> [a] -> [b]
mapList f xs = mapListHelper f xs []
  where
    mapListHelper :: (a -> b) -> [a] -> [b] -> [b]
    mapListHelper _ [] acc = acc
    mapListHelper f (x:xs) acc = mapListHelper f xs (acc ++ [f x])
```

Но с моим примером чисел Фибоначчи, тоже не супер вау получается

2023-10-02 13:19 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +elemByIndex :: [a] -> Int -> a
Код закончит работу с ошибкой "The list is empty"
Можно заменить ее на error))
Код с использованием Either

```
elemByIndex :: [a] -> Int -> Either String a
elemByIndex [] _                   = Left "Error input data"
elemByIndex _ 0                    = Left "Invalid index, index must be greater than 0"
elemByIndex (x : _) 1              = Right x
elemByIndex (x : xs) n | n < 0     = Left "Invalid index, index must be positive"
                       | otherwise = elemByIndex xs (n - 1)
```

2023-10-02 13:20 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +myReverse :: [a] -> [a]
Она же, но с использованием Either и ХР
```
myReverse :: [a] -> Either String [a]
myReverse xs = myReverseHelper xs []
  where
    myReverseHelper :: [a] -> [a] -> Either String [a]
    myReverseHelper [] acc = Right acc
    myReverseHelper (x : xs) acc = myReverseHelper xs (x : acc)
```

2023-10-02 13:20 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +myTail []       = error "The list is empty"
myTail :: [a] -> Maybe [a]
myTail []       = Nothing
myTail (_ : xs) = Just xs

2023-10-03 14:10 UTC, pluralia commented on hw1_solution.hs
> +myTail []       = error "The list is empty"
Пиши, пожалуйста, код в блоках. А вообще лучше новый коммит сделать

2023-10-03 14:11 UTC, pluralia commented on hw1_solution.hs
> +myTail []       = error "The list is empty"
> Используйте Either или Maybe для обработки ошибок.

Этот комментарий относится ко всем `error` в домашке. Исправь, пожалуйста, везде

2023-10-03 14:12 UTC, pluralia commented on hw1_solution.hs
> +myReverse :: [a] -> [a]
Чтобы добавить синтаксис haskell в блок кода, пиши ```haskell

2023-10-03 14:12 UTC, pluralia commented on hw1_solution.hs
> +myReverse :: [a] -> [a]
Здесь `Either` не нужен: любой список можно развернуть

2023-10-03 14:19 UTC, pluralia commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
Ты сейчас пытаешься реализовать функцию `and :: [Bool] -> Bool`, а тебе нужен обычный бинарный оператор.

Подсказка: обрати внимание на ассоциативность.

2023-10-03 14:35 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
Я слишком намудрил с вашим вопросом. Дополнительное указание на то, что нужен именно бинарный оператор меняет ситуацию. Бинарным называют оператор, который принимает два операнда, по одному с каждой стороны.
Тогда ``` True &&& False &&& True ``` вызовет ошибку, но если задавать запрос с явным указанием ассоциативности
```(True &&& False) &&& True => False```, то все будет работать в исходно написанной функции

2023-10-03 14:42 UTC, pluralia commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
> Но с моим примером чисел Фибоначчи, тоже не супер вау получается

Что именно? У тебя хорошая реализация `fibTail`

2023-10-03 14:42 UTC, pluralia commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
> Будет, но не очень быстро

Верная реализация! Как думаешь, в чем может быть проблема?

2023-10-03 14:42 UTC, pluralia commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
Верно! Как задать ассоциативность оператору?

2023-10-03 14:45 UTC, pluralia commented on hw1_solution.hs
> +myTail []       = error "The list is empty"
👍

2023-10-03 15:03 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
Проблема в том, что я запустил тест на fib, а не fibTail)

2023-10-03 15:03 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +mapList :: (a -> b) -> [a] -> [b]
C fibTail все работает отлично)

2023-10-03 15:16 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
через ```infixl 3  &&&```, тогда функция станет левоассоциативной и все будет работать без скобок

2023-10-03 15:17 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +(&&&) :: Bool -> Bool -> Bool
коммит для этой функции добавил

2023-10-03 15:26 UTC, pluralia commented on hw1_solution.hs
> +myLength (x : xs) = 1 + myLength xs
Здесь ожидаю версию с хвостовой рекурсией

2023-10-03 15:35 UTC, Artem9999999999999999999999 commented on hw1_solution.hs
> +myLength (x : xs) = 1 + myLength xs
Сделал коммит

```
myLength :: [a] -> Int
myLength list = myLengthHelper list 0
  where
    myLengthHelper :: [a] -> Int -> Int
    myLengthHelper [] acc = acc
    myLengthHelper (x : xs) acc = myLengthHelper xs (acc + 1)
```

2023-10-03 15:40 UTC, pluralia commented
Домашка сдана

2023-10-03 15:40 UTC, closed without merging