Hw02_Pushkina
pluralia/fp-fall-2023 pull request #10
Opened 2023-10-12 19:33 UTC by forestcream

Там немного у меня путаница с ветками возникла, поэтому PR делаю из своей ветки

2023-10-13 18:12 UTC, pluralia requested changes
Все неплохо -- пара общих вопросов:
1. Как будто избегаешь лямбд и композиции функций (да, мы прошли ее только сегодня, но вы уже знаете как писать со скобками `f (g x)`. Почему?
2. Как ты понимаешь, когда что использовать: `foldr`, `foldl`, `foldl'`?

2023-10-13 18:12 UTC, pluralia commented on hw02/test/TestSpec.hs
> +  describe "or'" $ do
Списки разной длины?

2023-10-13 18:12 UTC, pluralia commented on hw02/test/TestSpec.hs
> +  describe "maximum'" $ do
Хочется еще тестов на списки разной длины и с не только упорядоченными элементами

2023-10-16 15:55 UTC, forestcream commented on hw02/src/MyLib.hs
> +import Control.Monad (when)
Случайно добавился, я не заметила

2023-10-16 15:56 UTC, forestcream commented on hw02/src/MyLib.hs
> +-- кажется, что нет разницы какую свертку мы используем
Хорошо, буду знать

2023-10-16 16:03 UTC, forestcream commented on hw02/src/MyLib.hs
> +    maxMaybe x Nothing = x
`maximum' :: [Int] -> Maybe Int
maximum' xs = foldr maxMaybe Nothing . map Just $ xs
  where
    maxMaybe Nothing y = y
    maxMaybe x Nothing = x
    maxMaybe (Just x) (Just y) = Just (max x y)`
вот тогда как будет выглядеть функция с композицией

2023-10-16 16:13 UTC, forestcream commented on hw02/src/MyLib.hs
> +-- я не придумала как можно эту функцию реализовать с левой сверткой, с правой интуитивно понятнее
``` 
maximum' :: [Int] -> Maybe Int
maximum' xs = foldl maxMaybe Nothing (map Just xs)
  where
    maxMaybe y Nothing = y
    maxMaybe Nothing x = x
    maxMaybe (Just y) (Just x) = Just (max y x)
```
Поиска максимума на бесконечном списке достаточно бессмысленен, так что наверное левая свертка будет лучше

2023-10-16 16:18 UTC, forestcream commented on hw02/src/MyLib.hs
> +myZipWith f xs ys = foldr helpMyZipWith [] (zip xs ys)
```
myZipWith :: (a -> b -> c) -> [a] -> [b] -> [c]
myZipWith f xs ys = map helpMyZipWith (zip xs ys)
  where
    helpMyZipWith (a, b) = f a b
```

2023-10-16 16:31 UTC, forestcream commented on hw02/src/MyLib.hs
> +    helpMyZipWith (a, b) acc = f a b : acc
```
myZipWith2 :: (a -> b -> c) -> [a] -> [b] -> [c]
myZipWith2 f xs ys = map (\(a, b) -> f a b) (zip xs ys)
```

2023-10-16 17:01 UTC, forestcream commented on hw02/src/MyLib.hs
> +    helpMap x acc = f x : acc
исправила
```filter' p = foldr (\x xs -> if p x then x : xs else xs) []```

2023-10-16 17:04 UTC, forestcream commented on hw02/src/MyLib.hs
> +    choose p x xs = if p x then x : xs else xs
```reverse' = foldl (\xs x -> x : xs) []```

2023-10-16 17:06 UTC, forestcream commented on hw02/src/MyLib.hs
> +reverse' = foldl place_first []
foldl' более строгая и сразу вычисляет промежуточные результаты

2023-10-16 17:09 UTC, forestcream commented on hw02/src/MyLib.hs
> +-- какую свертку использовать неважно
Потому что на мне важно в каком порядке проверять список

2023-10-16 17:11 UTC, forestcream commented on hw02/src/MyLib.hs
> +    helpLast x y = Just y
```head' = foldr (\x _ -> Just x) Nothing```

2023-10-16 17:13 UTC, forestcream commented on hw02/src/MyLib.hs
> +-- какую свертку использовать неважно
Без разницы с какой стороны списка идти

2023-10-16 17:15 UTC, forestcream commented on hw02/src/MyLib.hs
> +    helpLast x y = Just y
``` last' = foldl (\_ y -> Just y) Nothing ```

2023-10-16 18:11 UTC, forestcream commented on hw02/src/MyLib.hs
> +take' :: Int -> [a] -> [a]
```
take' :: Int -> [a] -> [a]
take' n xs = snd $ L.foldl' help_take (0, []) (zip [1..] xs)
  where
    help_take (i, acc) (j, x)
      | j <= n    = (j, acc ++ [x])
      | otherwise = (i, acc)
```

2023-10-16 18:16 UTC, forestcream commented on hw02/src/MyLib.hs
> +take'' :: Int -> [a] -> [a]
```
take'' :: Int -> [a] -> [a]
take'' n xs = foldr help_take' (const []) (zip [1..] xs) 0
  where
    help_take' :: (Int, a) -> (Int -> [a]) -> Int -> [a]
    help_take' (j, x) f i
      | j <= n    = x : f (i + 1)
      | otherwise = []
```

2023-10-16 18:26 UTC, forestcream commented on hw02/src/MyLib.hs
> +insertionSort = foldr insert []
да, через рекурсию
```insertionSort :: Ord a => [a] -> [a]
insertionSort [] = []
insertionSort (x:xs) = insert x (insertionSort xs)
  where
    insert x [] = [x]
    insert x acc@(y:ys)
      | x <= y = x : acc
      | otherwise = y : insert x ys
```

2023-10-16 18:29 UTC, forestcream commented on hw02/src/MyLib.hs
> +insert xs n = foldr insertInOrder [n] xs
Мне казалось, что она будет более оптимальной из-за ленивости

2023-10-16 18:45 UTC, forestcream commented on hw02/src/MyLib.hs
> +    insertInOrder x acc
```
insert :: [Int] -> Int -> [Int]
insert xs n = foldr insertInOrder [n] xs
  where
      insertInOrder x [] = [x]
      insertInOrder x acc@(_ : ys)
        | x <= n = x : acc
        | otherwise = n : x : ys
```

2023-10-16 18:47 UTC, forestcream commented on hw02/src/MyLib.hs
> +    place_first xs x = x : xs
reverse' :: [a] -> [a]
reverse' = foldl (\xs x -> x : xs) []

2023-10-16 19:00 UTC, forestcream commented on hw02/src/MyLib.hs
> +fibSum xs = result
```
fibSum :: [Int] -> Int
fibSum xs = foldl processElement 0 . zip [0..] $ xs
  where
    processElement acc (i, x)
      | i `elem` fibIndices = acc + x
      | otherwise = acc
    fibIndices = take (length xs) fibs
```

2023-10-16 19:01 UTC, forestcream commented on hw02/test/TestSpec.hs
> +  describe "maximum'" $ do
Обновила тесты в коммите новом - добавила на другую длину и с элементами не по порядку

2023-10-16 19:08 UTC, forestcream commented
1. Да, с лямбдами и композициями мне сложновато сразу писать, но я вот сейчас когда переделывала уже свой код с использованием лямбд и композиций, то стало легче
2. foldr - ленивость и когда по логике мы идем справа налево, так же он работает с бесконечными списками
foldl - когда по логике идем слева направо
foldl' - если список очень большой, чтобы не было переполнения

2023-10-17 10:52 UTC, pluralia commented on hw02/src/MyLib.hs
> +-- я не придумала как можно эту функцию реализовать с левой сверткой, с правой интуитивно понятнее
Почему тут 2 одинаковые функции `maximum'` и `maximum1'`? Полагаю, одна из них должна была быть с левой сверкой -- добавь, пожалуйста.

Ты изменила `maxMaybe` (рассмотрела все случаи паттернматчинга), и теперь левая свертка заработала. Почему?

2023-10-17 10:55 UTC, pluralia commented on hw02/src/MyLib.hs
> +-- какую свертку использовать неважно
Это и правда неважно, но есть другой важный момент. Перепиши эту функцию с левой сверткой и посмотри на результат

2023-10-17 10:56 UTC, pluralia commented on hw02/src/MyLib.hs
> +    helpMap x acc = f x : acc
`map` остался без лямбды

2023-10-17 10:57 UTC, pluralia commented on hw02/src/MyLib.hs
> +-- какую свертку использовать неважно
Это и правда неважно, но есть другой важный момент. Перепиши эту функцию с левой сверткой и посмотри на результат

Другой важный момент -- скорость: везде, где список не бесконечный, нужно использовать `foldl'`

2023-10-17 10:57 UTC, pluralia commented on hw02/src/MyLib.hs
> +    helpMap x acc = f x : acc
Тут все то же, что и для `filter`

2023-10-17 10:59 UTC, pluralia commented on hw02/src/MyLib.hs
> +myZipWith f xs ys = foldr helpMyZipWith [] (zip xs ys)
Используй, пожалуйста, лямбды

2023-10-17 11:21 UTC, pluralia commented
1. Понимаю, что непривычно. Ты молодец :) Когда привыкнешь, почувствуешь, что так писать даже приятнее: читается легче и имена переменным придумывать не нужно
2. Почти.
    - Про справа налево нужно помнить, что это влияет не только на порядок обхода, но и на то, в каком порядке элементы собираются снова -- чтобы преисполниться, попробуй разные сверки на `filter` и `map`
    - foldr -- ok
    - foldl -- лучше не использовать никогда; потому что он ленивый, но не способен обрабатывать бесконечные списки
    - foldl' - лучше использовать вообще везде, где можешь, потому что он самый быстрый (быстрее foldr); `foldr` предпочтительнее только в случаях, если у тебя потенциально может быть бесконечный список
3. После всех экспериментов, ответь, пожалуйста, снова: что лучше использовать для `filter` и `map`?

2023-10-17 18:40 UTC, forestcream commented
1. Спасибо :)
2. Хорошо
3. Лямбды
4. Сделано (hlint некоторые просто предлагают заменить уже реализованной функцией и их я не трогала)

2023-10-17 19:20 UTC, pluralia commented
3. Лямбды -- это правда. Но я про foldr/foldl/foldl'
4. Не запушила?

2023-10-17 20:20 UTC, forestcream commented
3. лучше левую свертку и еще лучше строгую
4.  теперь запушила

2023-10-17 21:01 UTC, pluralia commented
3. Нет. Должны ли filter и map уметь работать на бесконечных списках?
4. Не все ворнинги исправлены и еще hlint

Последний шанс исправить -- что будет, за то балл и поставлю

2023-10-18 06:58 UTC, forestcream commented
3. Да, нам нужно уметь работать на бесконечных списках, значит нужна правая
4. Исправила все что можно

2023-10-18 09:04 UTC, pluralia commented
Ок, но можно поправить еще 2 hlint
<img width="345" alt="Screenshot 2023-10-18 at 11 03 52" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/f6642d24-9898-4074-986b-d2f980125ef7">

2023-10-18 09:04 UTC, closed without merging