HW2 Kostina
pluralia/fp-fall-2023 pull request #11
Opened 2023-10-12 20:30 UTC by jmkostina

У меня не запускается `cabal test`
пишет 
```haskell
cabal-3.6.2.0: can't find source for TestsSpec in test,
/Users/juliakostina/Desktop/Haskell/Homework2/dist-newstyle/build/x86_64-osx/ghc-9.4.7/hw2-0.1.0.0/t/hw2-test/build/hw2-test/autogen,
/Users/juliakostina/Desktop/Haskell/Homework2/dist-newstyle/build/x86_64-osx/ghc-9.4.7/hw2-0.1.0.0/t/hw2-test/build/global-autogen
```

2023-10-13 17:16 UTC, pluralia commented
@jmkostina, заигнорь, пожалуйста, `dyst-newstyle`.

Ты указала TestsSpec в .cabal, а файл у тебя называется TestSpec, поэтому он не может его найти.

Я запустила твои тесты, но там много ошибок компилятора -- исправь их, пожалуйста, и я посмотрю домашку

2023-10-14 11:05 UTC, jmkostina commented
я пересобрала несколько раз проект, но у меня все равно ошибка при тестировании
Пишет
```haskell
juliakostina@iMac-Ulia HT2 % cabal test                                          
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.6.2.0 supports
'ghc' version < 9.4): /Users/juliakostina/.ghcup/bin/ghc is version 9.4.7
Resolving dependencies...
Build profile: -w ghc-9.4.7 -O1
In order, the following will be built (use -v for more details):
 - hw2-0.1.0.0 (test:hw2-test) (first run)
Configuring test suite 'hw2-test' for hw2-0.1.0.0..
Preprocessing test suite 'hw2-test' for hw2-0.1.0.0..
Building test suite 'hw2-test' for hw2-0.1.0.0..
ghc-9.4.7: could not execute: hspec-discover
```
 я не понимаю, что не так, если hspec-discover часть hspec, который у меня стоит, то все должно работать

2023-10-14 15:54 UTC, pluralia requested changes
@jmkostina, Я оставила пару комментариев -- сделав эти изменения, я запустила тесты

Удали из репо `dyst-newstyle`, пожалуйста, -- ревьювить тяжелее, когда столько файлов

2023-10-14 15:54 UTC, pluralia commented on HT2/hw2.cabal
> +    build-depends:    base ^>=4.17.2.0
Замени на 4.16.4.0

2023-10-14 15:54 UTC, pluralia commented on HT2/hw2.cabal
> +    build-depends:    base ^>=4.17.2.0,
Замени на 4.16.4.0

2023-10-14 15:54 UTC, pluralia commented on HT2/hw2.cabal
> +    build-depends:    base ^>=4.17.2.0,
Добавь hw2 в зависимости

2023-10-14 15:54 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +module TestSpec (spec) where
Должен называться TestsSpec, потому что файл называется TestsSpec

2023-10-14 18:30 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +module TestSpec (spec) where
У себя поменяла, та же ошибка

2023-10-14 19:52 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +module TestSpec (spec) where
Попробуй остальные вещи по моим комментариям сделать. Eсли не поможет, будем уже по-другому с ошибкой разбираться

2023-10-17 12:52 UTC, pluralia requested changes
@jmkostina, у тебя по-прежнему проблемы со сборкой?

1. Много ошибок компиляции на тестах -- исправь их, пожалуйста, и ворнинги
2. hlint

2023-10-17 12:52 UTC, pluralia commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
Давай смотреть на ошибку
```
Couldn't match type ‘a’ with ‘Int’
  Expected: [a]
    Actual: [Int]
```
- Какой тип у insertionSort?
- Какой тип у insert?
- Почему одно не работает с другим?

2023-10-17 12:52 UTC, pluralia commented on HT2/src/MyLib.hs
> +-- я понимаю, что нужно сделать, но не понимаю как мне это написать с использованием списка fibs
fibs содержит индексы, элементов исходного списка, которые ты хочешь сохранить. Как проверить, что элемент содержится в списке?

2023-10-17 12:52 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
Выдает все в обратном порядке -- это не ожидаемое поведение

2023-10-17 12:52 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test bfs" $ do
Больше тестов на деревья

2023-10-17 12:52 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test dfs" $ do
Больше тестов на деревья

2023-10-17 14:53 UTC, jmkostina commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
нам достаточно дойти до первого True, поэтому за счет ленивости `foldl'` мы остановимся после его нахождения

2023-10-17 15:07 UTC, jmkostina commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
нам нужно, чтобы функции обрабатывались справа. если там будет какая-нибудь неассоциативная функция, то `foldl` ее просто не сможет обработать

2023-10-17 15:10 UTC, jmkostina commented on HT2/src/MyLib.hs
> +last' [] = Nothing
как в передыдущем? типа
```haskell
last' :: [a] -> Maybe a
last' = L.foldl' (\_ y -> Just y) Nothing
```

2023-10-17 15:15 UTC, jmkostina commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
я поняла функции как возвращающую выбранное число элементов (с начала или с конца, в зависимости от `foldr` и `foldl`
для 1 случая
```haskell
take' 3 [1,2,3,4,5] -> [1,2,3]
```
для 2 случая
```haskell
take'' 3 [1,2,3,4,5] -> [3,4,5]
```

2023-10-17 15:21 UTC, jmkostina commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
- у insertionSort - `Ord`
- у insertion - `Int`
- видимо нужно переписать в insertion тип `Ord`? а оно будет работать, если введут не упорядоченный список?

2023-10-17 15:27 UTC, jmkostina commented on HT2/src/MyLib.hs
> +-- я понимаю, что нужно сделать, но не понимаю как мне это написать с использованием списка fibs
если бы это был питон, я бы просто сравнивала индекс со списком `fibs`, но я не знаю какая встроенная функция Haskell может это сделать. или нужно что-то другое? вроде
```haskell
isInFibs :: Integer -> Bool
```

2023-10-17 15:35 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
Я использую левостороннюю свертку, а она, если я правильно поняла, прикрепляет к началу списка ответы

2023-10-17 15:42 UTC, pluralia commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
> нам нужно, чтобы функции обрабатывались справа

Какие функции? Зачем?

2023-10-17 15:46 UTC, pluralia commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
> я предполагаю, что список не бесконечный

Откуда такое предположение?

На стандартом filter я могу так вот написать `take 3 . filter even $ [1..]`. Могу ли я то же сделать с твоей текущей реализацией `filter'`? Почему?

2023-10-17 15:47 UTC, pluralia commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
Верно! Но по заданию нужна обычная реализация `take''`: чтобы работал как стандартная `take`

2023-10-17 15:48 UTC, pluralia commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
> у insertionSort - Ord

Нет. Есть другие идеи?

2023-10-17 15:48 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +  describe "test bfs" $ do
```haskell
it "case 3" $ do
  let tree = Node 10 []
    bfs tree `shouldBe` ([10] :: [Int])

it "case 4" $ do
  let tree = Node 1 [Node 2 [Node 3 [], Node 4 []], Node 5 [Node 6 [], Node 7 []]]
    bfs tree `shouldBe` ([1, 2, 5, 3, 4, 6, 7] :: [Int])
```

2023-10-17 15:52 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +  describe "test dfs" $ do
```haskell
it "case 3" $ do
  let tree = Node 'A' []
    dfs tree `shouldBe` ([A] :: [Char])

it "case 4" $ do
  let tree = Node 'c' 
    [Node 'o' 
      [Node 'e' [], Node 'e' []], 
     Node 'f' [Node 'i' [], Node 's' []], 
     Node 'f' 
       [Node 't' [], Node 'a' [], Node 's' [Node 't' [], Node 'y'[]]]]
  dfs tree `shouldBe` (["coeefisftasty"] :: [Char])
```

2023-10-17 15:54 UTC, jmkostina commented
я так и не смогла выполнить `cabal test`, а без него я так поняла и `hlint` не работает. у меня ошибка `could not execute: hspec-discover`. все имена я у себя поменяла и зависимости прописала

2023-10-17 16:02 UTC, pluralia commented on HT2/src/MyLib.hs
> +-- я понимаю, что нужно сделать, но не понимаю как мне это написать с использованием списка fibs
> но я не знаю какая встроенная функция Haskell может это сделать

В таких случаях и нужно пользоваться hoogle. Думаешь, с какой сигнатурой тебе нужна функция и ищешь ее. Тебе нужна функция, которая принимает элемент, список и говорит, есть ли этот элемент в этом списке.

Какая у нее сигнатура? Как называется эта функция?

2023-10-17 16:02 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
Верно! Тебе нужно либо менять свертку, либо в конце развернуть список.

2023-10-17 16:11 UTC, pluralia commented
1. `hlint` не связан с `cabal test`
2. У тебя установлен `hspec-discover`? 
3. Прописан ли `hspec-discover` в $PATH? `hspec-discover` должен работать сам по себе
<img width="383" alt="Screenshot 2023-10-17 at 18 10 57" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/d3cbd6e7-4ee6-4f27-b938-8d85bb606c03">

2023-10-17 17:14 UTC, jmkostina commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
с моей `filter'` не получится, она уходит в бесконечность, потому что каждый раз будет вычисляться и откусываться первый элемент в этом бесконечном списке. 
но я не понимаю, почему можно сделать такое с стандартной функцией для бесконечного списка.

2023-10-17 17:16 UTC, jmkostina commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
Функция деления, она неассоциативна. Иначе будет ошибка

2023-10-17 17:23 UTC, jmkostina commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
я не знаю, как это сделать

2023-10-17 17:25 UTC, jmkostina commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
Любой типо, но только сравниваемый? по определению `Ord`

2023-10-17 17:35 UTC, jmkostina commented on HT2/src/MyLib.hs
> +-- я понимаю, что нужно сделать, но не понимаю как мне это написать с использованием списка fibs
нужен `elem` - `elem :: Eq a => a -> t a -> Bool`
```haskell
fibSum :: [Int] -> Int
fibSum xs = sum[x | (x, i) <- zip xs [0..], i `elem` fibs] 
```

2023-10-17 17:50 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
я не знаю, как правильно вписать разворот

2023-10-17 18:05 UTC, jmkostina commented
я устанавливала по вашим комментариям, но у меня не находит 
```
juliakostina@iMac-Ulia HT2 % hspec-discover
zsh: command not found: hspec-discover
```
как в этой ситуации прописывать путь, я не знаю

2023-10-17 18:28 UTC, pluralia commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
> с моей filter' не получится, она уходит в бесконечность, потому что каждый раз будет вычисляться и откусываться первый элемент в этом бесконечном списке.

Как нужно поменять твою реализацию, чтобы твоя filter' тоже работала?

2023-10-17 18:29 UTC, pluralia commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
Что делает `:` в коде?

2023-10-17 18:32 UTC, pluralia commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
Дать подсказку или -0.25?

2023-10-17 18:35 UTC, pluralia commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
Ord -- это не тип, а ограничение на тип. Тип у тебя `Ord a => a`.

Окей, у тебя есть `insertionSort`, который сортирует элементы типа `Ord a => a`. Их ты пытаешься передать в 'insertion`, который работает с `Int` -- более специфичным типом. Что нужно сделать, чтобы все заработало?

2023-10-17 19:04 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
развернуть список = reverse

2023-10-17 19:07 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test dfs" $ do
Тест с одним элементом -- не серьезно

2023-10-17 19:07 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +  describe "test bfs" $ do
Тест с одним элементом -- не серьезно

2023-10-17 19:14 UTC, pluralia commented on HT2/src/MyLib.hs
> +-- я понимаю, что нужно сделать, но не понимаю как мне это написать с использованием списка fibs
Ок -- поставлю 0,25 за него

2023-10-18 17:43 UTC, jmkostina commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
взять `foldr` - 
``` haskell
filter' condition = foldr(\acc x -> if condition acc then acc : x else x) []
```

добавила тест на бесконечный список

2023-10-18 17:57 UTC, jmkostina commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
`:` - берет список от x до acc
`foldr` нужен для обработки бесконечных списков

добавила тест на бесконечный список

2023-10-18 18:05 UTC, jmkostina commented on HT2/src/MyLib.hs
> +--insertionSort (x:xs) = insert(insertionSort xs) x
нужно убрать этот специфический тип `Int` - `insert :: Ord a => [a] -> a -> [a]`

2023-10-18 18:10 UTC, jmkostina commented on HT2/test/TestsSpec.hs
> +  describe "test `filterl'" $ do
я сделал через свертку, но если с `reverse`, то должно было быть 
```haskell
filter' :: (a -> Bool) -> [a] -> [a]
filter' condition = reverse . L.foldl'(\acc x -> if condition x then x:acc else acc)[]
```

2023-10-18 18:32 UTC, jmkostina commented
обновила файлы .cabal, MyLib.hs, TestsSpec.hs
Ошибки по `cabal test` и `hlint` исправила или прокоментировала
по тестам для деревьев - поскольку у нас не было отдельного курса по тестированию, прошу уточнить, какие тесты на деревья Вы бы хотели еще увидеть

2023-10-18 23:25 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +      take 3 . filter' even $ [1..] `shouldMatchList` ([2,4,6] :: [Int])
Неправильное использование `$`. Почитай, как работает этот оператор

2023-10-18 23:26 UTC, pluralia commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
Неправильное использование $. Почитай, как работает этот оператор

2023-10-18 23:27 UTC, pluralia commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
> : - берет список от x до acc

Что это значит?

> потому что при сборке cabal test ругается на несоответствие типов, которое для меня не понятно

Неправильное использование `$`

2023-10-18 23:30 UTC, pluralia commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
Простейший вариант -- развернуть список (не зачту)
Более адекватный и предпочтительный -- пропустить первые встретившиеся элементы, когда пойдешь с конца

2023-10-18 23:35 UTC, pluralia commented
Вижу и ворнинги компилятора, и hlint -- комментариев не нахожу

> по тестам для деревьев - поскольку у нас не было отдельного курса по тестированию, прошу уточнить, какие тесты на деревья Вы бы хотели еще увидеть

Тебе не требуется специфических знаний -- тесты, которые есть, нормальные. Просто добавь еще тестов на деревья другой структуры -- по 2-3 штуки

2023-10-19 19:26 UTC, jmkostina commented on HT2/src/MyLib.hs
> +filter' condition = L.foldl'(\acc x -> if condition x then x:acc else acc)[]
поправила в тестах

2023-10-19 19:26 UTC, jmkostina commented on HT2/src/MyLib.hs
> +map' f = foldr (\x acc -> f x:acc) []
значит, что все элементы до `x` мы уже обработали, остался список от `x` до конца
тест поменяла в новом файле

2023-10-19 19:26 UTC, jmkostina commented on HT2/src/MyLib.hs
> +take'' n = foldr (\x acc -> if length' acc < n then x:acc else acc) []
нет, я не сделаю

2023-10-19 19:26 UTC, jmkostina commented
я обновила файлы, комментарии должны быть видны

у меня всего 4 hint - 2 в тестах и 2 в библиотеке
от компилятора у меня один ворнинг `[-Wtype-defaults]` на `length' [1, 3..10] `shouldBe` (5 :: Int)`, но откуда тут это берется не понятно, потому что я и в других местах использую список с арифметической прогрессией и там нет ворнингов

добавила по одному примеру деревьев в dfs/bfs, чтобы была видна разница обходов

2023-10-20 08:24 UTC, pluralia commented on HT2/src/MyLib.hs
> +-- у меня всего 4 hint - 2 здесь и 2 в тестах
Ок

2023-10-20 08:24 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +-- у меня всего 4 hint - 2 здесь и 2 в библиотеке
hlint -- это не про "рабочесть", а про читаемость и качество кода, и рекомендация более, чем адекватная: лямбды нужно "сокращать"

В этот раз снижать баллы не буду, но в следующий раз за такое снижу

2023-10-20 08:24 UTC, pluralia commented on HT2/test/TestsSpec.hs
> +    -- здесь cabal test поругался на warning: [-Wtype-defaults] но я не вижу для этого причин
Тут он просто грустит, что не знает до конца тип списка. Если укажешь, все будет ок

В остальных местах он не грустит, потому что может вывести тип полученного значения из аннотации желаемого
Почему он может не вывести здесь тоже? length возвращает значение не из списка и не модификацию значения из списка

2023-10-20 08:24 UTC, pluralia commented on HT2/test/TestsSpec.hs
>        map' (*5) [1, 3..10] `shouldBe` ([5,15,25,35,45] :: [Int])
Здесь ты использовала лямбду. Почему, если hlint-рекомендации по замене на лямбду считаешь нерелевантными?

2023-10-20 08:42 UTC, pluralia commented
Ок, сдала. Снижаю баллы, потому что:
-0,75 — fibSum (поставила 0,25 не смотря на то, что реализация сдана после дедлайна)
-0,25 — take’'
-0,25 -- filter скопирован
-2,25 — tree тоже

2023-10-20 08:42 UTC, closed without merging