HW02
pluralia/fp-fall-2023 pull request #12
Opened 2023-10-15 09:14 UTC by SophiaLaz

2023-10-15 14:24 UTC, pluralia requested changes
1. Запускаются ли у тебя тесты?
* опечатка if -> it
* везде нужно исправить `==` на `shouldBe` -- посмотри пример в практике

2. hlint сильно ругается

2023-10-17 12:54 UTC, pluralia requested changes
1. Исправь, пожалуйста, ворнинги компилятора и hlint
2. Добавь тесты

2023-10-17 12:54 UTC, pluralia commented on src/MyLib.hs
> +take'' left = snd . takeHelper
Здесь было лучше сделать композицию snd . foldr ..., а хелпер только для функции сверки

2023-10-17 12:54 UTC, pluralia commented on test/TestSpec.hs
> +-- Number 4
В этом блоке хотелось бы больше тестов

2023-10-17 12:54 UTC, pluralia commented on test/TestSpec.hs
> +-- Number 5
Больше тестов на деревья

2023-10-17 15:11 UTC, SophiaLaz commented on src/MyLib.hs
> +filter' f = foldr (\x b -> if f x then x : b else b) []
Я подумала, что нужно учесть случай бесконечных списков.

2023-10-17 20:26 UTC, pluralia commented
👍

2023-10-17 20:26 UTC, closed without merging