Add files via upload
pluralia/fp-fall-2023 pull request #13
Opened 2023-10-15 09:18 UTC by Artem9999999999999999999999

2023-10-20 18:28 UTC, pluralia requested changes
1. Много ворнингов и hlint-рекомендаций -- исправь, пожалуйста. В этот раз не буду снижать баллы за это, потому что ты открыл PR до того, как я написала о таком условии, но, если при следующей проверке этого PR ворнинги останутся, снижу
2. Нужны более сложные деревья для тестов
3. Добавь везде сигнатуры функций в классах типов -- с расширением InstanceSIgs будет работать

2023-10-20 18:28 UTC, pluralia commented on hw03/src/MyLib.hs
> +pointful a b c   = a b $ c -- можем удалить последний элемент
Это неверный переход. Удалить d можно, но по другой причине

2023-10-20 18:28 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- и возникают ошибки компиляции со всем кодом из 6 и 7 заданий, но при :r все компилируется.
Ушли ли ошибки с подключением расширений?

2023-10-20 18:28 UTC, pluralia commented on hw03/src/MyLib.hs
> +data Monday = Chest
Почему не newtype?

2023-10-20 18:28 UTC, pluralia commented on hw03/src/MyLib.hs
> +instance GumRats Monday where
Код максимально искусственный

Какая задача здесь стоит? По дню недели определить на какую часть дела происходит активность. Реши эту задачу, используя класс типов GumRats

2023-10-21 04:00 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
Первое расширение позволяет определять экземпляры типовых классов более гибко. А второе позволяет явно указывать сигнатуры типов для методов класса типов в экземпляре, так без указания последнего расширения у меня возникали ошибки при компиляции, а после его добавления все стало компилироваться.

2023-10-21 04:02 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +Какой-то прикол с компиляцией для этой функции при запуске cabal test, хотя при :r ошибок не возникает и тесты в консоли работают
Это помогло, спасибо!

2023-10-21 04:15 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +        show tree `shouldBe` "2453514535"
Видимо, ошибка в функции, она несколько раз ходит в одни и те же узлы

2023-10-21 04:18 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +-- и возникают ошибки компиляции со всем кодом из 6 и 7 заданий, но при :r все компилируется.
Да, я их уже исправил, но комментарий не удалил. Они были связаны с тем, что я не подключил deriving(Eq) и в тестах не работал ShouldBe

2023-10-21 04:31 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +data Monday = Chest
Сейчас в целом переделал этот дата класс, а так, да, нужно было newtype использовать

2023-10-21 05:00 UTC, Artem9999999999999999999999 commented
Исправил ворнинги при запуске cabal test, при :l :r их не было и не появилось
![image](https://github.com/pluralia/fp-fall-2023/assets/113240536/4a81b059-f4c7-4fd9-8fc6-0dcb5d321af3)
Также исправил hlint
![image](https://github.com/pluralia/fp-fall-2023/assets/113240536/9a788627-b7b2-4059-beb6-ba78761c8f6a)

2023-10-21 05:00 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +instance GumRats Monday where
Исправил

2023-10-21 05:03 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +Тут была куча ошибок при компиляции и при запуске cabal test.
Осталась проблема  с компиляцией тестов, они все еще не работают

2023-10-21 05:16 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +Тут была куча ошибок при компиляции и при запуске cabal test.
Она разрешилась импортом в файле тестов

2023-10-21 05:19 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +-- я бы на этом остановился, потому что код стал максимально нечитаемым
Исправил. Такие штуки прям очень пугают, думаю, что если в коде увижу такой поинт фри стайл, даже не доведенный до онли точек, то я не пойму что вообще происходит

2023-10-21 05:19 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +        show tree `shouldBe` "2453514535"
Исправил

2023-10-21 05:57 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +{-
Раскомментировал

2023-10-21 06:02 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +    describe "Num instance for ChurchNumber" $ do
```
    fromInteger :: Integer -> ChurchNumber
    (+) :: ChurchNumber -> ChurchNumber -> ChurchNumber
    (-) :: ChurchNumber -> ChurchNumber -> ChurchNumber
    (*) :: ChurchNumber -> ChurchNumber -> ChurchNumber
    abs :: ChurchNumber -> ChurchNumber
    signum :: ChurchNumber -> ChurchNumber
```
а какие еще?

2023-10-21 09:48 UTC, pluralia commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
> Первое расширение позволяет определять экземпляры типовых классов более гибко

Что значит "более гибко"?

2023-10-21 09:50 UTC, pluralia commented on hw03/test/TestSpec.hs
> +    describe "Num instance for ChurchNumber" $ do
Ты реализовал все, но не на все есть тесты

2023-10-21 09:58 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- я бы на этом остановился, потому что код стал максимально нечитаемым
Да, есть такое) Цель упражнения не показать, что так нужно писать вообще всегда, а отработать паттерны приведения к point-free. Сделав эту таску вы должны преисполниться и легко применять элементы point-free в жизни, где это имеет смысл. Сравни:
```
fun1 f g h = f . g . h
fun2 f g h x = f (g (h x))
```
Очевидно, **что** читается лучше, *если привык к такой нотации*

2023-10-21 10:11 UTC, pluralia commented
У меня все еще куча ворнингов
<img width="421" alt="Screenshot 2023-10-21 at 12 11 22" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/02605d9c-76a4-46f6-8268-005837df543c">

2023-10-21 13:28 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +-- я бы на этом остановился, потому что код стал максимально нечитаемым
Да, просто они понятные, когда ты сам выводишь их и совсем не понятные, если ты сразу видишь голый поинт фри стайл, но скорее всего это дело привычки

2023-10-21 14:39 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +В задании написано чеерез Data
Наш тип данных имеет только один конструктор с
одним полем, на лекции мы говорили, что такие вещи лучше определять как
newtype, потому что он более эффективно
представляется во время исполнения

2023-10-21 14:40 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +        show tree `shouldBe` "24531"
Добавил

2023-10-21 14:40 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +    describe "Num instance for ChurchNumber" $ do
Понял, добавил тесты

2023-10-21 14:42 UTC, Artem9999999999999999999999 commented on hw03/test/TestSpec.hs
> +    describe "ToCMYK instance for RGB" $ do
Работала плохо, исправил, теперь работает хорошо

![image](https://github.com/pluralia/fp-fall-2023/assets/113240536/40c1ff99-d434-42e8-b71c-a188c176a154)

2023-10-21 14:43 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +instance ToCMYK RGB where
исправил

2023-10-21 14:43 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +        c = 100 - (r * 100) `div` 255
была идея использовать целочисленное деление (как в классах типов через функции), но математика не сошлась, переписал это задание.

2023-10-21 14:43 UTC, Artem9999999999999999999999 commented
Ага, увидел эти ворнинги. А почему в ```cabal test``` их не видно было?
Я их почистил теперь ничего не видно
![image](https://github.com/pluralia/fp-fall-2023/assets/113240536/4bce0290-772e-443a-a1b1-8f6fe6c20702)

2023-10-21 14:46 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
То есть он разрешает определение экземпляров класса типов с произвольными вложенными типами в заголовке экземпляра.

2023-10-23 16:06 UTC, pluralia commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
Пример?

2023-10-23 16:14 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- я бы на этом остановился, потому что код стал максимально нечитаемым
Голый обычно не придется видеть: если увидишь у коллеги -- вызови на дружескую беседу о том, как лучше писать код ;)

На всякий случай повторю: в реальной жизни будут использоваться только элементы point-free стиля, поэтому страдать не придется. Но чтобы эти элементы использовать легко, к ним нужно привыкнуть -- этим мы и занимаемся в этом задании

2023-10-24 05:09 UTC, Artem9999999999999999999999 commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
Например, если мы уберем это расширения, то компилятор начнет ругаться на определение инстанса с конкретным указанием типа.
В общем, виде это можно описать так:
без расширения инстансы определяем так: 
```
instance C [a] where
```
а с расширением можем определить инстанс для конкретного типа:
```
instance C [Int] where
```

где C это какой-то уже реализованный класс типов

2023-10-24 05:11 UTC, Artem9999999999999999999999 commented
Все поправил

2023-10-24 07:58 UTC, pluralia commented
9,5 👍

2023-10-24 07:58 UTC, closed without merging