HW03_ShchukinIA
pluralia/fp-fall-2023 pull request #14
Opened 2023-10-15 19:43 UTC by paiksonn

2023-10-17 20:34 UTC, pluralia requested changes
У тебя ничего не компилируется и "битые" тесты -- исправь, пожалуйста

2023-10-17 20:34 UTC, pluralia commented on src/MyLib.hs
> +-- все еще не понимаю, что нужно сделать с rgb инстансом
Определить класс типов и инстансы через функции -- посмотри в практике [здесь](https://github.com/pluralia/fp-fall-2023/blob/hw03/prac03.hs#L12-#L24)

2023-10-17 20:34 UTC, pluralia commented on src/MyLib.hs
> +-- не понял, что значит сделать инстанс класса ToCMYK для RGB :c
Нужен `instance ToCMYK RGB where ... `

2023-10-17 20:34 UTC, pluralia commented on src/MyLib.hs
> +-- можно было бы и дальше упрощать до состояния "совы", но кому оно надо, нечитаемо же
Загуглил -- молодец) Нужно для баллов домашки

2023-10-17 20:34 UTC, pluralia commented on src/MyLib.hs
> +-- 5.b Реализуйте следующие функции
Используй инстанс `Enum`

2023-10-17 20:34 UTC, pluralia commented on src/MyLib.hs
> +instance Bifunctor Either where
[Обновила домашку](https://github.com/pluralia/fp-fall-2023/blob/hw03/hw03.hs#L196-197) -- используй `Either'`

2023-10-18 04:35 UTC, paiksonn commented on src/MyLib.hs
> +-- все еще не понимаю, что нужно сделать с rgb инстансом
Я не понимаю, что именно именно он должен делать: переводить из CMYK в RGB? Или что-то другое?

2023-10-18 04:36 UTC, paiksonn commented on src/MyLib.hs
> +-- можно было бы и дальше упрощать до состояния "совы", но кому оно надо, нечитаемо же
Т.е. нужно доделать до состояния только точек и все?

2023-10-18 04:38 UTC, paiksonn commented on src/MyLib.hs
> +-- 5.b Реализуйте следующие функции
Хорошо, переделаю и залью решение

2023-10-18 04:38 UTC, paiksonn commented on src/MyLib.hs
> +instance Bifunctor Either where
Понял, сейчас переделаю

2023-10-18 04:45 UTC, paiksonn commented on src/MyLib.hs
> +module MyLib where
1) Согласно гуглу нужно, чтобы определять экземпляры классов типов для типов данных, которые не соответствуют точному шаблону, заданному в классе. Ну т.е. чтобы можно было, например, определить экземпляр класса типов для списка списков, даже если класс типов ожидает просто список. Т.е. можно более общий код писать.

2) Согласно тому же гуглу, оно нужно, чтобы явно указывать сигнатуры методов класса в экземплярах этого класса.

2023-10-18 04:46 UTC, paiksonn commented on src/MyLib.hs
> +module MyLib where
Они же добавляются в файл MyLibTest.hs , верно?
К `{-# OPTIONS_GHC -F -pgmF hspec-discover #-}`

2023-10-18 04:49 UTC, paiksonn commented
> У тебя ничего не компилируется и "битые" тесты -- исправь, пожалуйста

Видимо что-то поломалось, когда делал копипаст моего кода в файл со старым кодом - у меня все запускается. Сейчас переделаю некоторые задания и запушу новый файл целиком с компьютера, а не через копипаст

2023-10-18 04:58 UTC, paiksonn commented on src/MyLib.hs
> +instance Bifunctor Either where
Если я правильно понял, то надо реализовать только инстанс `Functor` для `Either`, т.к. для `Pair` я его реализовывал выше, в предыдущем задании

2023-10-18 08:10 UTC, paiksonn commented
Заапдейтил код через подгрузку, а не изменение исходного, так что сейчас ничего не должно поехать/не компилиться/etc. Я надеюсь, что предыдущая проблема с этим решена и она не отразится на результатах по баллам за это дз. Не отразится же?

Ворнингов от компилятора не было, hlint тоже молчал (хотя я тут недавно чистил диск от лишних либ и мог случайно зацепить его, т.к. суммарно либы хаскеля занимали 10 гб и я удалял наиболее весомые) 

В целом, в ручную все тесты и функции запускаются и работают как надо (я проверил ручками почти функции, вводя тесты через консоль).

Единственное, что 3 задание я так и не переделал, т.к. я не понимаю, что оно должно делать. Почему-то именно это задание вызвало трудности, если не сложно, то можешь, пожалуйста, подробнее и с примерами объяснить этот момент?

2023-10-18 08:16 UTC, paiksonn commented on src/MyLib.hs
> +-- можно было бы и дальше упрощать до состояния "совы", но кому оно надо, нечитаемо же
доделал до состояния точек

2023-10-18 08:55 UTC, pluralia commented on src/MyLib.hs
> +-- все еще не понимаю, что нужно сделать с rgb инстансом
переводить из CMYK в RGB

2023-10-18 08:58 UTC, pluralia commented on src/MyLib.hs
> +-- можно было бы и дальше упрощать до состояния "совы", но кому оно надо, нечитаемо же
4 с объяснением должен быть каждый шаг

2023-10-18 09:01 UTC, pluralia commented
> Я надеюсь, что предыдущая проблема с этим решена и она не отразится на результатах по баллам за это дз. Не отразится же?

В этот раз не отразится -- я написала о -2 баллах после того, как ты это все дело залил. Но у всех будущих PR баллы будут вычитаться, если будет что-то битое

По 3 заданию: напиши конкретные вопросы, и я на них отвечу

2023-10-18 14:45 UTC, paiksonn commented
> По 3 заданию: напиши конкретные вопросы, и я на них отвечу

По 3 заданию:
вот сначала нужно написать инстансы класса toCMYK. Для [Int] это означает, что на вход приходит массив чисел и если все они от 0 до 100, то они каким-то образом превращаются в цвета? А для RGB это означает, что на вход приходит массив RGB цветов (3 цвета) и их нужно каким-то образом (каким?) перевести в массив из SMYK цветов (4 цвета)?

2023-10-18 23:16 UTC, pluralia commented
> Для [Int] это означает, что на вход приходит массив чисел и если все они от 0 до 100, то они каким-то образом превращаются в цвета?

Тебе нужно загуглить, что такое CMYK

> А для RGB это означает, что на вход приходит массив RGB цветов (3 цвета) и их нужно каким-то образом (каким?) перевести в массив из SMYK цветов (4 цвета)?

Тебе нужно загуглить, как конвертить RGB в CMYK

> Для класса DtoSMYK нужно реализовать то же самое, только когда класс типов немного по другому задан?

Нет класса DtoSMYK -- есть тип данных, поля в котором -- функции, соответствующие функциям из класса типов `ToCMYK`. А инстанс -- функция

2023-10-19 14:41 UTC, paiksonn commented
Я почитал, что в гугле написано для RGB/SMYK и сделал 3 таску, надеюсь правильно

2023-10-20 18:36 UTC, pluralia requested changes
1. Много ворнингов, hlint-рекомендаций еще и **битые тесты** -- исправь, пожалуйста. Я уже смотрела твою домашку и не стала снижать тебе баллы, потому что ты открыл PR до того, как я написала об обязательном исправлении ворнингов. Hо я уже смотрела твою домашку, а ты ничего не исправил. В качестве поощрения, что ты открыл PR заранее, я дам тебе еще один шанс исправить все это добро, но, если при следующем ревью твоего PR что-то останется, баллы сниму по полной
2. Добавь везде сигнатуры функций в классах типов -- с расширением InstanceSIgs будет работать

2023-10-20 18:36 UTC, pluralia commented on src/MyLib.hs
> +-- pointful a b c   = a b $ c         -- удаляем d
Это неверный переход. Удалить d можно, но по другой причине

2023-10-20 18:36 UTC, pluralia commented on src/MyLib.hs
> +-- Pair неизменяемый тип данных, так что нельзя просто применить что-то к элементам пары
Что значит "Pair неизменяемый тип данных"?

2023-10-20 18:36 UTC, pluralia commented on src/MyLib.hs
> +-- Почитал stakoverflow, там по первой ссылке в гугле "functor for pair haskell" хорошо объяснено
Отлично! Теперь перерасскажи мне своими словами здесь

2023-10-24 13:01 UTC, paiksonn commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs      #-}
{-# LANGUAGE FlexibleInstances #-} нужно для того, чтобы более гибко определять экземпляры типов
{-# LANGUAGE InstanceSigs      #-} нужно для того, чтобы явно указывать тип функции

2023-10-24 13:35 UTC, paiksonn commented on src/MyLib.hs
> +-- Функция преобразования числа Чёрча в число обычное
в Num

2023-10-24 15:16 UTC, pluralia commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs      #-}
> нужно для того, чтобы более гибко определять экземпляры типов

Разверни мысль, пожалуйста

2023-10-24 15:55 UTC, paiksonn commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs      #-}
Без этого расширения сигнатуры экземпляров классов типов должны быть структурно одинаковыми, и параметры типов должны совпадать точно, а с ним это правило можно нарушать

2023-10-24 16:01 UTC, paiksonn commented on src/MyLib.hs
> +-- Pair неизменяемый тип данных, так что нельзя просто применить что-то к элементам пары
Имелось ввиду, что `fmap` может поменять только последний элемент в паре, а не оба сразу. Так работает по построению, собственно, самого `fmap`, т.к. он принимает на вход `f a`

2023-10-24 16:06 UTC, paiksonn commented on src/MyLib.hs
> +-- Почитал stakoverflow, там по первой ссылке в гугле "functor for pair haskell" хорошо объяснено
Там если уходить в глубину определений, то `[class Functor (f :: Type -> Type)]` (взял с hoogla), а те же Either/Pair дают больше одного свободного типа

2023-10-24 16:10 UTC, paiksonn commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs      #-}
Ну т.е., например, можно делать инстанс с какой-нибудь специализацией внутри а-ля `[[Int]]` или `[[String]]`

2023-10-24 16:12 UTC, paiksonn commented on src/MyLib.hs
> +  toCMYK :: RGB -> Maybe CMYK
Что это означает?
Я что-то не понял

2023-10-24 16:23 UTC, paiksonn commented
- Файл MyLib.hs переделал с учетом комментариев. Hlint в нем молчит, есть некоторое количество ворнингов, никак не влияющих на работу (они возникают из-за одинаковых имен переменных и компилятор ругается на возможный shadowing)
- Файл TestSpec.hs частично переделал. Оставил работающую часть тестов, остальные закомменчены (постараюсь успеть их переделать позже). Ворнингов и пожеланий hlint в этом файле нет.

2023-10-24 16:57 UTC, pluralia commented on src/MyLib.hs
> +  toCMYK :: RGB -> Maybe CMYK
Попробуй `toCMYK (UnsafeMkRGB 125 130 160)` -- верный ли результат?

2023-10-24 17:08 UTC, pluralia commented
1. shadowing нужно убрать, а еще там есть `-Wtype-defaults`; shadowing ты прокомментировал, а `-Wtype-defaults` буду считать, что не заметил, поэтому пока не снижаю
2. Можно скриншот, что у тебя hlint молчит? У меня 11 hints в MyLib

2023-10-24 17:52 UTC, paiksonn commented
1. `Wtype-defaults` возникает в местах, где у меня указан тип данных `Int`, но я там использую `/ 255.0` и компилятору приходится самому переводить `Double` в `Int`
2. Не знаю, честно говоря, почему так. Hlint может быть глючит, попробую переустановить его

2023-10-26 22:02 UTC, pluralia commented
Тесты есть, но закомментированы -- снижаю на ~25%
-0,5 -- hlint
-1,5 -- 2a
-0,25 -- нет тестов для 2b
-0,75 -- неверная конверсия в 3a/b; тесты закомментированы и однообразны
-0,25 -- тесты закомментированы для 5
-0,5 -- тесты закомментированы для 6 и 7

Итог: 6,25

2023-10-26 22:02 UTC, closed without merging