HW03_DmitrievOS
pluralia/fp-fall-2023 pull request #15
Opened 2023-10-16 17:45 UTC by qilowoq

2023-10-20 18:33 UTC, pluralia requested changes
Много ворнингов -- исправь, пожалуйста. В этот раз не буду снижать баллы за это, потому что ты открыл PR до того, как я написала о таком условии, но, если при следующей проверке этого PR ворнинги останутся, снижу

2023-10-25 15:40 UTC, qilowoq commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Нашел их в интернетах. Нужны были для того, чтобы переопределить Instance Show String (тк стандартная реализация очень плохо выводит список из строк:

```
ghci> show ["1", "2"]
"[\"1\", \"2\"]"
```

Если я бы сразу нашел какую-то другую реалиазацию. Я бы не использовал эти расширения

2023-10-25 16:13 UTC, qilowoq commented on hw3/test/TestSpec.hs
> +
Не понял. Вроде же написаны

2023-10-25 16:47 UTC, qilowoq commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
`intercalate :: [a] -> [[a]] -> [a]]` у нас не факт, что value будет типа String

2023-10-25 19:01 UTC, pluralia commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
> `InstanceSigs`  ... Вещь бесполезная

Неправда. Типы в Haskell помогают ориентироваться в том, что делает функция, и тебе, и компилятору. Да, ты можешь заглянуть в определение класса, но круто, когда у тебя это все перед глазами. + Если ты используешь FlexibleInstances, тип функций класса типов может стать более специфичным, и хорошо его указать

2023-10-25 19:01 UTC, pluralia commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Для чего используется FlexibleInstances вообще, а не только у тебя в коде?

2023-10-25 19:03 UTC, pluralia commented
Зря удалил `InstanceSigs` -- верни, пожалуйста

2023-10-25 19:05 UTC, pluralia commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
Разверни мысль

2023-10-25 19:06 UTC, pluralia commented on hw3/test/TestSpec.hs
> +
Верно, пропустила 👍

2023-10-25 19:17 UTC, pluralia commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
По-прежнему не понимаю, в чем проблема, ответ верный с Just и в тестах, и в repl

2023-10-26 00:16 UTC, qilowoq commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
Хм. странно у меня проваливает этот тест

```
Running 1 test suites...
Test suite hw03-test: RUNNING...

Test
  ChurchNumber
    Eq [✔]
    Num [✔]
    Ord [✔]
    Ix [✔]
  Tree
    Show Pre [✔]
    Show In [✔]
    Show Post [✔]
    Eq [✔]
  CMYK
    returns the correct result [✘]
  DAY
    returns the correct result [✔]
  Functor
    returns the correct result [✔]
  Bifunctor
    returns the correct result [✔]

Failures:

  test/TestSpec.hs:130:39: 
  1) Test.CMYK returns the correct result
       expected: Just (UnsafeMkCMYK {cyan = 0, magenta = 0, yellow = 0, black = 100})
        but got: Nothing

  To rerun use: --match "/Test/CMYK/returns the correct result/" --seed 1154847601

Randomized with seed 1154847601

Finished in 2.2382 seconds
12 examples, 1 failure

Test suite hw03-test: FAIL
```

2023-10-26 00:25 UTC, qilowoq commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
Я вот это имею в виду:

Если у меня у дерева value типа String, то `intercalate`  работает ок
```
ghci> intercalate ", " ["Lorem", "ipsum", "dolor"]
"Lorem, ipsum, dolor"

```
Второй аргумент здесь - список value получаемый при обходе. Но нам никто не запрещает сделать value типа Int. например:

```
ghci> intercalate ", " [3, 2, 1]

<interactive>:5:19: error:
    • No instance for (Num [Char]) arising from the literal ‘3’
    • In the expression: 3
      In the second argument of ‘intercalate’, namely ‘[3, 2, 1]’
      In the expression: intercalate ", " [3, 2, 1]

```

И тогда все валится

2023-10-26 00:41 UTC, qilowoq commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
`InstanceSigs` дает явно указывать типы методов класса типов при их определении. Ну по крайней мере для этого я использовал, вроде других функций у него нет

2023-10-26 08:31 UTC, pluralia commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Cпрашивала про `FlexibleInstances`. `InstanceSigs` ты уже ответил :)

2023-10-26 08:34 UTC, pluralia commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
Это решается так: `intercalate ", " . fmap show $ [3, 2, 1]`

Как в случае задания с деревом можно получить гарантии, что к значениям в дереве можно применять `show`?

2023-10-26 11:03 UTC, pluralia commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
У меня по-прежнему все ок.

Попробуй `cabal clean && cabal test`. Если не поможет, можешь попросить одногруппников загрузить твой репо и запустить тесты на их машине

2023-10-26 14:34 UTC, qilowoq commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
Это мало что меняет. Так же некрасиво:

```
ghci> intercalate ", " . fmap show $ [3, 2, 1]
"3, 2, 1"

ghci> intercalate ", " . fmap show $ ["3", "2", "1"]
"\"3\", \"2\", \"1\""
```

"Как в случае задания с деревом можно получить гарантии, что к значениям в дереве можно применять show?" Мы уже это ведь делаем:

`instance (Show a) => Show (PreOrder a) where`

2023-10-26 14:47 UTC, qilowoq commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Туплю. Я почитал и `FlexibleInstances` используется для того, чтобы определять экземпляры классов типов для нестандартных типов.  Стандартные это Int, Bool, списки типо такого. Поэтому, чтобы определить, например, `instance ToCMYK [Int] where`, нужно это расширение

2023-10-26 15:11 UTC, qilowoq commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
`cabal clean && cabal test` не помог. Это тема у меня на двух разных машинах.

2023-10-26 15:53 UTC, pluralia commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Не совсем. Как насчет такого:
```haskell
class MyClass a where

instance MyClass [a] where

instance MyClass [RGB] where
```
Здесь мы добавили специализацию для списка на тип RGB -- это нестандартный тип, но FlexibleInstances нам нужно все равно

2023-10-26 15:54 UTC, pluralia commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
Если хочешь, можем после практики остаться и посмотреть у меня / у тебя, в чем может быть проблема

2023-10-26 16:56 UTC, qilowoq commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
Хорошо

2023-10-26 16:56 UTC, qilowoq commented on hw3/src/MyLib.hs
> +instance {-# OVERLAPPING #-} Show String where
Поменял

2023-10-26 16:56 UTC, qilowoq commented on hw3/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Понял

2023-10-26 19:44 UTC, pluralia commented
👍

2023-10-26 19:44 UTC, closed without merging

2023-10-29 16:42 UTC, pluralia commented on hw3/test/TestSpec.hs
> +      -- ... but got: Nothing ?????????? Не понимаю в чем дело
@qilowoq, попробуй добавить `traceShow (c, m, y, k) $ mkCMYK c m y k` [здесь](https://github.com/qilowoq/fp-fall-2023/blob/hw03/hw3/src/MyLib.hs#L259), после чего загляни в логи. Пусть до .log файла будет указан после запуска тестов "Test suite logged to: ..."

2023-11-04 18:40 UTC, pluralia commented on hw3/src/MyLib.hs
> +        c = if k == 1 then 0 else (round $ (1.0 - r' - k') / (1.0 - k') * 100.0) :: Int
@qilowoq, проблема с тестами возникла из-зa сравнения k, которое типа Double. При сравнении Double не может быть точного равенства, поэтому тесты падают. А вот почему ghci (или у меня( не подает -- загадка; видимо, какие-то оптимизации происходят.

Как можно исправить: заменить равенство на `abs (k - 1) < 1e-5`

2023-11-04 18:41 UTC, pluralia commented on hw3/src/MyLib.hs
> +     in mkCMYK c m y k
Чтобы такие вещи отлавливать, нужно заменить
`mkCMYK c m y k` на `traceShow (k', k, ...) $ mkCMYK c m y k`