Hw03_Pushkina_Olga
pluralia/fp-fall-2023 pull request #16
Opened 2023-10-19 12:28 UTC by forestcream

2023-10-20 19:34 UTC, pluralia requested changes
1.  -1 балл из-за ворнингов и hlint. Исправь, пожалуйста, иначе не приму домашку
2. Нужны более сложные деревья для тестов
3. Можно доделать 6c (похоже, ты над ним размышляла) и 7 задание

2023-10-20 19:34 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- Реализуйте инстанс Functor для Either и пары
Конечно же нужно было инстанс Bifunctor. Можно доделать

2023-10-20 19:34 UTC, pluralia commented on hw03/src/MyLib.hs
> +data MyHoroscope = MyHoroscope { mySign :: String, myPrediction :: String }
Самый функциональный пример из всех домашек, которые видела 👍

2023-10-24 10:52 UTC, forestcream commented on hw03/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances #-}
InstanceSigs - позволяет явно указывать типы, когда мы объявляем экземпляр класса типа (если его не добавить, компилятор выдает ошибку)
FlexibleInstances  - позволяет явно указывать, что за тип мы хотим при объявлении экземпляра

2023-10-24 11:01 UTC, forestcream commented on hw03/src/MyLib.hs
> +        enumFromToChurch :: ChurchNumber -> ChurchNumber -> [ChurchNumber]
```
range (n1, m1)
      | n1 > m1     = []
      | n1 == m1    = [m1]
      | otherwise = n1 : range (Succ n1, m1)
      ```

2023-10-24 11:10 UTC, forestcream commented on hw03/src/MyLib.hs
> +        churchToInt :: ChurchNumber -> Integer
Я не очень понимаю вопрос, у меня есть fromInteger, но она делает ровно обратное

2023-10-24 12:10 UTC, pluralia commented on hw03/src/MyLib.hs
> +        churchToInt :: ChurchNumber -> Integer
> У тебя уже есть реализация этой функции. Как она называется?
Это неверно... У вас нет реализации функции для ChurchNumber, на которую намекаю.

Давай задам вопрос иначе. Вы реализовывали в домашке класс типов, в котором есть, по сути, эквивалент churchToInt (т.e. конверсия типа к Int). Что это за класс типов?

2023-10-25 07:26 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- С какими трудностями вы столкнулись? - Pair принимает 2 аргумента, а Functor 1, но что с этим делать я не придумала
```
data Pair a b = Pair a b
  deriving (Show)

instance Functor (Pair a) where
  fmap :: (b -> c) -> Pair a b -> Pair a c
  fmap f (Pair x y) = Pair x (f y)
```
Можно как будто фиксировать один из параметров, например, а.  И тогда functor принимает всего 1 параметр. Но, честно говоря, выглядит странно, хотя вроде и работает

2023-10-25 08:01 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- Реализуйте инстанс Functor для Either и пары
```
instance Bifunctor MyEither where
  bimap :: (a -> d) -> (b -> e) -> MyEither a b -> MyEither d e
  bimap f _ (MyLeft x) = MyLeft (f x)
  bimap _ g (MyRight y) = MyRight (g y)

data MyPair a b = MyPair a b

instance Bifunctor MyPair where
  bimap :: (a -> d) -> (b -> e) -> MyPair a b -> MyPair d e
  bimap f g (MyPair x y) = MyPair (f x) (g y)
```

2023-10-25 08:02 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
```
-- pointful a b c d = a b (c d)
-- pointful a b c = \d -> a b (c d) - заменяем d на лямбду фунцию
-- pointful a b = \c d -> a b (c d) -  то же самое с с
-- pointful a b = \c -> a b . c - откидываем d
```

2023-10-25 08:10 UTC, forestcream commented on hw03/src/MyLib.hs
> +        churchToInt :: ChurchNumber -> Integer
Enum, который реализовывали для дней недель делал ровно это - конвертировал в Int

2023-10-25 08:10 UTC, forestcream commented on hw03/src/MyLib.hs
> +    show :: Show a => InOrder a -> String
```
-- | in-order обход дерева
--
newtype InOrder a = In (Tree a)

instance Show a => Show (InOrder a) where
    show :: Show a => InOrder a -> String
    show (In (Node v [])) = show v
    show (In (Node v ts)) = show v ++ " " ++ unwords ( map (show . In) ts)
```

2023-10-25 08:17 UTC, forestcream commented
1. Из ворнингов остались только про цвета из 3 задания - то что там названия совпадают. Это можно исправить заменив на какие-то чуть измененные названия цветов (`red1`, `green1`), но это испортит читаемость. Так же hlint предлагает в строчке `data DToCMYK a = MkToCMYK { toCMYK' :: a -> Maybe CMYK }` предлагает поменять на `newtype`, но в задании было указано использовать именно `data`
2. Добавила более сложные деревья в коммите

2023-10-25 12:51 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- С какими трудностями вы столкнулись? - Pair принимает 2 аргумента, а Functor 1, но что с этим делать я не придумала
> Но, честно говоря, выглядит странно, хотя вроде и работает

Согласна, но иначе функтор к паре не применить

2023-10-25 12:54 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
Вот этот переход непонятен
```
-- pointful a b = \c d -> a b (c d) -  то же самое с с
-- pointful a b = \c -> a b . c - откидываем d
```

Кроме того, для полного балла за задание нужно убрать не только d, но и все остальные аргументы

2023-10-25 13:01 UTC, pluralia commented
> Это можно исправить заменив на какие-то чуть измененные названия цветов (red1, green1), но это испортит читаемость

Можно заменить на `red'` или `r`. Чтобы исправлять меньше, можно поменять имена полей в определении `data RGB` на `red'`, а имена переменных оставить как `red`

> Так же hlint предлагает в строчке data DToCMYK a = MkToCMYK { toCMYK' :: a -> Maybe CMYK } предлагает поменять на newtype

Здесь предложение использовать newtype верно -- это мой косяк, и за этот hint баллы не снижала. Помнишь, почему именно здесь нужно использовать newtype?

2023-10-25 16:14 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
Я переписала через $ иначе я сама немного запуталась в исключении переменных 
```
pointful a b c d = a b (c d)
                        = (a b) $ c $ d - закидываем c и d в конец
                        = (a . b) $ c $ d - заменяем (a b) на a.b
                        = (.)$(.) $ c $ d - заменяем (a . b) на просто композиции в нужном порядке
                        = (.)$(.) - откидываем c и d так как они последние агрументы
```

2023-10-25 16:26 UTC, forestcream commented
Заменила названия в коммите, теперь ничего не ругается
Мы используем newtype так как создаем новый тип на основе уже существующего, но мы меняем при этом его имя. И на сколько я помню он в общем более эффективный, чем просто data

2023-10-25 18:55 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
> закидываем c и d в конец

Что значит это значит? Мы не закидываем к конец и используем оператор, чтобы убрать скобки

> = (a . b) $ c $ d - заменяем (a b) на a.b

Так нельзя

2023-10-25 20:01 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
```
pointful a b c d = a b (c d)
                        = a b $ c d
                        = a b . c $ d
                        = a b . c 
                        = ((( . ) . a) b) c
                        = (( . ) . a) b
                        = (( . ) . a)
                        = (( . ) . )
```
сейчас сошлось с https://pointfree.io/

2023-10-25 20:13 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
Ответ верный -- хочется комментариев

2023-10-26 06:31 UTC, forestcream commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
```
pointful a b c d = a b (c d)
                        = a b $ c d -  заменяем скобочки на $, чтобы сохранить правильный порядок
                        = a b . c $ d - заменяем по вот этому правилу \x -> outside . inside $ x
                        = a b . c  -  и убираем d как вот здесь outside . inside
                        = ((( . ) . a) b) c - это как вот этот переход из презентации = \x -> f . (g x) -- ((.) f) (g x)
= \x -> ((.) f) (g x), только надо еще одну композицию добавить, чтобы не нарушить порядок
                        = (( . ) . a) b - убираем c
                        = (( . ) . a) - убираем a
                        = (( . ) . ) -  оставляем только точки
```

2023-10-26 08:21 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- pointful a b c d = a . b (c d) -- pointed f g x = f . g x          -- eta-reduction
Не все комментарии объясняют, почему мы все это можем сделать (например, "убираем с" -- почему можем?). Но ок, поставлю тебе полный балл, потому что явно сама делаешь.

2023-10-26 08:29 UTC, pluralia commented
👍

2023-10-26 08:29 UTC, closed without merging