Hw03 Kostina
pluralia/fp-fall-2023 pull request #17
Opened 2023-10-19 18:53 UTC by jmkostina

2023-10-20 18:39 UTC, pluralia requested changes
1.  -0,5 за ворнинги -- нужно исправить. hlint тоже, но ты его указала свое мнение про скобки, поэтому за него не снижаю
2. Добавь везде сигнатуры функций в классах типов -- с расширением InstanceSIgs будет работать
3. Добавь тесты на задания, которые выполнила -- поставлю полный балл
4. -2.5 за невыполненные задания

2023-10-20 18:39 UTC, pluralia commented on hw03/src/MyLib.hs
> +a b . c -> (.) (a b) (.) c - это по строчке выше
Комментарий верный, а переход -- нет. Почему (.) (a b) (.) c? Откуда вторая (.)?

2023-10-20 18:39 UTC, pluralia commented on hw03/src/MyLib.hs
> +data List a = Nil | Cons a (List a)
-1,5

2023-10-20 18:39 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- 6.c(*) Реализуйте инстанс Functor для пары (1 балл)
-1

2023-10-26 17:31 UTC, jmkostina commented on hw03/src/MyLib.hs
> +a b . c -> (.) (a b) (.) c - это по строчке выше
Вторая (.) не нужна
Должно быть `a b . c -> (.) (a b) c` и тогда с этого места
```haskell
(.) (a b) c -> (.) $ a b  - дроп с и замена скобок на оператор апликации $
(.) $ a b -> (.) . a $ b - замена оператора апликации $ на оператор композиции, перенос оператора апликации $ на переменную. Можно дропать
(.) . a -> (.) (.) а -> (.) (.) - перенос по * и дроп а
```

2023-10-26 17:31 UTC, jmkostina commented on hw03/src/MyLib.hs
> +-- я взяла формулы из https://www.101computing.net/cmyk-to-rgb-conversion-algorithm/
я начала переписывать и еще сильнее запуталась

2023-10-26 17:31 UTC, jmkostina commented on hw03/src/MyLib.hs
> +    show (In tree) = inOrderShow tree
по аналогии с `pre` и `post` должно быть только 2 элемента, тогда 
```haskell
instance Show a => Show (InOrder a) where
    show (In tree) = inOrderShow tree
      where
        inOrderShow (Node val ts) = concatMap inOrderShow ts ++ show val
```

2023-10-26 17:31 UTC, jmkostina commented on hw03/test/TestSpec.hs
> +
Не делала `Ix`

2023-10-26 17:31 UTC, jmkostina commented on hw03/test/TestSpec.hs
> +    describe "ChurchNumbers, Num" $ do
Добавила в обновленном файле

2023-10-26 17:31 UTC, jmkostina commented on hw03/test/TestSpec.hs
> +  -- во время тестирования компилятор не понимает, к чему относится Succ без скобок
Да, я неправильно его поняла. Скобки убрала

2023-10-26 17:31 UTC, jmkostina commented on hw03/src/MyLib.hs
> +-- честно пользовалась гуглом, до конца так и не разобралась, как это работает именно в инстансах haskell
В моем понимании реализация инстансов должна совпадать с тем как может выглядеть работа функции (то есть это по сути пример). Для меня обход деревьев - это суммирование трех элементов в общем случае, а мой последний инстанс в `pre` и `post` складывает только два поддерева, а промежуточный элемент никуда не попадает

2023-10-26 17:31 UTC, jmkostina commented on hw03/src/MyLib.hs
> +instance Ord ChurchNumber where
Добавила в обновленном файле

2023-10-26 17:32 UTC, jmkostina commented on hw03/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
`{-# LANGUAGE FlexibleInstances #-}` - это чтобы можно было определять классы с произвольными вложенными типами
`{-# LANGUAGE InstanceSigs #-}` - это чтобы можно было присваивать сигнатуры типов методам класса в объявлении инстансов (как мы на паре делали с Eq и как Вы попросили в 1м задании сделать)

2023-10-26 17:32 UTC, jmkostina commented
я с 3м заданием еще сильнее запуталась, когда разбираться начала

2023-10-26 19:44 UTC, pluralia commented on hw03/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
> определять классы с произвольными вложенными типами

Что это значит?

2023-10-26 19:46 UTC, pluralia commented on hw03/src/MyLib.hs
> +a b . c -> (.) (a b) (.) c - это по строчке выше
Молодец!

2023-10-26 19:49 UTC, pluralia commented
В чем именно ты запуталась? Напиши здесь в комментарии шаги, которые нужно сделать для конверсии

2023-10-26 22:04 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- честно пользовалась гуглом, до конца так и не разобралась, как это работает именно в инстансах haskell
Разберем на практике

2023-10-26 22:06 UTC, pluralia commented on hw03/src/MyLib.hs
> +-- я взяла формулы из https://www.101computing.net/cmyk-to-rgb-conversion-algorithm/
Можешь пингануть меня в тг, если будет время/желание разобраться

2023-10-26 22:22 UTC, pluralia commented
-0,5 -- за ворнинги
-0,25 -- нет Ix для 1
-0,25 -- мало тестов для 2a
-1 -- неверная конверсия для 3a/b, нет тестов
-0,25 -- нет 3с
-0,25 -- нет тестов для 6a/b
-1 -- нет 6с
-0,5 -- нет 7
-0,25 -- нет 8

Итог: 5,75

2023-10-26 22:22 UTC, closed without merging