hw1 Shchukin
pluralia/fp-fall-2023 pull request #2
Opened 2023-10-02 10:16 UTC by paiksonn

2023-10-02 12:26 UTC, pluralia commented on hw1.hs
> +chPow :: ChurchNumber -> ChurchNumber -> ChurchNumber
Верный ли ответ при возведении в 0?

2023-10-02 12:28 UTC, pluralia commented on hw1.hs
> +-- я не совсем понял, нужно задавать дерево с вводом с клавиатуры или просто рандомное дерево
Сделано как и задумывалось 👍

2023-10-02 12:47 UTC, paiksonn commented on hw1.hs
> +(/\||/\*) :: Bool -> Bool -> Bool
По идее, как я понял, для пользовательских операторов, когда это не объявлено явно, то приоритет и ассоциативность по умолчанию не определены. 
А чтобы вручную их определить, то нужно вначале прописать что-то типа:
infixl 9 /\||/\*
(/\||/\*) :: Bool -> Bool -> Bool
Т.е. тут я назначил оператору наивысший приоритет (он идет от 0 до 9) и левоассоциативность

2023-10-02 13:01 UTC, paiksonn commented on hw1.hs
> +-- видимо из-за выхода за пределы мощности вычислений. Но т.к. вычисления происходят сразу, то и результат
Чтобы доказать, что это правда работает, вот, что вышло для 1500:
ghci> fibTail 1500
13551125668563101951636936867148408377786010712418497242133543153221487310873528750612259354035717265300373778814347320257699257082356550045349914102924249595997483982228699287527241931811325095099642447621242200209254439920196960465321438498305345893378932585393381539093549479296194800838145996187122583354898000

2023-10-02 13:04 UTC, paiksonn commented on hw1.hs
> +myLength :: [a] -> Int
оно написано напрямую, не в хвостовом виде, поэтому на больших значениях она 100% словить переполнение стека вызовов или просто работать миллион лет будет 
Запустил, действительно словил стек оверфлоу

2023-10-02 13:41 UTC, paiksonn commented on hw1.hs
> +  where fromJust (Just x) = x
Спасибо!
Постараюсь учесть, просто тут всего одна строка после where, проще читается (ИМХО) в одну строку

2023-10-02 13:55 UTC, paiksonn commented on hw1.hs
> +myReverse :: [a] -> [a]
Ровно также, как и с предыдущими функциями - переполнение стека. 
Переписал функцию по новому, код сейчас апдейтну

2023-10-02 14:40 UTC, paiksonn commented on hw1.hs
> +-- main :: IO ()
Да, кажется, там ничего сложного 
main :: IO ()
main = putStrLn "Hello, World!"

2023-10-02 14:49 UTC, paiksonn commented on hw1.hs
> +-- import Test.HUnit  -- это фрейворк для тестирования в Хаскеле (спасибо гугл)
Почему-то они не запускались из одного файла с этим кодом.
Только когда я тесты вынес в отдельный Tests.hs файл и подключил его через 
module Tests where все заработало 
Это я чего-то не понимаю или это фишка хаскеля, что он как бы с помощью импортированных тестов не может их запускать в одном файле с исполняемым кодом?

2023-10-02 15:02 UTC, paiksonn commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
Хочется сказать, что да, я не вижу очевидных подводных камней, но раз есть вопрос, значит там что-то есть))

2023-10-02 15:05 UTC, paiksonn commented on hw1.hs
> +chAdd (Succ m) n = chAdd m (chSucc n)
а как было бы нестранно?

2023-10-02 16:42 UTC, paiksonn commented on hw1.hs
> +chPow :: ChurchNumber -> ChurchNumber -> ChurchNumber
нет, как раз таки потому что я забыл про паттерн-матчинг и поставил более редкое условие ниже более частого и поэтому в него бы программа просто не зашла, так что поменял их местами

2023-10-03 15:01 UTC, pluralia commented on hw1.hs
> +(/\||/\*) :: Bool -> Bool -> Bool
> приоритет и ассоциативность по умолчанию не определены.

Не верно. Ответ [здесь](https://www.haskell.org/onlinereport/decls.html)

2023-10-03 15:04 UTC, pluralia commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
Будет ли эта функция работать быстрее, eсли переписать ее с хвостовой рекурсией?

2023-10-03 15:04 UTC, pluralia commented on hw1.hs
> +chAdd (Succ m) n = chAdd m (chSucc n)
Субъективщина) Я бы поставила `Zero` в первое уравнение, а `Succ` -- после

2023-10-03 15:07 UTC, pluralia commented on hw1.hs
> +  where fromJust (Just x) = x
Про форматирование будем говорить на следующей лекции :)

2023-10-03 15:23 UTC, pluralia commented on hw1.hs
> +    myInitTailHelper [] acc = acc
Не забывай указывать типы фукнций

2023-10-03 15:23 UTC, pluralia commented on hw1.hs
> +myInitTail :: [a] -> Maybe Int
Что делает эта функция?

2023-10-03 15:23 UTC, pluralia commented on hw1.hs
> +myReverseTail :: [a] -> Maybe Int
Отлично!

2023-10-03 15:23 UTC, pluralia commented on hw1.hs
> +myLengthTail :: [a] -> Integer
Возвращает неверный результат

2023-10-03 15:42 UTC, pluralia commented on hw1.hs
> +myLengthTail :: [a] -> Integer
Моя ошибка -- все верно

2023-10-03 15:47 UTC, pluralia commented on hw1.hs
> +myReverseTail :: [a] -> Maybe Int
Типы не должны были сойтись

2023-10-03 15:54 UTC, pluralia commented on hw1.hs
> +-- import Test.HUnit  -- это фрейворк для тестирования в Хаскеле (спасибо гугл)
> Это я чего-то не понимаю или это фишка хаскеля, что он как бы с помощью импортированных тестов не может их запускать в одном файле с исполняемым кодом?

Честно говоря, нет ответа на этот вопрос: всегда писала тесты с использованием фреймворков в отдельном файле

2023-10-03 15:57 UTC, pluralia commented on hw1.hs
> +-- main :: IO ()
Типы не должны были сойтись. Можно подробнее, как ты запускал эти тесты? Это не требуется для зачета домашки, но, если хочешь поразбираться, можешь запушить то, что и как запускал.

2023-10-03 16:14 UTC, paiksonn commented on hw1.hs
> +(/\||/\*) :: Bool -> Bool -> Bool
"Any operator lacking a fixity declaration is assumed to be infixl 9"
Т.е. по умолчанию у оператора приоритет 9 и левоассоциативность

2023-10-03 16:25 UTC, paiksonn commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
Да, безусловно будет
Заапдейтил код с хвостовой реализацией

2023-10-03 16:36 UTC, paiksonn commented on hw1.hs
> +myInitTail :: [a] -> Maybe Int
Переворачивает список задом наперед, просто я там корявый копипаст сделал, должно было быть так:
myInitTail :: [a] -> Maybe [a]

2023-10-03 16:37 UTC, paiksonn commented on hw1.hs
> +myReverseTail :: [a] -> Maybe Int
Да, ответил выше, там корявый копипаст был и не тот тип получился, поправил

2023-10-03 19:00 UTC, pluralia requested changes

2023-10-03 19:00 UTC, pluralia commented on hw1.hs
> +mapMaybeTail :: (a -> b) -> Maybe a -> Maybe b
Был ли смысл переписывать `mapMaybe` с хвостовой рекурсией?

2023-10-03 19:00 UTC, pluralia commented on hw1.hs
> +    mapMaybeHelper :: (a -> b) -> Maybe a -> Maybe b -> Maybe b
Типы не сходятся

2023-10-03 19:00 UTC, pluralia commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
С хвостовой рекурсией нужно было делать `mapList`.
`mapMaybe` тут почти подходит, потому что `Maybe` по своей сути эквивалентно списку пустому и с одним элементом.

2023-10-03 19:00 UTC, pluralia commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Работает ли эта функция?

2023-10-03 19:08 UTC, paiksonn commented on hw1.hs
> +mapMaybeTail :: (a -> b) -> Maybe a -> Maybe b
нет, там ведь в целом нет рекурсии.
Просто я не понял, видимо, что хотели от меня переделку mapList, а не mapMaybe

2023-10-03 19:25 UTC, paiksonn commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
нет, убрал ее

2023-10-03 19:30 UTC, pluralia commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Перепиши `myInitTail` c `mapMaybe` без хвостовой рекурсии и зачту домашку

2023-10-03 20:28 UTC, paiksonn commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Честно говоря, я не понимаю, как это сделать.
Можно, пожалуйста, подсказку?

2023-10-03 20:33 UTC, paiksonn commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Видимо, два случая крайних остаются и переделать нужно только последнюю строку, т.е.
`myInit [] = Nothing
myInit [_] = Just []` - они остаются 

А вот строки `myInit (x:xs) = Just (x : fromJust (myInit xs)) 
  where fromJust (Just x) = x` должны измениться

2023-10-04 09:10 UTC, pluralia commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
@paiksonn, у тебя написано
```haskell
myInit :: [a] -> Maybe [a]
myInit []        = Nothing
myInit [x]      = Just []
myInit (x:xs) = Just (x : fromJust (myInit xs))
  where
    fromJust (Just x) = x
```

Давай напишем тип `fromJust :: Maybe x -> x`
Теперь давай вспомним тип `mapMaybe :: (x -> y) -> Maybe x -> Maybe y`

Теперь подумаем, что хочется сделать в последнем уравнении `myInit`:
1) мы хотим взять результат рекурсивного вызова `myInit xs`, который имеет тип `Maybe [a]`: `myInit xs :: Maybe [a]`
2) прибавить к нему элемент `x`, имеющий тип `a`: `x :: a`
3) и вернуть результат с типом `Maybe [a]`

Как это сделать? Выведи тип `mapMaybe` -- что соответствует типам `x` и что `y`
1) Мы хотим вернуть `Maybe [a]` в п.3. Значит, `y == [a]` => `mapMaybe :: (x -> [a]) -> Maybe x -> Maybe [a]`
2) Что соответствует `x`?

Теперь у тебя есть полный тип `mapMaybe`, как его нужно использовать для решения твоей задачи. Помогает ли тебе это понять, что отправить в качестве аргументов в `mapMaybe`?

2023-10-04 10:51 UTC, paiksonn commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Кажется, тут можно сделать вот так:

`
myInit :: [a] -> Maybe [a]
myInit [] = Nothing
myInit xs = mapMaybe myInitHelper (Just xs)
  where
    myInitHelper:: [b] -> [b]
    myInitHelper [_] = []
    myInitHelper (x:xs) = x : myInitHelper xs
`

Проверил тестами, все работает корректно

2023-10-04 11:12 UTC, pluralia commented on hw1.hs
> +myInitTail :: [a] -> Maybe [a]
Хорошо, зачту домашку. Hо реализация совсем тяжело читается. Вернемся к этому на практике в пятницу.

2023-10-04 11:13 UTC, pluralia commented
👍

2023-10-04 11:13 UTC, closed without merging