HW4,Manasyan_AL
pluralia/fp-fall-2023 pull request #20
Opened 2023-10-22 11:36 UTC by Artem9999999999999999999999

2023-10-29 11:28 UTC, pluralia requested changes
+0,1 за понравившиеся реализации

Ты уже знаешь монады / аппликативы -- изучал Haskell раньше?

2023-10-29 11:28 UTC, pluralia commented on hw4/src/MyLib.hs
> +data AminoAcid = Ala   -- Аланин
Подписи в комментах -- 👍

2023-10-29 11:28 UTC, pluralia commented on hw4/src/MyLib.hs
> +  | otherwise = T.chunksOf 3 str >>= (\codon -> case M.lookup codon codonTable of
Монады тоже знаешь?

2023-10-29 11:28 UTC, pluralia commented on hw4/test/TestSpec.hs
> +      it "fromListL tests" $ do
Списки с повторяющимися ключами?

2023-10-29 11:28 UTC, pluralia commented on hw4/test/TestSpec.hs
> +      it "fromListR tests" $ do
Списки с повторяющимися ключами?

2023-10-30 11:14 UTC, Artem9999999999999999999999 commented
Читаю книжку по Haskell и обсуждения конструкторов на stackoverflow. Стараюсь использовать в домашках какие-то новые и интересные конструкторы, если они уместны.
Сделал коммит, в нем все исправления и ответы на Ваши вопросы.

2023-10-30 11:43 UTC, pluralia commented on hw4/src/MyLib.hs
> +gcContent = (/) <$> fromIntegral . T.length . T.filter (\c -> c == 'G' || c == 'C') <*> fromIntegral . T.length
Ok, +0,15

2023-10-30 12:57 UTC, pluralia commented
+0,25 суммарно
Очень классно, что смотришь материал вокруг!

2023-10-30 15:06 UTC, Artem9999999999999999999999 commented
У меня PR еще открыт, что-то еще нужно посмотреть?

2023-10-30 15:20 UTC, pluralia commented
@Artem9999999999999999999999, да, нужно кое-что доделать: у меня ревью не закоммитилось :(

2023-10-30 15:21 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- затем результаты 2 и 3 частей делятся друг на друга с помощью оператора (/)
+0,15 я тебе поставила, но необходимо, чтобы ты понял, почему это именно это все работает

2023-10-30 19:37 UTC, pluralia commented
[Странный коммит](https://github.com/pluralia/fp-fall-2023/pull/20/commits/00754049330357b0111b067b029d5acd05b7901a) -- перезатирает тесты

Не ответил про монады и аппликативы -- без этого полный балл за домашку не поставлю. Использовал, что не проходили -- умничка, но должен понимать, как оно работает

2023-10-30 19:45 UTC, Artem9999999999999999999999 commented
Почему-то файл MyLib.hs не подтянулся. Сейчас поправил, должно быть видно изменения

2023-10-30 21:37 UTC, pluralia commented on hw4/src/MyLib.hs
> +average vec | V.length vec > 0 = V.foldl' (+) 0 vec / fromIntegral (V.length vec)
1. ок
2. на что можно заменить `divide (sum', len)`? почему здесь не получается использовать `/` сразу? что нужно сделать, чтобы можно было использовать `/` здесь?

2023-10-30 21:40 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- В нашем случае, f - это функция (a -> b), a - это T.Text, и b - это Double.
`f` -- это `(-> T.Text)`

2023-10-30 21:42 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- затем результаты 2 и 3 частей делятся друг на друга с помощью оператора (/)
Здесь не буду больше мучить, а просто покажу на паре, что ожидала, потому что как раз будем `Applicative` проходить. Ты не против, если использую твое решение для демонстрации применения аппликативов на паре (без указания авторства)?

Если хочешь, можешь еще типы поковырять -- подсказку про `f` я оставила.

2023-10-30 21:45 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- и создания временных структур данных, так как не требует создания множества
`concatMap` тут будет работать также долго. Почему бы не использовать просто `map`?

2023-10-30 21:45 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- В нашем случае, f - это функция (a -> b), a - это T.Text, и b - это Double.
Здесь не буду больше мучить, а просто покажу на паре, что ожидала, потому что как раз будем Applicative проходить. Ты не против, если использую твое решение для демонстрации применения аппликативов на паре (без указания авторства)?

Если хочешь, можешь еще типы поковырять -- подсказку про `f` я оставила.

2023-10-31 06:28 UTC, Artem9999999999999999999999 commented on hw4/src/MyLib.hs
> +-- В нашем случае, f - это функция (a -> b), a - это T.Text, и b - это Double.
Да, конечно.
Будет интересно послушать про этот пример.

2023-10-31 06:31 UTC, Artem9999999999999999999999 commented
Поправил

2023-10-31 09:19 UTC, pluralia commented on hw4/src/MyLib.hs
> +-- тут hlint попросил заменить case на fromMaybe Stop
Хорошая замена: `fromMaybe Stop` здесь пытается достать из Maybe и, если приходит Nothing, возвращает `Stop`

2023-10-31 09:20 UTC, pluralia commented on hw4/src/MyLib.hs
> +average vec | V.length vec > 0 = V.foldl' (+) 0 vec / fromIntegral (V.length vec)
Ответ на 2:
|
|
|
`divide (sum', len)`  можно заменить на `uncurry (/)`

2023-10-31 09:20 UTC, pluralia commented
👍

2023-10-31 09:20 UTC, closed without merging