HW4 Kostina
pluralia/fp-fall-2023 pull request #22
Opened 2023-10-24 16:45 UTC by jmkostina

2023-10-29 10:47 UTC, pluralia reviewed
-0,5 -- нет половины 9
-1,25 -- нет 11

2023-10-29 10:47 UTC, pluralia commented on src/MyLib.hs
> +average vec = V.foldl' (+) 0 vec / fromIntegral (V.length vec)
Как эта функция отработает на пустом списке?

2023-10-29 10:47 UTC, pluralia commented on src/MyLib.hs
> +gcContent str = fromIntegral gcTotal / fromIntegral (T.length str)
Как отработает на пустой строке?

2023-10-29 10:47 UTC, pluralia commented on src/MyLib.hs
> +identity str1 str2 | T.length str1 == T.length str2 = 1 - fromIntegral (hamming str1 str2) / fromIntegral (T.length str1)
А если обе строки пустые?

2023-10-29 11:32 UTC, pluralia requested changes

2023-10-29 11:32 UTC, pluralia commented on src/MyLib.hs
> +    --toSymbol Pyl = 'O'
Почему закомментированы?

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +    --toSymbol Pyl = 'O'
Там в табличке из вики написанно, что эти две аминокислоты имеют такие же трехбуквенные коды, как и стоп-кодон. То есть если я никак не прописываю зависимости их появления (что например TGA это не терминация, а Pyl = 'O') то их можно и не добавлять, так как я все равно буду их последовательности считать терминацией

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
чтобы при обновлении пары ключ-значение, попадали только первые вхождения уникальных элементов

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +--я не поняла, как с левой сверткой делать
там просто `flip` нужно добавить
```haskell
fromListL :: Ord k => [(k, v)] -> M.Map k v
fromListL = foldl' (flip(uncurry M.insert)) M.empty
```

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +-- чем будет отличаться поведение этих вариантов.
ну по логике разница в том, какое значение при перезаписи (если значения ключа повторяются)  будет оставаться - правая или левая (т.к. правая и левая свертки смотрят с разных концов)

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +identity str1 str2 | T.length str1 == T.length str2 = 1 - fromIntegral (hamming str1 str2) / fromIntegral (T.length str1)
нужно проверять на ненулевую длину
```haskell
identity :: T.Text -> T.Text -> Double
identity str1 str2 | T.length str1 == T.length str2 && T.length str1 > 0 = 1 - fromIntegral (hamming str1 str2) / fromIntegral (T.length str1)
                   | otherwise = error "Different length"
```

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +reverseNucl :: M.Map Char Char
а в чем выгода для нас во внутренних функциях?
```haskell
isReversePalindrom :: T.Text -> Bool
isReversePalindrom str = str == T.reverse (T.map (reverseNucl M.!) str)
    where
      reverseNucl :: M.Map Char Char
      reverseNucl = M.fromList [('A', 'T'), ('T', 'A'), ('C', 'G'), ('G', 'C')]
```

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +          where
см. предыдущий коммент

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +gcContent str = fromIntegral gcTotal / fromIntegral (T.length str)
аналогично предыдущему - нужно проверить на ненулевую длину
нужно (с учетом следующего комментария)
```haskell
gcContent :: T.Text -> Double
gcContent str | T.length str > 0 = fromIntegral gcTotal / fromIntegral (T.length str)
              | otherwise = error "Nothing to count - empty string"
    where
      gcIsland x = nuclCheck 'G' x + nuclCheck 'C' x
      gcTotal = T.foldl'(\c x -> c + gcIsland x) 0 str
```

2023-11-01 07:37 UTC, jmkostina commented on src/MyLib.hs
> +average vec = V.foldl' (+) 0 vec / fromIntegral (V.length vec)
будет `NaN`, т.к. на 0 (размер пустого списка) делить не получится. Нужно проверить на непустоту
```haskell

average :: V.Vector Double -> Double
average vec | V.length vec > 0 = V.foldl' (+) 0 vec / fromIntegral (V.length vec)
            | otherwise = error "Nothing to count - empty list"
```

2023-11-01 07:39 UTC, jmkostina commented on src/MyLib.hs
> +-- здесь при сборке cabal пишет, что импорт foldl', foldr из Data.Foldable избыточен, но я тогда не поняла, откуда мы его берем
удалила только `foldr`, потому что без импорта `foldl'` не собирается задание 9

2023-11-01 22:43 UTC, pluralia commented on src/MyLib.hs
> +reverseNucl :: M.Map Char Char
1. Читаемость -- ты сразу понимаешь, зачем нужна эта функция. А точнее, что она больше нигде не нужна
2. Локальные функции имеют доступ к аргументам основной функции -- их можно не передавать

2023-11-01 22:45 UTC, pluralia commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
Разве у нас здесь есть пары ключ-значение?

2023-11-02 12:31 UTC, jmkostina commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
это я на 9 задание посмотрела, простите.
здесь я честно не знаю, но у меня с `foldl'` были ошибки (там компилятор писал, что я не тот тип передаю), а с `foldr` получилось вывести как и в 9
если честно, я не понимаю, почему нельзя просто заменять одну свертку на другую в функции - то есть почему они требуют разного синтаксиса. для меня это вообще не логично

2023-11-02 12:31 UTC, jmkostina commented on src/MyLib.hs
> +reverseNucl :: M.Map Char Char
поняла

2023-11-02 13:12 UTC, pluralia commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
Как нужно поменять код, чтобы здесь работала `foldl'`?

> то есть почему они требуют разного синтаксиса. для меня это вообще не логично
Понимаю, и, честно говоря, сама постоянно забываю, какой свертке в каком порядке передавать аргументы :(

Однако, логика тут есть и она обусловлена семантикой этих функций: какой операнд (элемент списка и аккумулятор) будет левым, а какой правым при применении операции свертки. Если у тебя операция свертки -- какой-нибудь +, который ассоциативен и коммутативен, то прикол со сменой типов аргументов для foldl/r тебе только мешает. Для более сложной операции смена порядка аргументов заставит тебя лишний раз задуматься, в каком порядке происходит сверка, а это важно для понимания, какой результат ты получить

2023-11-02 13:13 UTC, pluralia commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
Как заменить `foldr` на `foldl'`? Есть ли в Haskell функция, которая меняет порядок аргументов?

2023-11-02 13:14 UTC, pluralia commented on src/MyLib.hs
> +nubOrd = toList . foldr S.insert S.empty
Вижу, что в другом месте ее использовала. Приму домашку

2023-11-02 13:14 UTC, pluralia commented
👍

2023-11-02 13:14 UTC, closed without merging