Hw04_Pushkina_Olga
pluralia/fp-fall-2023 pull request #23
Opened 2023-10-26 10:19 UTC by forestcream

hlint и ворнингов у меня нет

2023-10-29 11:33 UTC, pluralia requested changes
+0,25 за понравившиеся реализации

2023-10-29 11:33 UTC, pluralia commented on hw4/src/MyLib.hs
> +        go xs = case M.lookup (T.pack (take 3 xs)) codonTable of
Используй T.chunksOf

2023-10-29 11:33 UTC, pluralia commented on hw4/src/MyLib.hs
> +type Codon = T.Text
Молодец, что использовала alias

2023-10-29 11:33 UTC, pluralia commented on hw4/src/MyLib.hs
> +  [ (T.pack "GCT", Ala), (T.pack "GCC", Ala), (T.pack "GCA", Ala), (T.pack "GCG", Ala)
T.pack можно было накинуть при помощи map, а можно вообще убрать -- он разберется, что ты имеешь ввиду тут Text, а не String

2023-10-31 15:36 UTC, forestcream commented on hw4/src/MyLib.hs
> +        let sumAndCount = V.foldl' step (0, 0) vec
```
average :: V.Vector Double -> Double
average vec
    | V.null vec = 0.0
    |otherwise = 
        let sumAndCount = V.foldl' (\(s, l) x -> (s + x, l + (1 :: Int))) (0, 0) vec
            (sum', len) = fmap fromIntegral sumAndCount
        in sum' / len
```

2023-10-31 18:47 UTC, forestcream commented on hw4/src/MyLib.hs
> +            | Set.member element set = (set, list)
у меня если я убираю проверку вот так, все перестает работать
```
nubOrd :: Ord a => [a] -> [a]
nubOrd = reverse . snd . foldl processElement (Set.empty, [])
    where
        processElement :: Ord a => (Set.Set a, [a]) -> a -> (Set.Set a, [a])
        processElement (set, list) element = (Set.insert element set, element:list)
```

2023-10-31 18:57 UTC, forestcream commented on hw4/src/MyLib.hs
> +buildQuery parameters = T.drop 1 $ M.foldlWithKey' appendKeyValue (T.pack "") parameters
```
buildQuery :: M.Map T.Text T.Text -> T.Text
buildQuery parameters = T.intercalate (T.pack "&") $ map appendKeyValue $ M.toList parameters
    where
        appendKeyValue (k, v) = k `T.append` T.pack "=" `T.append` v
```

2023-10-31 19:00 UTC, forestcream commented on hw4/src/MyLib.hs
> +        complement :: Char -> Char
```
isReversePalindrom :: T.Text -> Bool
isReversePalindrom dna = T.reverse (T.map complement dna) == dna
    where
        complementMap = M.fromList [('A', 'T'), ('T', 'A'), ('G', 'C'), ('C', 'G')]
        complement c = M.findWithDefault (error "Incorrect input") c complementMap
```

2023-10-31 19:00 UTC, forestcream commented on hw4/src/MyLib.hs
> +        temp 'G' = 4
```
meltingTemp :: T.Text -> Int
meltingTemp = T.foldl' (\ acc c -> acc + temp c) 0
    where
        tempMap = M.fromList [('G', 4), ('C', 4), ('A', 2), ('T', 2)]
        temp c = M.findWithDefault 0 c tempMap
```

2023-10-31 19:17 UTC, forestcream commented on hw4/src/MyLib.hs
> +            (sum', len) = fmap fromIntegral sumAndCount
```
average :: V.Vector Double -> Double
average vec
    | V.null vec = 0.0
    | otherwise =  uncurry (/) (fromIntegral <$> V.foldl' (\ (s, l) x -> (s + x, l + (1 :: Int))) (0, 0) vec)
```

2023-10-31 19:20 UTC, forestcream commented on hw4/src/MyLib.hs
> +identity str1 str2
```
identity :: T.Text -> T.Text -> Double
identity str1 str2
    | T.length str1 /= T.length str2 = -1.0 -- вместо ошибки возращаем -1 так как в типы указан был только Double
    | T.length str1 == 0 && T.length str2 == 0 = 1.0
    | otherwise                      = 1 - hamming / len
    where
        len = fromIntegral $ T.length str1
        hamming = fromIntegral $ length $ filter not $ zipWith (==) (T.unpack str1) (T.unpack str2)
```
вернем 1, так как строки совпадают. или можно, наверное, тоже ошибку возращать

2023-10-31 19:27 UTC, forestcream commented on hw4/src/MyLib.hs
> +  [ (T.pack "GCT", Ala), (T.pack "GCC", Ala), (T.pack "GCA", Ala), (T.pack "GCG", Ala)
Про Map не подумала, и правда удобнее будет. Если T.pack не добавлять компилятор ругался

2023-10-31 22:41 UTC, pluralia commented on hw4/src/MyLib.hs
> +            | c == 'A' || c == 'T' = (gc, count' + 1)
Здесь 3 условия
```
| c == 'G' || c == 'C' = (gc + 1, count' + 1)
| c == 'A' || c == 'T' = (gc, count' + 1)
| otherwise = (gc, count')
``` 
Ты знаешь, что в строке есть только GCAT, поэтому count' в любом случае будет увеличиваться на 1, и одно условие можно упростить

2023-10-31 22:42 UTC, pluralia commented on hw4/src/MyLib.hs
> +        uniqueElements = snd . foldl processElement (Set.empty, [])
Не `foldl'`?

2023-10-31 22:58 UTC, pluralia commented on hw4/src/MyLib.hs
> +            | Set.member element set = (set, list)
Ты используешь Set, чтобы решить, добавлять ли элемент в новый лист, но тебе не нужен этот лист -- ты можешь сконвертить Set в лист

2023-11-01 16:08 UTC, forestcream commented on hw4/src/MyLib.hs
> +        go xs = case M.lookup (T.pack (take 3 xs)) codonTable of
```
translate :: T.Text -> Either String [AminoAcid]
translate dna
    |T.length dna `mod` 3 /= 0 = Left "Input is not correct"
    | otherwise = Right $ mapMaybe (`M.lookup` codonTable) (T.chunksOf 3 dna)
```

2023-11-01 16:10 UTC, forestcream commented on hw4/src/MyLib.hs
> +            | c == 'A' || c == 'T' = (gc, count' + 1)
а, ну тогда просто убираем проверку на другие символы
```
gcContent :: T.Text -> Double
gcContent str = 
    let (gcCount, totalCount) = T.foldl' step (0, 0) str
        step :: (Int, Int) -> Char -> (Int, Int)
        step (gc, count') c 
            | c == 'G' || c == 'C' = (gc + 1, count' + 1)
            | otherwise            = (gc, count' + 1)
    in fromIntegral gcCount / fromIntegral totalCount
```

2023-11-01 22:42 UTC, pluralia commented
`nubOrd` осталось поправить

2023-11-02 11:52 UTC, forestcream commented on hw4/src/MyLib.hs
> +        uniqueElements = snd . foldl processElement (Set.empty, [])
лучше foldl', чтобы стек не переполнился. Все время забываю про это
```
nubOrd :: Ord a => [a] -> [a]
nubOrd = reverse . snd . foldl' processElement (Set.empty, [])
    where
        processElement :: Ord a => (Set.Set a, [a]) -> a -> (Set.Set a, [a])
        processElement (set, list) element
            | Set.member element set = (set, list)
```

2023-11-02 12:46 UTC, pluralia commented
Коммент по `nubOrd` [здесь](https://github.com/pluralia/fp-fall-2023/pull/23#discussion_r1378237588)

В своем решении ты используешь Set, чтобы решить, добавлять ли элемент в новый лист, но тебе не нужен этот новый лист. Ты можешь сверкой пройтись по входному списку и добавить его элементы в Set -- так у тебя будет Set с уникальными элементами. Затем одной командой ты можешь сконвертировать его в лист

2023-11-02 19:33 UTC, forestcream commented on hw4/src/MyLib.hs
> +            | Set.member element set = (set, list)
Извини, проглядела. Вот с конвертом Set в лист
```
nubOrd :: Ord a => [a] -> [a]
nubOrd = Set.toList . foldl' processElement Set.empty
    where
        processElement :: Ord a => Set.Set a -> a -> Set.Set a
        processElement set element
            | Set.member element set = set
            | otherwise              = Set.insert element set
```

2023-11-02 20:57 UTC, pluralia commented
👍

2023-11-02 20:57 UTC, closed without merging