HW4_Shishkina
pluralia/fp-fall-2023 pull request #24
Opened 2023-10-26 13:43 UTC by SophiaLaz

2023-10-29 11:35 UTC, pluralia requested changes
Все хорошо, не хватает тестов на пустые списки/строки

2023-10-29 11:35 UTC, pluralia commented on src/MyLib.hs
> +aminoToStr = foldl' (\ acc x -> acc <> (T.singleton . transformation) x) T.empty
Почему foldl'? На что лучше заменить?

2023-10-29 11:35 UTC, pluralia commented on test/TestSpec.hs
> +    describe "9 - M.fromList" $ do
Не хватает тестов на списки с одинаковыми ключами

2023-10-29 12:27 UTC, pluralia commented on src/MyLib.hs
> +-- значит суммарно асимптотика будет O(n * log(n)).
Верно. За O(n) здесь и не выйдет

2023-10-31 14:38 UTC, SophiaLaz commented on src/MyLib.hs
> +average xs = foldl' (+) 0 xs / fromIntegral (V.length xs)
Будет деление на ноль (длина вектора), значит результат бесконечность (NaN)... Поправила ошибку.

2023-10-31 14:42 UTC, SophiaLaz commented on src/MyLib.hs
> +gcContent str =
Аналогично предыдущему - деление на ноль, результат NaN. Поправила.

2023-10-31 18:40 UTC, SophiaLaz commented on src/MyLib.hs
> +evenodd xs = (subArray False (zip [(0 :: Int)..] xs), subArray True (zip [(0 :: Int)..] xs))
переписала через фильтр

2023-10-31 21:20 UTC, pluralia commented
👍

2023-10-31 21:20 UTC, closed without merging