HW4_DmitrievOS
pluralia/fp-fall-2023 pull request #25
Opened 2023-10-29 01:29 UTC by qilowoq

2023-10-29 11:24 UTC, pluralia requested changes
+0,25 за понравившиеся реализации

Добавь, пожалуйста, тесты на пустые списки и списки/строки разной длины

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    evenodd "HDAOTTEA"  `shouldBe` (("HATE", "DOTA") :: ([Char], [Char]))
🤔

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +  it "gcContent" $ do
Строки разной длины?

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +  it "meltingTemp" $ do
Строки разной длины?

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +  it "identity" $ do
Строки разной длины?

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +  it "fromListL" $ do
Списки разной длины?

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +  it "fromListR" $ do
Списки разной длины?

2023-10-29 11:24 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Почему закомментировал?

2023-10-31 19:21 UTC, qilowoq commented on hw4/src/MyLib.hs
> +average = uncurry (/) . foldl' helper (0, 0)
Получится NaN тк 0/0

2023-10-31 19:30 UTC, qilowoq commented on hw4/src/MyLib.hs
> +gcContent = uncurry (/) . T.foldl' helper (0, 0)
Деление 0/0. NaN.  стоит ли менять?

2023-10-31 19:30 UTC, qilowoq commented on hw4/src/MyLib.hs
> +identity str1 str2 = if T.length str1 /= T.length str2
NaN

2023-10-31 19:54 UTC, qilowoq commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Там дичь. опять. Там должен быть `Invalid codon`.  Вот так:

```
ghci> translate (T.pack "AUGGCTGCCGCAGCG")
[*** Exception: Invalid codon
CallStack (from HasCallStack):
  error, called at src/MyLib.hs:295:42 in main:MyLib
```

Но тест (тот что закоменчен) падает.

2023-10-31 22:34 UTC, pluralia commented on hw4/src/MyLib.hs
> +average = uncurry (/) . foldl' helper (0, 0)
На пустом списке нужно ошибку (обернуть в Maybe, Either) или дефолтное значение

2023-10-31 22:35 UTC, pluralia commented on hw4/src/MyLib.hs
> +average = uncurry (/) . foldl' helper (0, 0)
Сделай в одном месте -- остальное не надо

2023-10-31 22:38 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Попробуй `traceShow` поставить и посмотреть на вывод REPL и тестов. [Здесь](https://github.com/pluralia/fp-fall-2023/pull/15#discussion_r1375471073) подробнее

2023-11-01 01:48 UTC, qilowoq commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Я добавил trace везде где только можно. 

Вот такой лог

```
Running 1 test suites...
Test suite hw4-test: RUNNING...

Test
  test padZero [✔]
  test encode [✔]
  test evenodd [✔]
  average [✔]
  gcContent [✔]
  isReversePalindrom [✔]
  meltingTemp [✔]
  identity [✔]
  fromListL [✔]
  fromListR [✔]
  nubOrd [✔]
  buildQuery [✔]
  aminoToStr [✔]
-- ["GCT","GCC","GCA","GCG"]
"GCT"
"GCC"
"GCA"
"GCG"
-- Invalid length
-- ["AUG","GCT","GCC","GCA","GCG"]
  translate [✘]

Failures:

  test/TestSpec.hs:92:53: 
  1) Test translate
       did not get expected exception: ErrorCall

  To rerun use: --match "/Test/translate/" --seed 2124353344

Randomized with seed 2124353344

Finished in 0.0016 seconds
14 examples, 1 failure
```

Первый и второй тесты отрабатывают как надо, но вот третий правильно разбивает и все ... он дальше этот список как будто никуда не передает. Все это очень странно

2023-11-01 22:38 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Посмотрю на выходных

2023-11-01 22:38 UTC, pluralia commented
👍

2023-11-01 22:38 UTC, closed without merging

2023-11-07 11:21 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
@qilowoq, проблема в ленивости. Ошибка "Invalid codon" возникает внутри ленивого списка, a `evaluate` (которую используешь в тестах) форсит вычисление этого списка только до самого верхнего `:`, поэтому ошибка не кидается и тест валится.

Что делать:
1. Не кидать ошибки, а возвращать `Either` (собственно, то, с чем ты сейчас столкнулся, и есть одна из причин, почему не стоит кидать ошибки, а оборачивать их в `Either` или `Maybe`)
2. Форсировать вычисления и избавиться от ленивости. Это можно сделать так:
  - добавить зависимость `deepseq` в `.cabal`
  - добавить это в MyLib.hs
```haskell
{-# LANGUAGE DeriveGeneric, DeriveAnyClass #-}

import Control.DeepSeq (NFData())
import GHC.Generics (Generic)
```
  - импортировать `force` в TestSpec.hs
```haskell
import Control.DeepSeq (force)
```
  - вызвать тест
```haskell
evaluate (force (translate (T.pack "AUGGCTGCCGCAGCG"))) `shouldThrow` anyErrorCall
```

2023-12-11 17:45 UTC, pluralia commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
@qilowoq, можно использовать этот пример на следующей лекции для иллюстрации проблемы ленивой обработки ошибок?

2023-12-12 00:55 UTC, qilowoq commented on hw4/test/TestSpec.hs
> +    --evaluate (translate (T.pack "AUGGCTGCCGCAGCG")) `shouldThrow` anyErrorCall
Конечно