HW5_DmitrievOS
pluralia/fp-fall-2023 pull request #26
Opened 2023-11-02 02:37 UTC by qilowoq

2023-11-05 00:00 UTC, pluralia requested changes
-0,5 за ворнинги

2023-11-05 00:00 UTC, pluralia commented on hw5/src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавь, пожалуйста, 1-2 теста на создание деревьев Size и Priority с помощью leaf и branch

2023-11-08 05:32 UTC, qilowoq commented on hw5/src/MyLib.hs
> +      StudentsLog (n : names) (calcmin (Just g) worst) (max (Just g) best)
`min Nothing ( Just _ ) == Nothing`. У нас всегда поле worst будет `Nothing`

2023-11-08 05:34 UTC, qilowoq commented on hw5/src/MyLib.hs
> +calculateStudentsLog = foldr helper (StudentsLog [] Nothing Nothing)
Согласен `foldr` лучше заменить на `foldl'`. Все равно нужно проходить по всем елементам списка

2023-11-08 05:34 UTC, qilowoq commented on hw5/src/MyLib.hs
> +import           Data.Monoid()
Убрал

2023-11-08 05:51 UTC, qilowoq commented on hw5/src/MyLib.hs
> +    StudentsLog (names1 ++ names2) (calcmin worst1 worst2) (max best1 best2)
min Nothing ( Just _ ) == Nothing. У нас всегда поле worstGrade будет Nothing

2023-11-08 05:59 UTC, qilowoq commented on hw5/src/MyLib.hs
> +applesInRange tree (minim, maxim) = foldr helper True tree
`all`

2023-11-08 06:24 UTC, qilowoq commented on hw5/src/MyLib.hs
> +siftDown (BinNode v BinLeaf r) | v < val r = BinNode v BinLeaf r
Если я уберу случай которого не может быть, то `Pattern match(es) are non-exhaustive`

2023-11-08 07:57 UTC, qilowoq commented on hw5/src/MyLib.hs
> +    calcmin :: Maybe Int -> Maybe Int -> Maybe Int
Нет идей. Там с min и Nothing у меня проблемы

2023-11-08 12:51 UTC, pluralia commented on hw5/src/MyLib.hs
> +    calcmin :: Maybe Int -> Maybe Int -> Maybe Int
Полагаю, тебя беспокоит, что появление Nothing в качестве одного из операндов дает Nothing -- это ожидаемое поведение.

2023-11-08 12:52 UTC, pluralia commented on hw5/src/MyLib.hs
> +      StudentsLog (n : names) (calcmin (Just g) worst) (max (Just g) best)
> У нас всегда поле worstGrade будет Nothing

Что нужно поменять, чтобы нормально считалось?

2023-11-08 12:55 UTC, pluralia commented on hw5/src/MyLib.hs
> +    calcmin :: Maybe Int -> Maybe Int -> Maybe Int
Концептуально в этом задании получается 2 варианта обработки Nothing для grade:

1. Мы говорим, что, если хотя бы у одного студента нет grade, мы не можем посчитать результирующую best/worstGrade. Эта версия получится, если использовать min <$> worstGrade a <*> worstGrade b и поменять mempty / инициализацию аккумулятора
2. То, как у тебя было реализовано: мы игнорируем Nothing, и за счет этого можем посчитать результирующую best/worstGrade, если хотя бы у одного студента есть не Nothing в качестве grade

Как лучше делать? Оба варианта нормальные.
Зачем прошу расписать через <$> и <*>? Чтобы показать альтернативный и важность правильной инициализации аккумулятора

2023-11-08 12:55 UTC, pluralia commented on hw5/src/MyLib.hs
> +    StudentsLog (names1 ++ names2) (calcmin worst1 worst2) (max best1 best2)
Посмотри, как mempty задаешь

2023-11-08 12:58 UTC, pluralia commented on hw5/src/MyLib.hs
> +siftDown (BinNode v BinLeaf r) | v < val r = BinNode v BinLeaf r
Верно. Можешь кинуть ошибку или завернуть в Maybe. Но проблему кидания ошибок ты уже увидел (я ответила тебе в PR к 4 домашке, в чем была проблема с тастами -- загляни, если еще не увидел), поэтому рассчитываю, что выберешь Maybe ;)

2023-11-09 03:58 UTC, qilowoq commented on hw5/src/MyLib.hs
> +applesInRange tree (minim, maxim) = foldr helper True tree
all

2023-11-09 04:02 UTC, qilowoq commented on hw5/src/MyLib.hs
> +    calcmin :: Maybe Int -> Maybe Int -> Maybe Int
Я поменял, но не уверен, что получилось красиво

2023-11-09 04:30 UTC, qilowoq commented on hw5/src/MyLib.hs
> +siftDown (BinNode v BinLeaf r) | v < val r = BinNode v BinLeaf r
Я бы с радостью выбрал Maybe, но siftDown реккурсивная и там все равно где-то что-то идет не так. Я написал бы вот так

```haskell
siftDown :: Ord a => BinaryHeap a -> Maybe (BinaryHeap a)
siftDown BinLeaf = Just BinLeaf
siftDown (BinNode v BinLeaf BinLeaf) = Just $ BinNode v BinLeaf BinLeaf
siftDown (BinNode v l BinLeaf) | v < val l = Just $ BinNode v l BinLeaf
                               | otherwise = Just $ BinNode (val l) ((unpack . siftDown) (l {val = v})) BinLeaf
siftDown (BinNode _ BinLeaf _) = Nothing
siftDown (BinNode v l r)       | v < min (val l) (val r) = Just $ BinNode v l r
                               | v > val l = Just $ BinNode (val l) ((unpack . siftDown) (l {val = v})) r
                               | otherwise = Just $ BinNode (val r) l ((unpack . siftDown) (r {val = v}))

unpack:: Maybe (BinaryHeap a) -> BinaryHeap a
unpack (Just x) = 
```

Но оно выдает ошибку, на вот этом примере:

```hsakell
bHeap' = BinNode 3 (BinNode 2 BinLeaf (BinNode 1 BinLeaf BinLeaf) ) (BinNode 4 BinLeaf BinLeaf)
siftDown bHeap'
```
Потому что у там неправильное поддерево

2023-11-09 07:35 UTC, pluralia commented on hw5/src/MyLib.hs
> +    calcmin :: Maybe Int -> Maybe Int -> Maybe Int
В чем не красота?

2023-11-09 08:20 UTC, pluralia commented on hw5/src/MyLib.hs
> +siftDown (BinNode v BinLeaf r) | v < val r = BinNode v BinLeaf r
Тебе нужна [такая вот функция](https://hoogle.haskell.org/?hoogle=Maybe%20a%20-%3E%20(a%20-%3E%20Maybe%20b)%20-%3E%20Maybe%20b) -- это оператор `>>=`
```
siftDown :: Ord a => BinaryHeap a -> Maybe (BinaryHeap a)
siftDown BinLeaf = Just BinLeaf
siftDown (BinNode v BinLeaf BinLeaf) = Just $ BinNode v BinLeaf BinLeaf
siftDown (BinNode v l BinLeaf) | v < val l = Just $ BinNode v l BinLeaf
                               | otherwise = siftDown (l {val = v}) >>= (\x -> Just $ BinNode (val l) x BinLeaf)
                        
siftDown (BinNode _ BinLeaf _) = Nothing
siftDown (BinNode v l r)       | v < min (val l) (val r) = Just $ BinNode v l r
                               | v > val l = siftDown (l {val = v}) >>= (\x -> Just $ BinNode (val l) x r)
                               | otherwise = siftDown (r {val = v}) >>= (\x -> Just $ BinNode (val r) l x)
```

2023-11-09 08:21 UTC, pluralia commented
👍

2023-11-09 08:21 UTC, closed without merging