HW5_ShchukinIA
pluralia/fp-fall-2023 pull request #27
Opened 2023-11-02 11:30 UTC by paiksonn

That was quite tough homework

2023-11-05 00:00 UTC, pluralia requested changes
Убери, пожалуйста, флаги игнорирования ворнингов и исправь их

2023-11-05 00:00 UTC, pluralia commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавь, пожалуйста, 1-2 теста на создание деревьев Size и Priority с помощью leaf и branch

2023-11-05 05:36 UTC, paiksonn commented on hw5.cabal
> +                      -fno-warn-name-shadowing
Просто, по идее, ворнинги по типу шедоуинга ведь никак не влияют на выполнение кода, просто сообщают нам о том, что мы где-то там использовали одинаково названные перемененные, поэтому я их просто отключил, чтобы глаз не мозолили
Но хорошо, уберу флаги и поправлю все

2023-11-05 05:38 UTC, paiksonn commented on src/MyLib.hs
> +minMaybe :: Ord a => Maybe a -> Maybe a -> Maybe a
`minMaybe a b = min <$> a <*> b`

2023-11-05 05:39 UTC, paiksonn commented on src/MyLib.hs
> +maxMaybe :: Ord a => Maybe a -> Maybe a -> Maybe a
`minMaybe a b = max <$> a <*> b`

2023-11-05 05:42 UTC, paiksonn commented on src/MyLib.hs
> +  -- Тут компилятор ругается на неканоничное определение функции mappend, но это никак не мешает
Да, действительно, спасибо

2023-11-05 05:47 UTC, paiksonn commented on src/MyLib.hs
> +    (minWeight, maxWeight) = weightRange
Мне показалось, что это выглядит более громоздко и сложно, если делать этим путём, поэтому написал вот так

2023-11-05 05:53 UTC, paiksonn commented on src/MyLib.hs
> +    find (\apple -> isColorMatch apple && isWeightInRange apple) (foldMap (: []) tree)
Да, но мне так просто понятнее самому, когда я сначала все в список завернул и там дальше уже все что нужно сделал, поэтому так написал

2023-11-05 05:54 UTC, paiksonn commented on src/MyLib.hs
> +    lowerBound = fst weightRange
Да, но по той же причине, что в комментарии выше писал, я написал вот так - для меня это более понятный и читаемый вид

2023-11-05 05:57 UTC, paiksonn commented on src/MyLib.hs
> +collectBasket tree = foldr collectApple emptyBasket (flattenTree tree) -- foldr для сохранения порядка яблок как они встречаются
а, точно, нужно еще по весу внутри каждого цвета отсортировать, я забыл про эту задачу, сейчас доделаю

2023-11-05 06:19 UTC, paiksonn commented on src/MyLib.hs
> +collectBasket tree = foldr collectApple emptyBasket (flattenTree tree) -- foldr для сохранения порядка яблок как они встречаются
Поправил, сейчас залью исправленную версию

2023-11-05 06:20 UTC, paiksonn commented on src/MyLib.hs
> +buildHeap = foldr insertValue BinLeaf
Я правильно понимаю, что отменяется вся 6 задача?

2023-11-05 06:27 UTC, paiksonn commented on src/MyLib.hs
> +  mempty = Size' 1
Прописал в обновленном коде

2023-11-05 06:31 UTC, paiksonn commented on src/MyLib.hs
> +-- Conflicting family instance declarations, т.к. хаскель не умеет в синонимы типов, если они идентичны уже существующим
Ну там просто будет ошибка компиляции, т.к. хаскель не позволяет создавать новые инстансы для уже существующих типов или их синонимов, ведь это может привести к конфликтам и/или недопустимым ситуациям

2023-11-05 06:37 UTC, paiksonn commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
Потому что `Leaf` зависит от типа `a`
Для `branch` у нас тип `a` никак напрямую не использовался
А для `Leaf` компилятор не может однозначно определить,  какой `mempty` использовать, потому что это значение должно быть специфичным для типа `a`

2023-11-05 06:43 UTC, paiksonn commented on src/MyLib.hs
> +  measure _ = Priority' maxBound
Кажется, что не очень, т.к. тут просто всем элементам дерева будет назначен максимальный приоритет и тогда свойства кучи в дереве соблюдаться не будут 
По идее, наверное, чтобы это работало правильно, нужно использовать информацию о реальных приоритетах узлов

2023-11-05 06:44 UTC, paiksonn commented on test/TestSpec.hs
> +            studentNames log `shouldBe` ["Ivan", "Artem", "Alexey"]
В обновленной версии кода гендерный баланс восстановлен

2023-11-05 06:50 UTC, paiksonn commented on test/TestSpec.hs
> +            let students = [Student "Hel(-p/-l)" 10000]
Its a mystery...

2023-11-05 06:51 UTC, paiksonn commented on src/MyLib.hs
> +siftDown (BinNode x BinLeaf right) -- слева лист, справа что-то есть
Согласен, убрал в новой версии

2023-11-05 07:18 UTC, paiksonn commented
Все, что было в комментариях, я в коде поправил
Осталось убрать флаги для ворнингов и чуть-чуть подреставрировать код 
Я сделаю это сегодня попозже и залью сюда новую версию со всеми исправлениями

2023-11-05 07:18 UTC, paiksonn commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавил

2023-11-05 15:56 UTC, paiksonn commented
Залил новую версию со всеми исправлениями

2023-11-05 18:55 UTC, pluralia commented on hw5.cabal
> +                      -fno-warn-name-shadowing
> ворнинги по типу шедоуинга ведь никак не влияют на выполнение кода

Технически, любые ворнинги не влияют на выполнение кода.

Проблема c shadowing может выглядеть так:
```
outerFunc x y = outerFunc (x + 1) y
  where
    innerFunc x y = undefined
```
И в этом случае ворнинг очень даже не бесполезный

2023-11-05 18:56 UTC, pluralia commented on hw5.cabal
> +                      -fno-warn-name-shadowing
-fno-warn-unused-imports
-fno-warn-missing-signatures

Понятно ли, почему стоит исправить эти ворнинги?

2023-11-05 18:57 UTC, pluralia commented on src/MyLib.hs
> +    find (\apple -> isColorMatch apple && isWeightInRange apple) (foldMap (: []) tree)
Хорошо. Теперь, когда разобрался, напиши, пожалуйста, с обходом дерева напрямую

2023-11-05 18:58 UTC, pluralia commented on src/MyLib.hs
> +buildHeap = foldr insertValue BinLeaf
Да

2023-11-05 19:03 UTC, pluralia commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
> А для Leaf компилятор не может однозначно определить, какой mempty использовать, потому что это значение должно быть специфичным для типа a

Такой проблемы не возникало в `branch` с `<>`: мы можем так же написать в сигнатуре `leaf :: Monoid a => a -> ...`, и он компилятор поймет, какой `mempty` использовать в зависимости от типа `a`

Еще варианты ответа на вопрос "Почему мы не можем написать leaf, как это сделано в 484-485 строках?"?

2023-11-05 19:04 UTC, pluralia commented on src/MyLib.hs
> +  measure _ = Priority' maxBound
> По идее, наверное, чтобы это работало правильно, нужно использовать информацию о реальных приоритетах узлов

Да. Например, можно выводить приоритет из значения

2023-11-05 19:10 UTC, pluralia commented on src/MyLib.hs
> +  mempty = Size' 1
Законы прописал механически -- пропиши продробнее. У тебя баг в реализации моноида -- найдешь его, если пропишешь законы нормально

2023-11-05 19:12 UTC, pluralia commented on test/TestSpec.hs
> +            let heapBefore = BinNode {val = (40 :: Int)
Не куча по форме

2023-11-05 19:14 UTC, pluralia commented on test/TestSpec.hs
> +        it "Sifts down with multiple levels of incorrect elements" $ do
В `siftDown` должно приходить дерево -- по форме куча, но с 1 неправильным элементом. Понятно, почему так?

Проверь, пожалуйста, свои примеры из тестов

2023-11-05 19:23 UTC, pluralia commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
У меня все работает. Попробуй `cabal clean && cabal test`. Пингани, если ошибка останется

2023-11-05 19:23 UTC, pluralia commented
1 ворнинг и много hlint -- не залил исправление скобок?

2023-11-05 19:36 UTC, paiksonn commented on hw5.cabal
> +                      -fno-warn-name-shadowing
Да
Зачем нам импортировать то, что мы дальше не используем и тратить на это ресурсы
И лучше определять все сигнатуры, чтобы не попасть в неловкую ситуацию

2023-11-05 20:10 UTC, paiksonn commented on src/MyLib.hs
> +    find (\apple -> isColorMatch apple && isWeightInRange apple) (foldMap (: []) tree)
вот так это выглядит:
```haskell
thisApple :: Tree Apple -> [String] -> (Float, Float) -> Maybe Apple
thisApple tree colors weightRange = 
  foldr findDesiredApple Nothing tree
  where
    findDesiredApple :: Apple -> Maybe Apple -> Maybe Apple
    findDesiredApple apple acc =
      if isDesiredApple apple then Just apple else acc

    isDesiredApple :: Apple -> Bool
    isDesiredApple (Apple appleColor appleWeight) =
      appleColor `elem` colors && appleWeight >= lowerBound weightRange && appleWeight <= upperBound weightRange

    lowerBound :: (Float, Float) -> Float
    lowerBound = fst

    upperBound :: (Float, Float) -> Float
    upperBound = snd
```

2023-11-05 20:20 UTC, paiksonn commented on src/MyLib.hs
> +  mempty = Size' 1
Согласен, нейтральный элемент тут 0, а не 1, тк для сайза мы реализуем сложение, а не умножение

2023-11-05 20:21 UTC, paiksonn commented on src/MyLib.hs
> +  mempty = Size' 1
```haskell

instance Monoid Size' where
  mempty :: Size'
  mempty = Size' 0
```

2023-11-05 20:24 UTC, paiksonn commented on test/TestSpec.hs
> +        it "Sifts down with multiple levels of incorrect elements" $ do
Да, согласен, почему-то у меня в голове смешались две задачи
Сифтдаун умеет один элемент кучи ставить на место, а не все элементы в куче сразу 
поправлю сейчас

2023-11-05 20:27 UTC, paiksonn commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
Тогда я не очень понимаю откуда думать, т.к. если просто раскоментировать эти строки и запустить (при этом закомментировав исправленную реализацию лифа) - все работает, ничего не падает и даже ворнингов нет

2023-11-05 21:00 UTC, paiksonn commented on test/TestSpec.hs
> +            let heapBefore = BinNode {val = (40 :: Int)
поправил и залил

2023-11-05 21:03 UTC, paiksonn commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
Да, попробовал, все равно так, причем только на проверках лифов, бранчи нормально строятся, но на 244 и 254 строках кода (обновленного), т.е. где:
```haskell
it "Creates a single leaf with Size' annotation" $ do
            leaf (5 :: Int) `shouldBe` BLeaf (Size' 1) 5

it "Creates a single leaf with Priority' annotation" $ do
            leaf (5 :: Int) `shouldBe` BLeaf (Priority' maxBound) 5
```
вот там компилятор выдает ошибки:
```haskell
test\TestSpec.hs:244:29: error: [GHC-39999]
    * No instance for `Eq (BinaryTree Size' Int)'
        arising from a use of `shouldBe'
    * In a stmt of a 'do' block:
        leaf (5 :: Int) `shouldBe` BLeaf (Size' 1) 5
      In the second argument of `($)', namely
        `do leaf (5 :: Int) `shouldBe` BLeaf (Size' 1) 5'
      In a stmt of a 'do' block:
        it "Creates a single leaf with Size' annotation"
          $ do leaf (5 :: Int) `shouldBe` BLeaf (Size' 1) 5
    |
244 |             leaf (5 :: Int) `shouldBe` BLeaf (Size' 1) 5
```

2023-11-05 21:08 UTC, paiksonn commented
Все обновил, ворнингов нет, hlint тоже молчит

2023-11-06 12:09 UTC, pluralia commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
Попробуй построить дерево, используя раскомментированный leaf

2023-11-06 15:58 UTC, paiksonn commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
Упал с ошибкой "No instance for `Monoid Size' arising from a use of `leaf'"

2023-11-07 09:31 UTC, pluralia commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
1. Ну, слушай, такую ошибку ты уже умеешь исправлять. Подумай, в чем проблема
2. Не можешь запустить, построй на бумаге -- должен увидеть, в чем проблема, когда размер листа указан как 0

2023-11-07 09:32 UTC, pluralia commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
У тебя не везде добавлены `deriving Eq`

2023-11-07 09:33 UTC, pluralia commented
Надо
1. Исправить реализацию Measured для  Priority
2. Добавить/раскомментировать тесты для leaf и branch -- после этого куча hlint
3. Доисправлять это
<img width="1197" alt="Screenshot 2023-11-06 at 13 16 33" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/78ca6e3e-6782-49a1-84b6-b5eee844377c">

2023-11-07 09:38 UTC, paiksonn commented
> Надо
> 
> 1. Исправить реализацию Measured для  Priority
> 2. Добавить/раскомментировать тесты для leaf и branch -- после этого куча ворнингов
> 3. Доисправлять это
> 
> <img alt="Screenshot 2023-11-06 at 13 16 33" width="1197" src="https://user-images.githubusercontent.com/15619772/280703111-78ca6e3e-6782-49a1-84b6-b5eee844377c.png">

1 и 2 я попробую поправить 
По поводу третьего - у меня нет такого ворнинга и нет этих рекомендаций от hlint`а, я попробую их поправить, но не уверен, что ничего не сломаю в процессе

2023-11-07 09:48 UTC, pluralia commented
hlint не твой -- это из домашки; его можно не исправлять тогда

2023-11-07 17:53 UTC, paiksonn commented on src/MyLib.hs
> +--   Потому что у нас получились для него разные типы данных (размер и приоритет)
Чтобы воспользоваться тем же моноидом (как мы это делали для branch), нам нужен mempty (пустое множество по своей сути), но leaf - не пустое множество, в этом и проблема, поэтому нельзя использовать код закомментированный

2023-11-07 18:28 UTC, paiksonn commented
> Надо
> 
> 1. Исправить реализацию Measured для  Priority
> 2. Добавить/раскомментировать тесты для leaf и branch -- после этого куча ворнингов

> 1. Исправил
> 2. Исправил
> 3. У меня нет никаких ворнингов и рекомендаций hlint 
![Снимок экрана 2023-11-07 212610](https://github.com/pluralia/fp-fall-2023/assets/113239177/f76a2cf5-12aa-40ea-ae17-573be45c518a)

2023-11-07 18:50 UTC, closed without merging