HW5 ManasyanAL
pluralia/fp-fall-2023 pull request #28
Opened 2023-11-02 11:33 UTC by Artem9999999999999999999999

2023-11-05 00:01 UTC, pluralia requested changes

2023-11-05 00:01 UTC, pluralia commented on hw5/src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавь, пожалуйста, 1-2 теста на создание деревьев Size и Priority с помощью leaf и branch

2023-11-07 11:59 UTC, Artem9999999999999999999999 commented on hw5/src/MyLib.hs
> +-- Int. Поэтому Haskell не позволяет создать несколько идентичных экземпляров типов.
тут имел ввиду как раз термин синонимы. Haskell не позволяет создавать экземпляры синонимов типов, идентичные существующим экземплярам

2023-11-07 12:00 UTC, Artem9999999999999999999999 commented
Поправил замечания, все в новом коммите

2023-11-07 12:38 UTC, pluralia commented on hw5/src/MyLib.hs
> +        insertSorted = insertSorted'
Используй, пожалуйста, библиотечную функцию сортировки

2023-11-07 12:38 UTC, pluralia commented on hw5/src/MyLib.hs
> +-- Int. Поэтому Haskell не позволяет создать несколько идентичных экземпляров типов.
Ты можешь создать несколько синонимов типов (как у нас было Size и Priority), но не можешь создать несколько инстансов одного класса типов для них. Понятно ли, что это значит? Можешь привести пример?

2023-11-07 13:54 UTC, Artem9999999999999999999999 commented
Сделал коммит с комментариями и исправлениями

2023-11-07 14:44 UTC, pluralia commented on hw5/src/MyLib.hs
> +-- даже если у нас есть разные синонимы для него.
Верно! Потому что синонимы -- это просто имена для одного и того же типа, а создавать несколько инстансов одного класса для одного типа нельзя. Именно поэтому решение -- обернуть в новый тип

2023-11-07 14:44 UTC, pluralia commented
👍

2023-11-07 14:44 UTC, closed without merging