Hw5_Pushkina_Olga
pluralia/fp-fall-2023 pull request #29
Opened 2023-11-02 19:15 UTC by forestcream

hlint и ворнингов у меня нет

2023-11-05 00:03 UTC, pluralia requested changes
Вижу ворнинги. Попробуй `cabal clean && cabal test`

2023-11-05 00:03 UTC, pluralia commented on hw5/src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавь, пожалуйста, 1-2 теста на создание деревьев Size и Priority с помощью leaf и branch

2023-11-05 00:03 UTC, pluralia commented on hw5/test/TestSpec.hs
> +    describe "siftDown" $ do
Хочется деревья поинтереснее

2023-11-07 18:55 UTC, forestcream commented on hw5/src/MyLib.hs
> +        , worstGrade   = case (worstGrade a, worstGrade b) of
```
instance Semigroup StudentsLog where
    (<>) :: StudentsLog -> StudentsLog -> StudentsLog
    a <> b = StudentsLog
        { studentNames = studentNames a ++ studentNames b
        , worstGrade   = min <$> worstGrade a <*> worstGrade b
        , bestGrade    = max <$> bestGrade a <*> bestGrade b
        }
```

2023-11-07 19:34 UTC, forestcream commented on hw5/src/MyLib.hs
> +        , bestGrade    = case (bestGrade a, bestGrade b) of
По идее вот так, но у меня начинается какая-то бурда с Nothing (из-за этого min и max странно работают), и кроме как опять налепить case, я не знаю как это исправить
```
instance Semigroup StudentsLog where
    (<>) :: StudentsLog -> StudentsLog -> StudentsLog
    a <> b = StudentsLog
        { studentNames = studentNames a ++ studentNames b
        , worstGrade   = min <$> worstGrade a <*> worstGrade b
        , bestGrade    = max <$> bestGrade a <*> bestGrade b
        }
```

2023-11-07 19:35 UTC, forestcream commented on hw5/src/MyLib.hs
> +-- чтобы тесты работали нужны инстансы Show и Eq
Сделала
```
data Student = Student 
    { name  :: String -- имя студента
    , grade :: Int    -- оценка студента по нашему предмету
    } deriving(Eq, Show)

data StudentsLog = StudentsLog
    { studentNames :: [String]  -- список имён студентов
    , worstGrade   :: Maybe Int -- наименьшая оценка по курсу
    , bestGrade    :: Maybe Int -- наибольшая оценка по курсу
    } deriving(Eq, Show)
```

2023-11-07 19:41 UTC, forestcream commented on hw5/src/MyLib.hs
> +applesInRange tree (low, high) = all inRange (foldMap (\apple -> [weight apple]) tree)
```
applesInRange :: Tree Apple -> (Float, Float) -> Bool
applesInRange tree (low, high) = getAll $ foldMap (\apple -> All $ weight apple >= low && weight apple <= high) tree
```

2023-11-07 19:48 UTC, forestcream commented on hw5/src/MyLib.hs
> +sumOfApples = foldr (\apple acc -> weight apple + acc) 0.0
Используем моноид `Sum`
```
sumOfApples :: Tree Apple -> Float
sumOfApples = getSum . foldMap (Sum . weight)
```

2023-11-07 20:15 UTC, forestcream commented on hw5/src/MyLib.hs
> +getInd (BLeaf _ a) _ = a
Вернется скорее всего ошибка, поэтому лучше поменяем `a` на `Maybe a` и проверяем неправильные значения. Я так же дополнила тесты
```
getInd :: BinaryTree Size a -> Int -> Maybe a
getInd (BLeaf _ a) n
  | n == 0 = Just a
  | otherwise = Nothing
getInd (BBranch _ left' right') n
  | n < sizeLeft = getInd left' n
  | otherwise     = getInd right' (n - sizeLeft)
  where sizeLeft = tag left'
```

2023-11-08 07:30 UTC, forestcream commented on hw5/src/MyLib.hs
> +  mempty = Size' 0
Потому что в сложении нейтральный элемент 0, плюс выполняется тогда закон для моноида, и если мы прибавим `Size' 0` к любому элементу, то он не поменяется

2023-11-08 07:36 UTC, forestcream commented on hw5/src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавила в коммит

2023-11-08 07:44 UTC, forestcream commented on hw5/test/TestSpec.hs
> +    describe "siftDown" $ do
добавила в коммит

2023-11-08 12:24 UTC, pluralia commented on hw5/src/MyLib.hs
> +        , bestGrade    = case (bestGrade a, bestGrade b) of
Поясни, пожалуйста, в чем именно проблема

2023-11-08 12:49 UTC, pluralia commented on hw5/src/MyLib.hs
> +        , bestGrade    = case (bestGrade a, bestGrade b) of
Концептуально тут получается 2 варианта обработки Nothing:
1. Мы говорим, что, если хотя бы у одного студента нет grade, мы не можем посчитать результирующую best/worstGrade. Эта версия получится, если использовать `min <$> worstGrade a <*> worstGrade b` и поменять `mempty`
2. То, как у тебя было реализовано: мы игнорируем Nothing, и за счет этого можем посчитать результирующую best/worstGrade, если хотя бы у одного студента есть не Nothing в качестве grade

Как лучше делать? Оба варианта нормальные

2023-11-09 10:18 UTC, forestcream commented on hw5/src/MyLib.hs
> +  | x > minChildVal = BinNode minChildVal (siftDown $ replaceMinChild x) right'
Да, было  понятно, что не так, но долго не могла этого сделать 
Ощущение, что вот так должно удовлетворять всем условиям 
```
siftDown :: Ord a => BinaryHeap a -> BinaryHeap a
siftDown BinLeaf = BinLeaf
siftDown heap@(BinNode x left' right')
  | x > rootVal left' && rootVal left' <= rootVal right' = BinNode (rootVal left') (siftDown $ replaceVal left' x) right'
  | x > rootVal right' && rootVal right' < rootVal left' = BinNode (rootVal right') left' (siftDown $ replaceVal right' x)
  | otherwise = heap
  where
    rootVal BinLeaf = x
    rootVal (BinNode y _ _) = y
    replaceVal (BinNode _ l r) v = BinNode v l r
    replaceVal BinLeaf _ = BinLeaf
```

2023-11-09 11:54 UTC, pluralia commented on hw5/src/MyLib.hs
> +  | x > minChildVal = BinNode minChildVal (siftDown $ replaceMinChild x) right'
Выглядит верно, но не запускала

2023-11-09 11:55 UTC, pluralia commented
👍

2023-11-09 11:55 UTC, closed without merging

2023-11-09 11:56 UTC, pluralia commented
Поставлю тебе  +0,25 за `Measured Priority` -- ты единственная с первого раза написала ее верно!