HW01_DmitrievOS
pluralia/fp-fall-2023 pull request #3
Opened 2023-10-02 12:33 UTC by qilowoq

2023-10-03 16:15 UTC, pluralia requested changes

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +-- | c хвостовой рекурсией: Int переполняется
Что можно сделать, чтобы переполнения не происходило?

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +myLength :: [a] -> Int
Будет ли работать эта функция на списках очень большой длины?

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +myInit (x : xs) = Right (x : unpack (myInit xs))
Как переписать эту функцию с `mapMaybe`?

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +    where unpack (Right x) = x
Может ли здесь прийти `Left`?

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +myReverse :: [a] -> [a]
Хочется хвостовую рекурсию

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +elemByIndex (x : xs) ind | myLength (x : xs) <= ind   = Left "Index out of range"
Если хочется иметь доступ к исходному не разобранному списку, можно написать так
```haskell
elemByIndex s@(x : xs) ind | myLength s <= ind = Left "Index out of range"
```

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
> +allTests4 = testMyLength <^> testMyTail <^> testMyInit <^> testMyAppend <^> testMyReverse <^> testElemByIndex
Можно использовать функцию `and :: [Bool] -> Bool`

2023-10-03 16:15 UTC, pluralia commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
Будет ли работать эта функция на списках большой длины?

2023-10-04 07:52 UTC, qilowoq commented on hw1.hs
> +myAnd x y = if x && y then True else False
Тогда используем патерн матчинг

myAnd True True = True
myAnd _ _ = False

2023-10-04 08:07 UTC, qilowoq commented on hw1.hs
> +(<^>) x y = myAnd x y
У дефолтного and приоритет 3 и правоассоциативность (как я понял это нужно для ленивости операции). Значит нужно сделать так: 

infixr 3 <^>

2023-10-04 08:07 UTC, qilowoq commented on hw1.hs
> +-- | c хвостовой рекурсией: Int переполняется
Истпользовать Integer. Он не переполнится

2023-10-04 08:10 UTC, qilowoq commented on hw1.hs
> +fib n | n < 0     = error "Lower than 0"
Тогда сделает так:

fibTail :: Integer -> Either String Integer
fibTail n | n < 0        = Left "Negative n"
             | otherwise = Right helper 0 1 n
  where
    helper a b n | n == 0     = a
                        | otherwise = helper b (a + b) (n - 1)

2023-10-04 08:17 UTC, qilowoq commented on hw1.hs
> +myLength :: [a] -> Int
Нет. Если длина списка превышает максимальное значение, которое может быть представлено типом Int, то произойдет переполнение и результат будет некорректным.

2023-10-04 08:33 UTC, qilowoq commented on hw1.hs
> +myReverse :: [a] -> [a]
Тогда так:
```

myReverse :: [a] -> [a]
myReverse [] = []
myReverse (x : xs) = helper xs [x]
  where helper [] acc       = acc
        helper (x : xs) acc = helper xs (x : acc)
```

2023-10-04 08:36 UTC, qilowoq commented on hw1.hs
> +allTests4 = testMyLength <^> testMyTail <^> testMyInit <^> testMyAppend <^> testMyReverse <^> testElemByIndex
`
allTests4 = and [testMyLength, testMyTail, testMyInit, testMyAppend, testMyReverse, testElemByIndex]
`

2023-10-04 08:38 UTC, qilowoq commented on hw1.hs
> +elemByIndex (x : xs) ind | myLength (x : xs) <= ind   = Left "Index out of range"
Пон

2023-10-04 08:42 UTC, qilowoq commented on hw1.hs
>  mapList :: (a -> b) -> [a] -> [b]
Да. Не вижу что бы тут этому мешало

2023-10-04 08:44 UTC, qilowoq commented on hw1.hs
> +    where unpack (Right x) = x
Если имеется в виду может ли unpack получит `Left  x` на вход, то нет тк `xs ` это всегда не пустой список

2023-10-04 09:21 UTC, qilowoq commented on hw1.hs
> +myInit (x : xs) = Right (x : unpack (myInit xs))
`myInit :: [a] -> Maybe [a]
myInit [] = Nothing
myInit [x] = Just []
myInit (x : xs) = mapMaybe (x :) (myInit xs)`

2023-10-04 10:59 UTC, qilowoq commented on hw1.hs
> +myLength :: [a] -> Int
Поменять `Int ` на `Integer`

```
myLength :: [a] -> Integer
myLength [] = 0
myLength (_ : xs) = 1 + myLength xs

```

2023-10-04 11:14 UTC, pluralia commented on hw1.hs
> +myLength :: [a] -> Int
A если запустить `myLength [1..100000000]`?

2023-10-04 11:41 UTC, qilowoq commented on hw1.hs
> +myLength :: [a] -> Int
Будет `*** Exception: stack overflow`

Если поменять на так: 

```
myLength :: [a] -> Integer
myLength (_ : xs) = helper xs 1
  where helper [] acc       = acc
        helper (_ : xs) acc = helper xs (acc + 1)
```

То мы немного оттянем `*** Exception: stack overflow`. Хотя на примере выше все равно валится

2023-10-04 11:45 UTC, pluralia commented on hw1.hs
> +myLength :: [a] -> Int
У меня версия с хвостовой рекурсией и `Integer` отрабатывает хорошо на примере

2023-10-04 11:45 UTC, pluralia commented
👍

2023-10-04 11:45 UTC, closed without merging