HW5 Kostina
pluralia/fp-fall-2023 pull request #30
Opened 2023-11-02 20:06 UTC by jmkostina

2023-11-05 00:05 UTC, pluralia requested changes
-0,5 за ворнинги
-1,5 за 8
-1 за 10
----
-3 суммарно

2023-11-05 00:05 UTC, pluralia commented on test/TestSpec.hs
> +        studentNames log1 `shouldBe` (["Julia", "Olga", "Sonya"] ::[String])
Мальчиков не хватает

2023-11-05 00:05 UTC, pluralia commented on test/TestSpec.hs
> +        siftDown (BinNode (3 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf) (BinNode (1 :: Integer) BinLeaf BinLeaf)) `shouldBe` BinNode (1 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf)
Деревья с более интересной формой хочется

2023-11-08 14:35 UTC, jmkostina commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
мне подсказали, что должно быть так
```haskell
getWorstGrade a b = min <$> a <*> b
```
Но, когда я пробую протестить эту функцию на непустом списке, у меня вместо наихудшей оценки выдает Nothing

2023-11-08 14:35 UTC, jmkostina commented on src/MyLib.hs
> +    studentNames = if null studentsList then [] else map name studentsList
Можно без нее, просто `map name studentsList`, потому что если studentsList пустой, то и так вернется []

2023-11-08 14:35 UTC, jmkostina commented on src/MyLib.hs
> +-- fmap (f . g)  ==  fmap f . fmap g => ???? я не поняла, что именно здесь нужно. это закон вроде из 25 строчки вытекает
```haskell
fmap (f . g) (Arrow h) -> Arrow (f . g) $ h ->  Arrow((f . g) . h)-- меняю $ на .
Arrow ((f . g) . h)-> Arrow(f . (g . h)) -- ассоциативность
Arrow (f . (g . h)) -> fmap f (fmap g (Arrow h))
```

2023-11-08 14:41 UTC, jmkostina commented on src/MyLib.hs
> +siftDown (BinNode v BinLeaf right)| v < val right = BinNode v BinLeaf right
Просто убираю этот случай
```haskell
siftDown :: Ord a => BinaryHeap a -> BinaryHeap a
siftDown BinLeaf = BinLeaf
siftDown (BinNode v BinLeaf BinLeaf) = BinNode v BinLeaf BinLeaf
siftDown (BinNode v left BinLeaf) | v < val left = BinNode v left BinLeaf
                                  | otherwise = BinNode (val left) (siftDown (left {val = v})) BinLeaf
siftDown (BinNode v left right)   | v < min (val left) (val right) = BinNode v left right
                                  | val left < val right = BinNode (val left) (siftDown (left {val = v})) right
                                  | otherwise = BinNode (val right) left (siftDown (right {val = v}))
```

2023-11-08 14:42 UTC, jmkostina commented on test/TestSpec.hs
> +        studentNames log1 `shouldBe` (["Julia", "Olga", "Sonya"] ::[String])
Я решила, что для теста можно обойтись только девочками

2023-11-08 15:53 UTC, pluralia commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
Есть идеи, почему?

2023-11-08 15:56 UTC, pluralia commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
Концептуально в этом задании есть 2 варианта обработки Nothing для grade:

1. Мы говорим, что, если хотя бы у одного студента нет grade, мы не можем посчитать результирующую best/worstGrade. Эта версия получится, если использовать min <$> worstGrade a <*> worstGrade b и использовать правильные инициализирующие значения
2. То, как у тебя было реализовано: мы игнорируем Nothing, и за счет этого можем посчитать результирующую best/worstGrade, если хотя бы у одного студента есть не Nothing в качестве grade

Как лучше делать? Оба варианта нормальные.
Зачем прошу расписать через <$> и <*>? Чтобы показать альтернативный вариант и важность правильной инициализации

2023-11-08 15:57 UTC, pluralia commented on src/MyLib.hs
> +getInd (BLeaf _ a) 1 = a
Давай разбираться. Ты рассмотрела все возможные конструкторы для первого аргумента `BinaryTree Size a`, но что насчет второго аргумента `Int`?

2023-11-08 15:58 UTC, pluralia commented on src/MyLib.hs
> +siftDown (BinNode v BinLeaf right)| v < val right = BinNode v BinLeaf right
Ок, пусть так. Я бы предложила обернуть в Maybe

2023-11-09 12:43 UTC, jmkostina commented on src/MyLib.hs
> +getInd (BLeaf _ a) 1 = a
? то есть нужно учесть 
```haskell
getInd (BLeaf _ a) _ = error "Size error"
```

2023-11-09 12:47 UTC, jmkostina commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
если брать первый вариант, то нужно поменять `mempty` для best/worstGrade, но по их типу Maybe Int там в `mempty` не может быть 0 и 10, к тому же мы не оставляем вариантов для других систем оценок. То есть нужен какой-то тип (класс?) который позволяет выполнять обработку. Но я такого типа не знаю

2023-11-09 12:59 UTC, pluralia commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
Можно взять минимальный и максимальный Int

2023-11-09 13:04 UTC, jmkostina commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
То есть прописываю `(Just maxBound Int) (Just minBound Int)` в mempty ?

2023-11-09 13:08 UTC, pluralia commented on src/MyLib.hs
> +        getWorstGrade :: Maybe Int -> Maybe Int -> Maybe Int
> То есть прописываю (Just maxBound Int) (Just minBound Int) в mempty ?

Почти. Посмотри, как в этом случае вызывается  `minBound`. Запись `minBound Int` не имеет смысла

2023-11-09 13:09 UTC, pluralia commented on test/TestSpec.hs
> +        siftDown (BinNode (3 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf) (BinNode (1 :: Integer) BinLeaf BinLeaf)) `shouldBe` BinNode (1 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf)
@jmkostina, добавь, пожалуйста, деревья. Обрати внимание на свойство кучи: только последний уровень может быть неполным

2023-11-09 21:28 UTC, jmkostina commented on test/TestSpec.hs
> +        siftDown (BinNode (3 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf) (BinNode (1 :: Integer) BinLeaf BinLeaf)) `shouldBe` BinNode (1 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf)
Я попробовала добавить деревья, но у меня не ожидаемое поведение на тесте. видимо, моя функция все же не корректна

2023-11-11 10:06 UTC, pluralia commented on test/TestSpec.hs
> +        siftDown (BinNode (3 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf) (BinNode (1 :: Integer) BinLeaf BinLeaf)) `shouldBe` BinNode (1 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf)
@jmkostina, покажи тесты, на которых завалилось. Балл я тебе полный поставила за это задание, но нужно разобраться. PR не закрою без тестов

2023-11-11 18:25 UTC, jmkostina commented on test/TestSpec.hs
> +        siftDown (BinNode (3 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf) (BinNode (1 :: Integer) BinLeaf BinLeaf)) `shouldBe` BinNode (1 :: Integer) (BinNode (2 :: Integer) BinLeaf BinLeaf)
Я тормоз, все работает
Дерево такое было
```haskell
let myheap2 = BinNode { val = 5
                , left  = BinNode {val=3, 
                                    left = BinNode {val=1, 
                                                     left=BinNode {val=4, 
                                                                    left=BinLeaf, 
                                                                    right=BinLeaf},
                                                     right = BinNode {val=7, 
                                                                    left=BinLeaf,
                                                                    right=BinLeaf}
                                                    },
                                    right = BinNode {val=13, 
                                                     left=BinNode {val=11, 
                                                                    left=BinLeaf, 
                                                                    right=BinLeaf},
                                                     right = BinNode {val=8, 
                                                                    left=BinLeaf,
                                                                    right=BinLeaf}
                                                    }
                                    } 
                , right = BinNode {val=6, 
                                    left = BinNode {val=2, 
                                                     left = BinLeaf,
                                                     right = BinLeaf
                                                     }, 
                                    right = BinNode {val=9, 
                                                     left=BinLeaf,
                                                     right=BinLeaf
                                                     }
                                    }
                }
```
Результат для `siftDown myheap2` такой, потому что я на куче запускаю `siftDown` только 1 раз, а не в цикле, как нужно, чтобы полностью восстановить кучу.
```haskell
let correctmyheap2 = BinNode { val = 3
                , left  = BinNode {val=1, 
                                    left = BinNode {val=4, 
                                                     left=BinNode {val=5, 
                                                                    left=BinLeaf, 
                                                                    right=BinLeaf},
                                                     right = BinNode {val=7, 
                                                                    left=BinLeaf,
                                                                    right=BinLeaf}
                                                    },
                                    right = BinNode {val=13, 
                                                     left=BinNode {val=11, 
                                                                    left=BinLeaf, 
                                                                    right=BinLeaf},
                                                     right = BinNode {val=8, 
                                                                    left=BinLeaf,
                                                                    right=BinLeaf}
                                                    }
                                    } 
                , right = BinNode {val=6, 
                                    left = BinNode {val=2, 
                                                     left = BinLeaf,
                                                     right = BinLeaf
                                                     }, 
                                    right = BinNode {val=9, 
                                                     left=BinLeaf,
                                                     right=BinLeaf
                                                     }
                                    }
                }
```
Полное восстановление, это как раз следующее задание, которое никто не сделал

2023-11-11 18:34 UTC, pluralia commented
👍

2023-11-11 18:34 UTC, closed without merging