HW5_Shishkina
pluralia/fp-fall-2023 pull request #31
Opened 2023-11-02 20:50 UTC by SophiaLaz

2023-11-05 00:08 UTC, pluralia requested changes
Умничка, что решила buildHeap! Я сняла задачу из домашки, поэтому тебе бонусный +1 балл

У меня завалился тест. Ответ близок к ожидаемому, поэтому скорее всего какие-то приколы с округлением не целых чисел, но нужно разобраться

2023-11-05 00:08 UTC, pluralia commented on src/MyLib.hs
> +-------------------------------------------------------------------------------
Добавь, пожалуйста, 1-2 теста на создание деревьев Size и Priority с помощью leaf и branch

2023-11-05 00:10 UTC, pluralia commented on test/TestSpec.hs
> +    describe "9 - не очень понятно, что тестировать" $ do
Что деревья верно создаются -- leaf и branch

2023-11-06 20:12 UTC, SophiaLaz commented on src/MyLib.hs
> +siftDown heap
запускает siftDown на правом поддереве
добавила тест на такую ситуацию

2023-11-06 20:13 UTC, SophiaLaz commented on src/MyLib.hs
> +getInd (BLeaf _ value)          _                              = value
нет, исправила это

2023-11-07 09:40 UTC, pluralia commented on src/MyLib.hs
> +       StudentsLog { studentNames = n1 <> n2
Я не подразумевала использование этих операторов, но так тоже хорошо

2023-11-07 09:45 UTC, pluralia commented on src/MyLib.hs
> +  -- но законы не выполнялись, так что исправила значение на 0
Верно! 
Значит, ты реально, а не механически расписала законы -- молодец ;)

2023-11-07 09:53 UTC, SophiaLaz commented on src/MyLib.hs
> +siftDown heap
Если учесть, что куча - сбалансированное бинарное дерево, которое заполняется слева направо по уровням, значит такой ситуации быть не может.
Могу добавить исключение на эту ситуацию "Unreacheble statement".

2023-11-07 09:57 UTC, pluralia commented
Чтобы тест не валился, можно писать проверку для Float/Double так
```haskell
abs (43.2 - sumOfApples tree1) `shouldSatisfy` (< 1e-5)
```

2023-11-07 10:00 UTC, pluralia commented on src/MyLib.hs
> +siftDown heap
Можно так оставить: мне важно только, что ты об этом знаешь. Как эту ситуацию обрабатывать уже другой вопрос -- в целом, можно и так, как ты в коде

2023-11-07 10:01 UTC, pluralia commented
Домашку засчитываю 👍 

Буду ждать ответ про тесты

2023-11-07 10:01 UTC, closed without merging

2023-11-07 10:28 UTC, SophiaLaz commented
Не получается ответить на комментарий, так что напишу тут.
У меня тесты не валились, поэтому и забыла сразу исправить. Но я поправила все тесты для функции `sumOfApples` с более аккуратным сравнением чисел типа `Float`

2023-11-07 11:12 UTC, pluralia commented
Здесь важно следующее: результат исполнения программы может варьироваться в зависимости от версии компилятора / примененных компиляторных оптимизаций, если сравнивать Double или Float с конкретным числом. Вывод: числа с плавающей точкой  нужно сравнивать с допуском или не сравнивать вообще. Это верно не только для Haskell, но для любого языка программирования