HW6_Shishkina
pluralia/fp-fall-2023 pull request #32
Opened 2023-11-06 19:28 UTC by SophiaLaz

2023-11-12 13:27 UTC, pluralia requested changes

2023-11-12 13:27 UTC, pluralia commented on src/MyLib.hs
> +rowP colnames = Row . fromList <$> (zip colnames <$> abstractRowP ',' valueP)
Можно убрать первый `<$>`

2023-11-13 13:57 UTC, SophiaLaz commented on src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
Это очень хороший вопрос и я пока не нашла на него внятного ответа)
Когда я запускала у себя, компилятор ругался на то, что я неправильно объявляю инстансы и хотел прагму `InstanceSigs` - при том, что она уже была указана. Так как он ругался на инстансы, я подумала, что можно добавить `FlexibleInstances` и с ней заработало. 
Но меня смущает то, что хоть в коде и присутствуют `Parser Int, Parser String` и прочие подобные конструкци, инстансы я объявляла для `Parser a`, а значит использование этой прагмы неочевидно.

2023-11-13 14:03 UTC, SophiaLaz commented on src/MyLib.hs
> +    firstDigitP = singleton . digitToInt <$> satisfyP (`elem` "123456789")
range на `Char` - не догадалась бы, а красиво) и логично, что для `['1'..'10']` не работает - `'10'` не является типом `Char`

2023-11-13 14:16 UTC, SophiaLaz commented on src/MyLib.hs
> +-- мы работаем над чем-то __в контексте__: в случае парсеров "обёрткой" выступает Maybe,
Сам парсер тоже выступает в роли контекста

2023-11-13 14:42 UTC, SophiaLaz commented on src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
Я всё же нашла причину и эта прагма действительно не нужна))
Надо было оставить только файл с парсером в папке `src` - тогда все работает хорошо) Непонятно только, почему оно чинило такую штуку...

2023-11-13 15:20 UTC, SophiaLaz commented on src/MyLib.hs
> +rowP colnames = Row . fromList <$> (zip colnames <$> abstractRowP ',' valueP)
исправила на композицию

2023-11-13 15:59 UTC, pluralia commented on src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
> Надо было оставить только файл с парсером в папке src - тогда все работает хорошо)

А как было до этого?

2023-11-13 16:01 UTC, pluralia commented on src/MyLib.hs
> +-- мы работаем над чем-то __в контексте__: в случае парсеров "обёрткой" выступает Maybe,
Можешь развернуть мысль? Хочу увидеть не просто `f == Parser`, а какие именно типы внутри `Parser` соответствуют `f`

2023-11-13 16:31 UTC, SophiaLaz commented on src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
было две копии парсера, в src и в корне проекта

2023-11-13 16:57 UTC, SophiaLaz commented on src/MyLib.hs
> +-- мы работаем над чем-то __в контексте__: в случае парсеров "обёрткой" выступает Maybe,
Тип парсера:
```haskell
f :: String -> Maybe (_ , String)
```
На месте `_` то, что мы парсим (`Expr, Int, SimpleExpr`)

2023-11-13 16:59 UTC, pluralia commented
👍

2023-11-13 16:59 UTC, closed without merging