HW6 ManasyanAL
pluralia/fp-fall-2023 pull request #33
Opened 2023-11-07 10:50 UTC by Artem9999999999999999999999

2023-11-12 13:27 UTC, pluralia requested changes

2023-11-12 13:27 UTC, pluralia commented on hw6/src/MyLib.hs
> +    valuesMapP = fromList . zip colN <$> abstractRowP ',' valueP
Не нужно выносить в отдельную функцию

2023-11-12 21:07 UTC, Artem9999999999999999999999 commented
Сделал коммит, в нем правки и ответы на вопросы

2023-11-13 11:16 UTC, pluralia commented on hw6/src/MyLib.hs
> +rowP colN = Row . fromList . zip colN <$> abstractRowP ',' valueP -- сейчас понял, что это решение не будет работать для float,
Хорошее замечание! Исправлю регулярку для float в задании домашки

2023-11-13 11:20 UTC, pluralia commented on hw6/src/MyLib.hs
> +-- где Just содержит пару с результатом парсинга типа b и оставшейся частью строки ввода, или Nothing, если парсинг не удался.
Вроде верно, но как-то вокруг да около.

`f :: Type -> Type` -- значит, это тип, который принимает на вход другой тип. Смотрим на то, что внутри у парсера. Там ` String -> Maybe (a, String)`, где `a` -- типовой параметр. Т.e. `f` здесь -- все вокруг него.

2023-11-13 11:20 UTC, pluralia commented
👍

2023-11-13 11:20 UTC, closed without merging