HW6_DmitrievOS
pluralia/fp-fall-2023 pull request #34
Opened 2023-11-09 05:38 UTC by qilowoq

2023-11-12 13:19 UTC, pluralia requested changes
-0,25 за hlint
-0,25 за 3b

2023-11-14 09:14 UTC, qilowoq commented on hw6/src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
Оно не надо. Было бы надо если бы я хотел бы определить `Inctance Parser Int` например

2023-11-14 09:33 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
По типам будет что-то типо такого

```haskell 
g :: a -> b
aP :: Parser a
fmap g aP :: Parser b
```

То есть к результату `aP` применится `g`

2023-11-14 18:34 UTC, pluralia commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
А что такое `f` так и не ответил ;)

2023-11-14 18:38 UTC, pluralia commented
Ответишь про `f` и зачту

2023-11-14 18:45 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
`f :: a -> (b -> Maybe (b, String))` 

мб не знаю

2023-11-15 12:59 UTC, pluralia commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
Как ты получил эту функцию?

2023-11-15 13:00 UTC, pluralia commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
- `fmap :: (a -> b) -> f a -> f b`
- `fmap :: (a -> b) -> Parser a -> Parser b`
- `newtype Parser a = Parser { runParser :: String -> Maybe (a, String) }`

1. `f` -- функция на типах, она ждет тип на вход, поэтому запись `f :: a -> (b -> Maybe (b, String))` некорректна
2. `f == Parser`
3. Если подставить определение парсера вместо `Parser` в п.2, то какая функция на типах получится?

2023-11-15 14:23 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
`f :: String -> Maybe (a, String)` ?

Честно говоря, я не понимаю. Я смотрю на реализацию `fmap` для парсера, там `f :: a -> b`. Принимает тип a, выдает тип b. 

Почему `f == Parser`?

Что значит "как именно выглядит контекст для парсера"?

2023-11-15 14:31 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
Я смотрю не туда. Если я подставлю определения парсера, то вот так, наверное

`f :: String -> Maybe (a, String)`

2023-11-15 18:30 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
Я не понимаю

2023-11-16 11:14 UTC, pluralia commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
@qilowoq, у тебя тип внутри парсера `String -> Maybe (a, String)` и `a` -- типовой параметр. Это значит, что финальный тип парсера зависит от того, что ты подставишь вместо `a` -- это и есть функция на типах.

`Functor` может быть реализован только для функции на типах, принимающей 1 тип как аргумент. `Parser` и есть такая функция. Давай писать функцию на типах как `:->`, тогда `f` (о которой мы и рассуждали выше, контекст) можно записать так `a :-> (String -> Maybe (a, String))`

Я не ожидала от тебя именно такого объяснения, но что-то похожее своими словами / своей нотацией. Надеюсь, тебе стало сейчас понятнее

2023-11-16 11:15 UTC, pluralia commented
👍

2023-11-16 11:15 UTC, closed without merging

2023-11-16 11:30 UTC, pluralia commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
На почте вижу другие твои комментарии, но не здесь -- ты их удалил?

Вот это и есть верный по смыслу ответ `f :: String -> Maybe (a, String)`, и ты его указал :)

2023-11-16 13:59 UTC, qilowoq commented on hw6/src/MyLib.hs
> +fmap4 :: Applicative f => (a -> b -> c -> d -> e) -> f a -> f b -> f c -> f d -> f e
Удалил. Я не был уверен в том, что написал. Спасибо за объяснение :->