Hw6_Pushkina_Olga
pluralia/fp-fall-2023 pull request #35
Opened 2023-11-09 10:30 UTC by forestcream

hlint и вонингов нет

2023-11-12 13:26 UTC, pluralia requested changes
-0,25 за ворнинг
-1,5 за 3с

2023-11-13 07:41 UTC, forestcream commented on hw6/src/Parser.hs
> +{-# LANGUAGE InstanceSigs, FlexibleInstances #-}
Я его сейчас убрала, и оно и не нужно. Сначала, когда делала, показалось, что без него выдается ошибка, но видно достаточно только InstanceSigs

2023-11-13 07:46 UTC, forestcream commented on hw6/src/MyLib.hs
> +  where
```
floatP :: Parser Float
floatP = read . concat <$> sequenceA [intPart, pure ".", fracPart]
  where
    intPart :: Parser [Char]
    intPart = some (satisfyP isDigit)

    fracPart :: Parser[Char]
    fracPart = satisfyP (== ',') *> (concatMap show <$> digitsP)
```

2023-11-13 07:46 UTC, forestcream commented on hw6/src/MyLib.hs
> +    fracPart = satisfyP (== ',') *> (concatMap show <$> digitsP)
```
floatP :: Parser Float
floatP = read . concat <$> sequenceA [intPart, pure ".", fracPart]
  where
    intPart :: Parser [Char]
    intPart = some (satisfyP isDigit)

    fracPart :: Parser[Char]
    fracPart = satisfyP (== ',') *> intPart
```

2023-11-13 07:58 UTC, forestcream commented on hw6/src/MyLib.hs
> +floatP = read . concat <$> sequenceA [intPart, pure ".", fracPart]
`sequenceA` собирает значения от парсеров, которые они распарсили, затем объединям все их результаты в один с помощью `concat`. То есть у нас получается, что все парсеры типа `Parser [Char]`. Затем мы их объединяем в список и получаем тип `[Parser [Char]]`, а затем `sequenceA ` делает из них тип `Parser [[Char]]`. Затем `concat`  объединяет все в одну строку и получается просто `[Char]` и из-за `<$>` оно остается `Parser [Char]`. А потом все читаем с помощью `read`

2023-11-13 08:20 UTC, forestcream commented on hw6/src/MyLib.hs
> +-- что мы выполняем друг за другом операции, оставаясь в одном контексте
Ощущение, что в `f` и подставится `Parser`

2023-11-13 08:24 UTC, forestcream commented on hw6/src/MyLib.hs
> +commaP = fmap pure (satisfyP (== ','))
Чтобы совпадали типы, у нас `satisfyP (== ',')` парсит `Char`, а мне нужна строка в итоге

2023-11-13 08:26 UTC, forestcream commented on hw6/src/MyLib.hs
> +commaSep :: Parser String
```
commaSep :: Parser String
commaSep = spaceP *> fmap pure (satisfyP (== ',')) <* spaceP
```

2023-11-13 08:29 UTC, forestcream commented on hw6/src/MyLib.hs
> +sepBy p sep = sepBy' p sep <|> pure []
```
sepBy :: Parser a -> Parser b -> Parser [a]
sepBy p sep = ((:) <$> p <*> many (sep *> p)) <|> pure []
```

2023-11-13 08:33 UTC, forestcream commented on hw6/src/MyLib.hs
> +intValueP = IntValue <$> intP
Я не очень поняла вопрос. Нам же нужно отдельно реализовать `intValueP`, или все ` IntValue`, ` FloatValue`, `StringValue` объединить в один парсер?

2023-11-13 13:27 UTC, pluralia commented on hw6/src/MyLib.hs
> +-- что мы выполняем друг за другом операции, оставаясь в одном контексте
Верно! А что соответствует `f` внутри `Parser`? Какие типы?

2023-11-13 13:27 UTC, pluralia commented on prac.hs
> +collatz :: Integer -> Maybe Integer
Где используется эта функция?

2023-11-13 13:27 UTC, pluralia commented on prac.hs
> +collatz :: Integer -> Maybe Integer
Где используется эта функция?

2023-11-13 13:27 UTC, pluralia commented on hw6/src/MyLib.hs
> +intValueP = IntValue <$> intP
Тебе не нужны отдельно парсеры `floatValueP`, `stringValueP`, ... -- они все в итоге парсят один и тот же тип `Value`, просто каждый парсит свой конструктор. Лучше иметь один парсер `valueP`, который содержит парсинг значений для всех конструкторов

2023-11-13 13:27 UTC, pluralia commented on hw6/src/MyLib.hs
> +floatP = read . concat <$> sequenceA [intPart, pure ".", fracPart]
Хорошо 👍 Напомню только, что `[Char]` -- это `String`

2023-11-13 14:01 UTC, forestcream commented on prac.hs
> +collatz :: Integer -> Maybe Integer
Ой, это случайно не добавила гит игнор, проверяла как эта штука работает просто

2023-11-13 14:32 UTC, forestcream commented on hw6/src/MyLib.hs
> +intValueP = IntValue <$> intP
```
valueP :: Parser Value
valueP = (FloatValue <$> floatP) <|> (IntValue <$> intP) <|>  (StringValue <$> symbolsP)
```

2023-11-13 15:53 UTC, pluralia commented on hw6/src/MyLib.hs
> +intValueP = IntValue <$> intP
Верно! Скобки можно убрать

2023-11-13 15:57 UTC, pluralia commented
Остался [этот](https://github.com/pluralia/fp-fall-2023/pull/35#discussion_r1391104144) вопрос. Ответишь на него и зачту домашку)

2023-11-13 16:16 UTC, forestcream commented on hw6/src/MyLib.hs
> +-- что мы выполняем друг за другом операции, оставаясь в одном контексте
`f` - это функция, которая принимает входные данные и возвращает распарсенное. То есть мы берем `a, b, c, d`, парсим их, `e` - это результат, а `f a, f b, f c, f d` получается являются парсерами данных, так как `f` у нас `Parser`

2023-11-13 17:35 UTC, forestcream commented on hw6/src/MyLib.hs
> +-- что мы выполняем друг за другом операции, оставаясь в одном контексте
Получается, что `f` в контексте `Parser`, то есть в контексте, в котором происходит парсинг. А `a` - это тип значения, который возвращается после парсинга, как и `b`

2023-11-13 21:43 UTC, pluralia commented
👍

2023-11-13 21:43 UTC, closed without merging