HW6 Kostina
pluralia/fp-fall-2023 pull request #40
Opened 2023-11-09 21:00 UTC by jmkostina

2023-11-12 13:23 UTC, pluralia requested changes
-1,5 за 3с
-1 за 4d

-0,25 за 1d, если не исправишь до дедлайна HW 7

2023-11-12 13:23 UTC, pluralia commented on src/MyLib.hs
> +rowP colnames sep = Row . fromList <$> (zip colnames <$> abstractRowP sep valueP)
Можно убрать первый <$>

2023-11-12 13:23 UTC, pluralia commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
Давай смотреть.  Ты получила "No instance for (Eq Row) arising from a use of ‘shouldBe’"? Возникают идеи, что с этим делать?

2023-11-12 13:23 UTC, pluralia commented on test/TestSpec.hs
> +      -- у меня какие-то странные числа выдает, не ожидаемые значения, допускаю, что это округления и точность, но не понятно почему отдельно работает
Это относительно нормально при вычислении чисел с плавающей точкой. Тебе нужно исправить тесты так, чтобы сравнение было неточным, но с некоторой окрестностью. Например:
```haskell
(\(x, s) -> (abs (x - 39.74) < 1e-5, s)) <$> runParser sumMultFloatsP "3,14 + 36,6"
  `shouldBe` (Just (True, "")   :: Maybe (Bool, String))

```

2023-11-15 10:42 UTC, jmkostina commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
слова `No instance` явно намекают, что я не описала поведение чего-то, только я не понимаю чего. вроде тип я обернула в `Maybe`, и тогда ошибки быть не должно

2023-11-15 10:42 UTC, jmkostina commented on test/TestSpec.hs
> +      -- у меня какие-то странные числа выдает, не ожидаемые значения, допускаю, что это округления и точность, но не понятно почему отдельно работает
тогда тесты:
```haskell
(\(x, s) -> (abs (x - 39.74) < 1e-5, s)) <$> runParser sumMultFloatsP "3,14 + 36,6"
  `shouldBe` (Just (True, "")   :: Maybe (Bool, String))
(\(x, s) -> (abs (x - 114.924) < 1e-5, s)) <$> runParser sumMultFloatsP "3,14 * 36,6"
  `shouldBe` (Just (True, "")   :: Maybe (Bool, String))
```

2023-11-15 10:42 UTC, jmkostina commented on src/MyLib.hs
> +rowP colnames sep = Row . fromList <$> (zip colnames <$> abstractRowP sep valueP)
```haskell
rowP :: [String] -> Char -> Parser Row
rowP colnames sep = Row . fromList (zip colnames <$> abstractRowP sep valueP)
```

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +    intValueP :: Parser Value
а почему нас здесь устраивает запись в строку , а не отдельными функциями?
```haskell
valueP :: Parser Value
valueP = FloatValue <$> floatP <|> IntValue <$> intP <|>  StringValue <$> symbolsP
```

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +{- так как мой парсер не работает, закоменчено
из-за того, что не работает `stringP ` из 1.d

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +В общем случае это обертки (типа Arrow из прошлой домашки), но у наших парсеров обертка Maybe, а в fmap - это функция f, которая задается свободно
подставляется то, что будем парсить, у нас там три типа (`simpleExprP`, `Expr`, `Int`)

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +      toFloat whole fract = fromIntegral whole + (fromIntegral fract / (10 ^ length (show fract)))
```haskell
floatP :: Parser Float
floatP = toFloat
  <$> intP
  <* satisfyP (== ',')
  <*> intP
    where
      toFloat :: Int -> Int -> Float
      toFloat integral fract = fromIntegral integral + (fromIntegral fract / (10 ^ length (show fract)))
```

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +               | otherwise = (:) <$> satisfyP (== pattern) <*> stringP
`stringP` нужно вызывать на остатки парсера `str`,  а на входе `input` satisfyP? 
а я делала наоборот из-за того, что не поняла, что такое `str`
```haskell
stringP str = Parser go
  where
    go :: String -> Maybe (String, String)
    go pattern | input == "" = Nothing
               | otherwise = (:) <$> satisfyP (== input) <*> stringP str
```

2023-11-15 10:43 UTC, jmkostina commented on src/MyLib.hs
> +stringP str = Parser go
значит, у меня не правильно обозначены входы
```haskell
stringP str = Parser go
```

2023-11-15 13:03 UTC, pluralia commented on src/MyLib.hs
> +               | otherwise = (:) <$> satisfyP (== pattern) <*> stringP
Ты запускала эту функцию?

2023-11-15 13:05 UTC, pluralia commented on src/MyLib.hs
> +В общем случае это обертки (типа Arrow из прошлой домашки), но у наших парсеров обертка Maybe, а в fmap - это функция f, которая задается свободно
1) `fmap :: (a -> b) -> f a -> f b`
2) `fmap :: (a -> b) -> Parser a -> Parser b`
3) `newtype Parser a = Parser { runParser :: String -> Maybe (a, String) }`

Что подставится в `f` из п.1, когда ты используешь `fmap` для парсера

2023-11-15 13:11 UTC, pluralia commented on src/MyLib.hs
> +    intValueP :: Parser Value
1) Лучше не в одну строку, а отформатировать на разных, разбив по <|>
2) Тебе не нужны отдельно парсеры floatValueP, stringValueP, ... -- они все в итоге парсят один и тот же тип Value, просто каждый парсит свой конструктор. Лучше иметь один парсер valueP, который содержит парсинг значений для всех конструкторов.
3) Разбивать на отдельные парсеры бывает нужно, если парсеры сложные, но это не тот случай -- здесь разбиение только ухудшает читаемость

2023-11-15 13:11 UTC, pluralia commented on src/MyLib.hs
> +rowP colnames sep = Row . fromList <$> (zip colnames <$> abstractRowP sep valueP)
Ты запускала этот код?

2023-11-15 13:12 UTC, pluralia commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
"No instance for (Eq Row)"
Что такое Eq Row?

2023-11-15 13:13 UTC, pluralia commented
Запускай код перед отправкой на проверку, пожалуйста. Сделай коммит

2023-11-15 14:21 UTC, jmkostina commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
Я понимаю, что это класс `Eq` (равенство) для нашего типа `Row`. Он у нас описан как
```haskell
newtype Row = Row (Map String Value)
  deriving (Show)
```
есть предположение, что это из-за того, что я передаю разделитель, но мне кажется, что это не верно, потому что у нас он в функции, а не в новом типе данных

2023-11-15 14:21 UTC, jmkostina commented on src/MyLib.hs
> +rowP colnames sep = Row . fromList <$> (zip colnames <$> abstractRowP sep valueP)
нет, это было предположение. 
я запустила, этот вариант не работает
нужно
```haskell
rowP :: [String] -> Char -> Parser Row
rowP colnames sep = Row . fromList . zip colnames <$> abstractRowP sep valueP
```

2023-11-15 14:21 UTC, jmkostina commented on src/MyLib.hs
> +В общем случае это обертки (типа Arrow из прошлой домашки), но у наших парсеров обертка Maybe, а в fmap - это функция f, которая задается свободно
будет `fmap :: (a -> b) -> Parser a -> Parser b =  fmap :: (a -> b) -> Maybe (a, String) -> Maybe (b, String)`?

2023-11-15 14:22 UTC, jmkostina commented on src/MyLib.hs
> +               | otherwise = (:) <$> satisfyP (== pattern) <*> stringP
нет, это было предположение. 
я запустила (поменяла `go pattern` на `go input`, это опечатка была). функция не работает, так как у меня ошибка в типах
но тогда я точно не понимаю, что не так

2023-11-15 19:08 UTC, jmkostina commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
UPD!
я туплю. 
нужно
```haskell
newtype Row = Row (Map String Value)
  deriving (Show, Eq)
```
тогда все работает

2023-11-16 22:59 UTC, pluralia commented on src/MyLib.hs
> +В общем случае это обертки (типа Arrow из прошлой домашки), но у наших парсеров обертка Maybe, а в fmap - это функция f, которая задается свободно
Почти. `Parser a` == `Parser (String -> Maybe (a, String))`. Видишь у себя проблему?

2023-11-16 23:00 UTC, pluralia commented on test/TestSpec.hs
> +{- не понимаю ошибку этого теста
Верно! Молодец, что разобралась :)

2023-11-16 23:04 UTC, pluralia commented on src/MyLib.hs
> +               | otherwise = (:) <$> satisfyP (== pattern) <*> stringP
За задание -0,25, но давай все же разберемся

2023-11-16 23:06 UTC, pluralia commented on src/MyLib.hs
> +    go input | input == "" = Nothing
Верно ли такое поведение на пустом входном потоке? Что, если паттерн `str`, который нам пришел, это пустая строка?

2023-11-16 23:13 UTC, pluralia commented on src/MyLib.hs
> +             | otherwise = (:) <$> satisfyP (== input) <*> stringP str
> satisfyP (== input)
1) Почему `input`? На какой строке запускается этот парсер?
2) `satisfyP` ожидает предикат на char `Char -> Bool`, а какой тип у `(== input)`?

> stringP str

Почему str?

2023-11-16 23:17 UTC, pluralia commented on src/MyLib.hs
> +             | otherwise = (:) <$> satisfyP (== input) <*> stringP str
Одно из возможных решений выглядит так. Посмотри на него и задай вопросы, если что-то непонятно. Если решишь сама до него дойти, то я поддержу тебя и буду давать наводящие вопросы, пока не получишь решение
|
|
|
|
|
|
|
|
|
|
|
|
```haskell
stringP :: String -> Parser String
stringP []       = pure ""
stringP (x : xs) = (:) <$> satisfyP (== x) <*> stringP xs
```

2023-11-17 21:33 UTC, closed without merging

2023-11-17 21:33 UTC, pluralia commented
@jmkostina, закрываю PR. Если будет желание добить `stringP` -- пиши