HW6_ShchukinIA [delayed]
pluralia/fp-fall-2023 pull request #41
Opened 2023-11-11 17:39 UTC by paiksonn

No warnings or Hlint hints

2023-11-12 13:09 UTC, pluralia requested changes
Молодец, что сдал домашку все равно!

-0,75 -- 2b
-0,75 -- 3с
---
-1,5

2023-11-16 22:51 UTC, pluralia commented on lib/MyLib.hs
> +-- Реализации действительно очень похожи, и в целом отличаются только моментом, что
Я немного про другое

- `fmap :: (a -> b) -> f a -> f b`
- `fmap :: (a -> b) -> Parser a -> Parser b`
- `newtype Parser a = Parser { runParser :: String -> Maybe (a, String) }`

1. `f` -- функция на типах, она ждет тип на вход, поэтому запись `f :: a -> (b -> Maybe (b, String))` некорректна
2. `f == Parser`
3. Если подставить определение парсера вместо `Parser` в п.2, то какая функция на типах получится?

2023-11-16 22:52 UTC, pluralia commented on lib/MyLib.hs
> +          | otherwise   = error "ERRORR"
Верно

2023-11-16 22:52 UTC, pluralia commented on lib/MyLib.hs
> +listP elementP = inBetweenP "[" "]" (sepByP (spaceP *> elementP <* spaceP) (stringP ","))
Список может быть пустым, но да, явно в задании это не было указано

2023-11-16 22:57 UTC, pluralia commented
Нужно подумать над [этим](https://github.com/pluralia/fp-fall-2023/pull/41#discussion_r1396463738) вопросом -- зачту домашку, когда дашь ответ. Давай договоримся разобраться с этим за завтрашний день: вопрос несложный, подсказку я уже дала

2023-11-17 06:16 UTC, paiksonn commented on lib/MyLib.hs
> +-- Реализации действительно очень похожи, и в целом отличаются только моментом, что
Получится так:
` f :: String -> Maybe (a, String)`

2023-11-17 12:39 UTC, pluralia commented
👍

2023-11-17 12:39 UTC, closed without merging