HW7_Dmitriev
pluralia/fp-fall-2023 pull request #43
Opened 2023-11-14 18:47 UTC by qilowoq

2023-11-21 00:32 UTC, pluralia requested changes
-0,25 -- нет тестов для 1 задания

Чуть позже добавлю больше комментариев по парсеру PDB

2023-11-21 00:32 UTC, pluralia commented on hw7/src/MyLib.hs
> +count 0 = pure []
Альтернативное определение. Тебе не нужна рекурсия
```haskell
count :: Int -> Parser String
count n = Parser $ \s -> if length s < n then Nothing else Just (splitAt n s)
```

2023-11-21 00:32 UTC, pluralia commented on hw7/src/MyLib.hs
> +    f s = case runParser aP s of
Забыл указать тип функции

2023-11-21 00:32 UTC, pluralia commented on hw7/src/MyLib.hs
> +        Just (b, _) -> Just (b, rest)
Не припомню альтернатив, но замечу в этой строчке один эффект.

Что происходит здесь:
1) Применяешь 1 парсер; он обязан возвращать строку
2) На этой строке запускаешь 2 парсер; при этом ты игнорируешь тот факт. что этот 2 парсер мог распарсить только часть строки

Пример: `runParser (floatP <.> count 5) "12.3a"` возвращает `Just (12.3,"")`. 

Это то, чего ты хочешь? Почему?

2023-11-21 00:32 UTC, pluralia commented on hw7/src/MyLib.hs
> +atomP = do
У тебя монадный парсер получился, а мы учились писать аппликативные. Но на зачет задания это не повлияет

2023-11-21 12:29 UTC, qilowoq commented on hw7/src/MyLib.hs
> +        Just (b, _) -> Just (b, rest)
Да именно этого. Тк формат PDB разделяет поля не пробелами или какими-то знаками, а каждому полю отделяется определенное количество символов. Поэтому мне все равно распарсит он его или нет (но вообще должен).

2023-11-21 12:51 UTC, qilowoq commented on hw7/src/MyLib.hs
> +fastaListP = many fastaP
Как отработает парсер, если комментарий встретится между описанием и последовательностью?
неправильно будет рабатать. я исправил

Как отработает парсер, если придет 2 описания подряд?
он сломается. не думаю, что это нормальный fasta формат

2023-11-21 16:17 UTC, pluralia requested changes
@qilowoq, добавила больше комментов по PDB парсеру и посмотрела твои текущие исправления

2023-11-21 16:17 UTC, pluralia commented on hw7/src/MyLib.hs
> +--  = (k a >>= h) <> (as >>= (\x -> k x >>= h)) = тут, наверное, надо сказать про индукцию
Да

2023-11-24 22:55 UTC, pluralia commented
👍

2023-11-24 22:55 UTC, closed without merging