Hw7_Shishkin
pluralia/fp-fall-2023 pull request #44
Opened 2023-11-14 20:04 UTC by Alexvsalexvsalex

2023-11-21 20:55 UTC, pluralia requested changes
Все хорошо -- в основном попридиралась к названиям функций :)

2023-11-21 20:55 UTC, pluralia commented on src/MyLib.hs
> +stringP = foldr (\c acc -> (:) <$> satisfyP (== c) <*> acc) (pure [])
Можно так
```haskell
stringP :: String -> Parser String
stringP = traverse (satisfyP . (==))
```

2023-11-21 20:55 UTC, pluralia commented on src/MyLib.hs
> +takeInLineP 0 = pure []
Можно так
```haskell
count :: Int -> Parser String
count n = Parser $ \s -> if length s < n then Nothing else Just (splitAt n s)
```

2023-11-21 20:55 UTC, pluralia commented on src/MyLib.hs
> +  <* stringP " "
Почему не `oneSpaceP`?

2023-11-22 19:10 UTC, Alexvsalexvsalex commented on src/MyLib.hs
> +  <* stringP " "
Не признал)

2023-11-22 19:16 UTC, Alexvsalexvsalex commented on src/MyLib.hs
> +takeInLineP 0 = pure []
Вообще да, но мне еще хотелось, что бы символы не были line separator.
Я потом использую spaceP, который пользуется isSpace, кушающий '\n'. Так что явно пришлось бы еще где-то что-то править, иначе корректно попарсятся атома, написанные на несколько строк.

2023-11-22 19:17 UTC, Alexvsalexvsalex commented
Поправил

2023-11-23 21:57 UTC, pluralia commented
👍

2023-11-23 21:57 UTC, closed without merging