HW7 ManasyanAL
pluralia/fp-fall-2023 pull request #47
Opened 2023-11-16 11:48 UTC by Artem9999999999999999999999

2023-11-21 00:35 UTC, pluralia requested changes
-0,25 -- нет тестов для 1 задания

Чуть позже добавлю больше комментариев по парсеру PDB

2023-11-21 21:25 UTC, pluralia requested changes
@Artem9999999999999999999999, добавила комменты по PDB парсеру

2023-11-21 21:25 UTC, pluralia commented on hw7/src/MyLib.hs
> +  <*> (satisfyP (== ' ') Data.Functor.$> ' ')                  -- atomICode - это hlint поправила
`Data.Functor.$>` -> `$>`: можно не полный путь

2023-11-21 21:25 UTC, pluralia commented on hw7/src/MyLib.hs
> +string = traverse (\c -> satisfyP (== c))
`stringP` -- или другое имя. `string` может запутать

2023-11-21 21:25 UTC, pluralia commented on hw7/src/MyLib.hs
> +modelP =
Запускал ли ты этот парсер? Что выдает?

2023-11-21 21:25 UTC, pluralia commented on hw7/src/MyLib.hs
> +pdbP = PDB <$> many modelP
Файл не парсится полностью. Что остается не распарсенным?

2023-11-25 00:20 UTC, pluralia commented
@Artem9999999999999999999999 , по поводу твоего вопроса на лекции
`testParserIO` вернет `True` даже, если распарсилась только часть входа. Вот альтернативная функция для тестов, которая проверяет, что парсер распарсил весь вход полностью
```haskell
testFullyParsedIO :: FilePath -> Parser a -> IO Bool
testFullyParsedIO filePath parser = maybe False (null . snd) <$> testIO filePath parser
```

2023-11-25 12:15 UTC, Artem9999999999999999999999 commented
Сделал коммит со всеми исправлениями. Добавил альтернативную функцию в файл с тестами

2023-11-25 12:34 UTC, Artem9999999999999999999999 commented on hw7/src/MyLib.hs
> +fastaP = Fasta
Мне кажется, что это про правило хорошего тона, потому что так повышается читабельность кода (все вишенки в основной функции). В целом, pdb очень вредный формат и реальные файлы всегда найдут где уронить твой код, поэтому так удобнее вносить вносить правки в свой код.

2023-11-26 23:43 UTC, pluralia commented
👍

2023-11-26 23:43 UTC, closed without merging