HW7_ShchukinIA
pluralia/fp-fall-2023 pull request #49
Opened 2023-11-16 15:39 UTC by paiksonn

2023-11-21 00:36 UTC, pluralia requested changes
-0,25 -- нет тестов для 1 задания

Добавь, пожалуйста, формулировки законов -- тяжело читать, когда док-ва нескольких законов перемешиваются

Чуть позже добавлю больше комментариев по парсеру PDB

2023-11-21 23:59 UTC, pluralia requested changes
@paiksonn, добавила комментарии по PDB парсеру: 1 проблему нашла за тебя и рассказала как их искать. Верю в тебя, что все исправишь ;)

2023-11-21 23:59 UTC, pluralia commented on lib/MyLib.hs
> +  cchainId <-  symbolChar <* space1
Почему `symbolChar`, а не `L.charLiteral`? В чем проблема использования `symbolChar`?

2023-11-21 23:59 UTC, pluralia commented on lib/MyLib.hs
> +  zzCoord <- L.float <* space1
Следующая проблема здесь. Предлагаю тебе отддебажить остальное самостоятельно. Ты можешь комментировать куски и смотреть на выдачу парсера вот так:
```haskell
data PDBAtom = PDBAtom
  { atomType :: String
  , atomNumber :: Int
  , atomName :: String
  , aminoAcid :: String
  , chainId :: Char
  , residueNumber :: Int
  , xCoord :: Double
  , yCoord :: Double
  , zCoord :: Double
  -- , occupancy :: Double
  -- , temperatureFactor :: Double
  -- , element :: String
  } deriving (Show)

atomParser :: Parsec Void String PDBAtom
atomParser = do
  aatomType <- string "ATOM" <* space1
  aatomNumber <- L.decimal <* space1
  aatomName <-  Text.Megaparsec.some alphaNumChar <* space1
  aaminoAcid <- Text.Megaparsec.some alphaNumChar <* space1
  cchainId <-  L.charLiteral <* space1
  rresidueNumber <- L.decimal <* space1
  xxCoord <- L.float <* space1
  yyCoord <- L.float <* space1
  zzCoord <- L.float <* space1
  -- ooccupancy <- L.float <* space1
  -- ttemperatureFactor <- L.float <* space1
  -- eelement <- Text.Megaparsec.some (alphaNumChar <|> symbolChar) <* newline
  return $ PDBAtom  
    aatomType
    aatomNumber
    aatomName
    aaminoAcid
    cchainId
    rresidueNumber
    xxCoord
    yyCoord
    zzCoord
    -- ooccupancy
    -- ttemperatureFactor
    -- eelement
```

Теперь запустим:
```
ghci > testParserIO' "only_atoms_small.pdb" atomParser
```

Получим:
```
Left "ParseErrorBundle {bundleErrors = TrivialError 47 (Just (Tokens ('-' :| \"\"))) (fromList [Label ('d' :| \"igit\"),Label ('w' :| \"hite space\")]) :| [], bundlePosState = PosState {pstateInput = \"ATOM      1  N   ARG I   1       1.046  16.244 -11.759  1.00 33.34           N1+\", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = \"\", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = \"\"}}"
```

`TrivialError 47 (Just (Tokens ('-' :| \"\")))` значит, что нам пришел неожиданный токен `-`.

Заглянем в `only_atoms_small.pdb` и увидем `-11.759` -- значит, мы не сумели распарсить отрицательный float. Как исправить?

2023-11-24 07:39 UTC, paiksonn commented on lib/Parser.hs
> +      case Parser.runParser p input of
Да, поправил, осталось при копировании из MyLib.hs

2023-11-24 07:41 UTC, paiksonn commented on lib/MyLib.hs
> +-- 5.c Either (1 балл)
Да, добавил

2023-11-24 08:37 UTC, paiksonn commented on lib/MyLib.hs
> +-- -- Проверка для Nothing' <*> Just' g <*> Just' a
исправил в новой версии

2023-11-24 08:37 UTC, paiksonn commented on lib/MyLib.hs
> +-- rightIdentity m = (m >>= Just') == m
исправил в новой версии

2023-11-24 08:37 UTC, paiksonn commented on lib/MyLib.hs
> +-- associativity m f g = ((m >>= f) >>= g) == (m >>= (\x -> f x >>= g))
исправил в новой версии

2023-11-24 08:54 UTC, paiksonn commented on lib/MyLib.hs
> +Я не совсем понял, это чисто теоретический вопрос или нужно прям реализовать код, поэтому
Понял, хорошо, реализовал все в новой версии

2023-11-24 09:31 UTC, paiksonn commented on lib/MyLib.hs
> +{-# LANGUAGE FlexibleInstances, InstanceSigs #-}
FlexibleInstances тут лишнее, а вот без InstanceSigs ничего не работает и летит ошибка `Illegal type signature in instance declaration`, которую сам компилятор предлагает исправить `Suggested fix: Perhaps you intended to use InstanceSigs`

2023-11-24 09:41 UTC, paiksonn commented on test/TestSpec.hs
> +{-# LANGUAGE FlexibleInstances #-}
Не нужен, все работает и без него 
Я просто всегда в начале работы по всем файлам копирую вставляю эти прагмы чтобы сразу часть ошибок убрать

2023-11-24 10:55 UTC, paiksonn commented
Заапдейтил все изменения, кроме тех, что касаются парсеров FASTA & PDB, их я сделаю отдельно

2023-11-24 11:54 UTC, paiksonn commented on lib/MyLib.hs
> +fastaP = do
Я думал, что парсер комментариев - это опциональная штука и можно не писать(
видимо я не так понял
все допилю, исправлю и залью

2023-11-25 00:04 UTC, pluralia commented
> Отдебажить через ghci я не могу (в телеграмме еще писал про это, мы тогда сошлись на том, что я буду эту дз делать только через cabal), поэтому и посмотреть, на каком символе теперь падает парсер я не могу

Также в ТГ я писала альтернативный вариант: ты можешь создать в своем проекте еще один модуль (на ряду с lib и test), в котором будет `main :: IO ()` -- это будет замечательно запускаться с cabal. Попробуй, пожалуйста, этот вариант

2023-11-25 07:02 UTC, paiksonn commented
> ты можешь создать в своем проекте еще один модуль (на ряду с lib и test), в котором будет `main :: IO ()` -- это будет замечательно запускаться с cabal. Попробуй, пожалуйста, этот вариант

Да, спасибо, я забыл про этот вариант, сейчас попробовал и он заработал
Оказалось, что не парсится значок '+' в самом конце строки, сейчас исправлю и залью новый код с мейном вместе

2023-11-26 23:45 UTC, pluralia commented on hw7.cabal
> +executable hw8
hw8?

2023-11-27 00:05 UTC, pluralia commented
У тебя битый парсер для Fasta, поэтому снижаю на 1 балл
<img width="994" alt="Screenshot 2023-11-27 at 01 01 26" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/f4a3007d-6e93-436e-895c-08063b0a364a">

Молодец, что разобрался с megaparsec! Накину за это 0,5 балла 👍

2023-11-27 00:05 UTC, closed without merging