HW7
pluralia/fp-fall-2023 pull request #51
Opened 2023-11-16 19:01 UTC by jmkostina

2023-11-21 00:38 UTC, pluralia requested changes
-0,5 -- нет 4
-2,75 -- нет 5
UPD: может быть -0,25 за 6 и -1,75 за 3, если не доделаешь

Чуть позже добавлю больше комментариев по парсеру PDB
UPD: добавила

2023-11-22 00:22 UTC, pluralia requested changes
@jmkostina, парсер PDB -- копипаста, и половина домашки не сделана, да и целом от последних твоих домашек ощущение, что материал усваивается в недостаточной степени. Дальше материал пойдет на усложнение, поэтому важно закрыть пробелы. Давай решим проблему с закрытием курса превентивно:
1) Сдалай 6 задание и исправь парсер PDB, чтобы добрать хоть немного баллов
2) Посмотри программу курса [здесь](https://github.com/pluralia/fp-fall-2023/tree/ae3bc7e69b0cc9f6189ae2c0ffa0443e876ce16c#program) и напиши мне, что непонятно -- я объясню либо в текстом виде, либо устроим персональную консультацию

2023-11-22 00:22 UTC, pluralia commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
Зачем?

2023-11-22 00:22 UTC, pluralia commented on src/MyLib.hs
> +-- 3. Парсер PDB (3,5 балла)
Копипаста. Причем битая -- даже не исправила проблемы исходника.

У тебя слишком мало баллов за эту домашку выходит, поэтому согласна поставить тебе 1,75 за это задание, если исправишь все проблемы (но, пожалуйста, сделай это самостоятельно!)

2023-11-22 09:03 UTC, jmkostina commented on src/MyLib.hs
> +{-# LANGUAGE InstanceSigs #-}
cabal не собирался без прагмы. Но она нужна для задания 5, которое я не делала

2023-11-22 09:03 UTC, jmkostina commented on src/MyLib.hs
> +-- 6. Что называется "стрелкой Клейсли"? (0,25 балла)
эта штука, которая принимает какое-то значение и возвращает его, обернутое во что-то (в монаду, например): `a -> m a`, где `m` - это какая-то функция `a->b`

2023-11-23 23:08 UTC, pluralia commented on src/MyLib.hs
> +-- 6. Что называется "стрелкой Клейсли"? (0,25 балла)
> a -> m a

В частном случае да, но в общем -- это `a -> m b`

> m - это какая-то функция a->b
1) `m` здесь -- монада (например, список, `Maybe` `Either`, `Reader`), но не функция
2) сама стрелка Клейсли -- это функция, которая берет на вход значение типа `a` и модифицирует его в значение типа `b`, а затем заворачивает в монаду `m`

Понятно ли это объяснение?

2023-12-01 00:23 UTC, pluralia commented
@jmkostina, закрываю этот PR -- дальнейшие обсуждения продолжим в новом PR

2023-12-01 00:23 UTC, closed without merging