HW7_Shishkina
pluralia/fp-fall-2023 pull request #52
Opened 2023-11-16 20:21 UTC by SophiaLaz

2023-11-17 18:49 UTC, pluralia reviewed
@SophiaLaz, нет `.cabal`

2023-11-21 00:50 UTC, pluralia requested changes
Тесты классные -- молодец!

Чуть позже добавлю больше комментариев по парсеру PDB

2023-11-21 00:50 UTC, pluralia commented on src/MyLib.hs
> +        seqP = foldr (<>) [] <$> some (some (satisfyP (`elem` ('*' : ['A'..'Z']))) <* many newLineP)
На какую функцию можно заменить `foldr (<>) []`?

2023-11-21 00:50 UTC, pluralia commented on src/MyLib.hs
> +        descriptP =    many (satisfyP (==';') *> many (satisfyP (/='\n')) *> newLineP)
Этот парсер парсит описание полностью, но в результат складывает только первое слово

2023-11-21 00:50 UTC, pluralia commented on src/MyLib.hs
> +fastaListP = many $ Fasta <$> descriptP <*> seqP
Падает на тесте
```
>MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken
MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA
DIDGDGQVNYEEFVQMMTAK*
;wklejhrjk

>gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus maximus]
LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGTNLV
EWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFHPYYTIKDFLG
LLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLALFLSIVIL
GLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGX
IENY
```

2023-11-22 14:56 UTC, SophiaLaz commented on src/MyLib.hs
> +fastaListP = many $ Fasta <$> descriptP <*> seqP
> чем лучше парсинг разделителей в основном парсере?

Можно вставлять в любое место, где эти разделители встречаются) Ну и как всегда, когда парсеры раскиданы на разные функции, это легче дебажить

Поправила, теперь на тесте не падает

2023-11-22 15:01 UTC, SophiaLaz commented on src/MyLib.hs
> +        descriptP =    many (satisfyP (==';') *> many (satisfyP (/='\n')) *> newLineP)
Вынесла

2023-11-22 15:01 UTC, SophiaLaz commented on src/MyLib.hs
> +        seqP = foldr (<>) [] <$> some (some (satisfyP (`elem` ('*' : ['A'..'Z']))) <* many newLineP)
`mconcat`

2023-11-22 15:03 UTC, SophiaLaz commented on src/MyLib.hs
> +        descriptP =    many (satisfyP (==';') *> many (satisfyP (/='\n')) *> newLineP)
Да, я подумала, что нам нужен только идентификатор последовательности, без описания, поэтому и сделала сначала так)

2023-11-23 22:16 UTC, pluralia commented on src/MyLib.hs
> +fastaListP = many $ Fasta <$> descriptP <*> seqP
Верно! [Здесь](https://github.com/pluralia/fp-fall-2023/pull/43#discussion_r1400780829) есть мое объяснение

Ты вынесла в основной парсер комментарии, но пробелы остались: `commentP`, `desriptP` и `seqP` заканчиваются на `many newLineP`. Можно не поправлять)

2023-11-23 22:32 UTC, pluralia commented
Классное док-во законов 👍

2023-11-23 22:32 UTC, closed without merging