Hw7_Pushkina
pluralia/fp-fall-2023 pull request #53
Opened 2023-11-18 19:16 UTC by forestcream

Ворнинги и hlint
Use $>
Found:
  satisfyP (== ';') *> many (satisfyP (/= '\n')) *> pure ()
Why not:
  (satisfyP (== ';') *> many (satisfyP (/= '\n'))) Data.Functor.$> ()
не поменяла, потому что не очень поняла зачем

Orphan instance: instance Monad Parser
To avoid this
    move the instance declaration to the module of the class or of the type, or
    wrap the type with a newtype and declare the instance on the new type.typecheck(-Worphans)
тут я так поняла, что он ругается, чтобы Монад был опеределен в том же файле, что и функтор с аппликативом

2023-11-19 22:42 UTC, pluralia commented
> Use $>
Found:
satisfyP (== ';') *> many (satisfyP (/= '\n')) *> pure ()
Why not:
(satisfyP (== ';') *> many (satisfyP (/= '\n'))) Data.Functor.$> ()
не поменяла, потому что не очень поняла зачем

Эта рекомендация имеет смысл. Чтобы все работало с аппликативным оператором `*>`, тебе приходится поднимать `()` в контекст, а для этого ты вынуждена использовать `pure`. Если бы ты использовала функторовский `$>`, то `pure` был бы не нужен.

> тут я так поняла, что он ругается, чтобы Монад был опеределен в том же файле, что и функтор с аппликативом

Верно! Можешь либо перенести к парсеру, либо так оставить сейчас

2023-11-21 00:56 UTC, pluralia requested changes
Хорошо доказала выполнение законов -- умничка!

Чуть позже добавлю больше комментариев по парсеру PDB

2023-11-21 00:56 UTC, pluralia commented on hw7/src/MyLib.hs
> +fastaP = Fasta <$> descriptionP <* newLineP <*> aminoAcidP <* many commentP
Комментарии могут быть не только в конце. Пример валидного входа
```
;wklejhrjk
>LCBO - Prolactin precursor - Bovine
;wklejhrjk
MDSKGSSQKGSRLLLLLVVSNLLLCQGVVSTPVCPNGPGNCQVSLRDLFDRAVMVSHYIHDLSS
EMFNEFDKRYAQGKGFITMALNSCHTSSLPTPEDKEQAQQTHHEVLMSLILGLLRSWNDPLYHL
VTEVRGMKGAPDAILSRAIEIEEENKRLLEGMEMIFGQVIPGAKETEPYPVWSGLPSLQTKDED
ARYSAFYNLLHCLRRDSSKIDTYLKLLNCRIIYNNNC*
;wklejhrjk
;wklejhrjk
>MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken
MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA
DIDGDGQVNYEEFVQMMTAK*
;wklejhrjk
```

2023-11-21 00:56 UTC, pluralia commented on hw7/src/MyLib.hs
> +descriptionP = satisfyP (== '>') *> many (satisfyP (/= '\n'))
В описании будет хотя бы одна буква

2023-11-21 00:56 UTC, pluralia commented on hw7/src/MyLib.hs
> +aminoAcidP = many (satisfyP (\c -> c /= '>' && c /= ';'))
В последовательности будет хотя бы одна буква

2023-11-22 00:51 UTC, pluralia requested changes
@forestcream, вижу, что тесты на парсер PDB закомментированы и парсер не работает. Оставила пару комментариев насчет первого бага и как дебажить. Пиши, если нужно больше пояснений

2023-11-22 00:51 UTC, pluralia commented on hw7/src/MyLib.hs
> +  }
Нет `deriving Show` -- из-за этого не можешь посмотреть вывод

2023-11-22 00:51 UTC, pluralia commented on hw7/src/MyLib.hs
> +  <*> ((,,) <$> (spaceP *> floatP) <*> (spaceP *> floatP) <*> (spaceP *> floatP)) -- позиция атома в трехмерном пространстве
У тебя здесь баг: парсер `floatP` умеет парсить только положительные числа, а тебе пришло отрицательное

Посмотри, пожалуйста, [комментарий к PR Ивана](https://github.com/pluralia/fp-fall-2023/pull/49/files#r1401346836) о том, как дебажить, и добей парсер :)

2023-11-22 07:48 UTC, forestcream commented on hw7/src/MyLib.hs
> +fastaP = Fasta <$> descriptionP <* newLineP <*> aminoAcidP <* many commentP
```
fastaP :: Parser Fasta
fastaP = Fasta <$> (many commentP *> descriptionP <* many commentP) <*> (aminoAcidP <* many commentP)
```

2023-11-22 07:54 UTC, forestcream commented on hw7/src/MyLib.hs
> +descriptionP = satisfyP (== '>') *> many (satisfyP (/= '\n'))
```
descriptionP :: Parser String
descriptionP = satisfyP (== '>')  *> some (satisfyP isLetter) <* many (satisfyP (/= '\n'))
```

2023-11-22 07:55 UTC, forestcream commented on hw7/src/MyLib.hs
> +aminoAcidP = many (satisfyP (\c -> c /= '>' && c /= ';'))
```
aminoAcidP :: Parser String
aminoAcidP = some (satisfyP isLetter) <* many (satisfyP (\c -> c /= '>' && c /= ';'))
```

2023-11-22 09:08 UTC, forestcream commented on hw7/src/MyLib.hs
> +  <*> ((,,) <$> (spaceP *> floatP) <*> (spaceP *> floatP) <*> (spaceP *> floatP)) -- позиция атома в трехмерном пространстве
у меня сейчас парситься строка ` MODEL        1\nATOM      1  N   ARG I   1       1.046  16.244 -11.759  1.00 33.34           N1+\nENDMDL" ` при входных данных ``` MODEL        1
ATOM      1  N   ARG I   1       1.046  16.244 -11.759  1.00 33.34           N1+
ENDMDL``` и я не очень понимаю в чем проблема - добавила в коммит как сейчас выглядит парсер

2023-11-23 22:43 UTC, pluralia commented on hw7/hw7.cabal
> +    build-depends:    base ^>=4.16.4.0, containers, text, vector, array, megaparsec
Для чего нужен `megaparsec`? Иван использовал эту библиотеку для парсинга, поэтому у него есть эта зависимость

2023-11-23 22:43 UTC, pluralia commented on hw7/src/MyLib.hs
> +descriptionP = satisfyP (== '>') *> many (satisfyP (/= '\n'))
Я подразумевала замену `many` на `some` в `many (satisfyP (/= '\n'))`

2023-11-23 22:44 UTC, pluralia commented on hw7/src/MyLib.hs
> +aminoAcidP = many (satisfyP (\c -> c /= '>' && c /= ';'))
Здесь аналогично

2023-11-23 22:45 UTC, pluralia commented on hw7/hw7.cabal
> +    build-depends:    base ^>=4.16.4.0, containers, text, vector, array, megaparsec
Для чего нужен megaparsec? Иван использовал эту библиотеку для парсинга, поэтому у него есть эта зависимость

2023-11-23 22:48 UTC, pluralia commented
@forestcream, как ты проверяешь результат парсинга? Я запускаю и вижу, что не парсится ничего. Здесь возвращается пустой список, а строка остается полностью нераспарсенной. Как думаешь, в чем может быть проблема?
<img width="559" alt="Screenshot 2023-11-23 at 23 48 06" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/ea0e494a-82c3-48ae-96a3-4b6f7f44cadb">

2023-11-23 23:01 UTC, pluralia commented on hw7/src/MyLib.hs
> +  <*> ((,,) <$> (spaceP *> floatP) <*> (spaceP *> floatP) <*> (spaceP *> floatP)) -- позиция атома в трехмерном пространстве
Текущий баг в реализации `signedFloatP`, а когда исправишь его, следующий баг будет в `elementAndChargeP`. Дальше не смотрела

2023-11-24 07:26 UTC, forestcream commented on hw7/hw7.cabal
> +    build-depends:    base ^>=4.16.4.0, containers, text, vector, array, megaparsec
Я пыталась сделать вывод тестов как у него. У меня не получилось сделать вывод строки целиком, у меня продолжало выводиться просто `True` или `False`

2023-11-24 18:31 UTC, forestcream commented on hw7/src/MyLib.hs
> +descriptionP = satisfyP (== '>') *> many (satisfyP (/= '\n'))
исправила
``` huskell
descriptionP :: Parser String
descriptionP = satisfyP (== '>') *> some (satisfyP (/= '\n'))
```

2023-11-24 18:33 UTC, forestcream commented on hw7/src/MyLib.hs
> +aminoAcidP = many (satisfyP (\c -> c /= '>' && c /= ';'))
и тут тоже
```haskell
aminoAcidP :: Parser String
aminoAcidP = some (satisfyP (\c -> c /= '>' && c /= ';'))
```

2023-11-24 18:34 UTC, forestcream commented on hw7/hw7.cabal
> +    build-depends:    base ^>=4.16.4.0, containers, text, vector, array, megaparsec
я пыталась сделать, чтобы тест выводил не только True или False, но и строку с ее помощью, но у меня не получилось, забыла удалить из зависимости

2023-11-24 18:35 UTC, forestcream commented
Я просто вызываю вот так в тестах
```huskell
it "Fasta test" $ do
        testParserIO "src/test.fasta" fastaListP `shouldReturn` True

    it "PDB test only_atoms.pdb" $ do
        testParserIO "src/only_atoms.pdb" modelP `shouldReturn` True

    it "PDB test atoms_with_bonds.pdb" $ do
        testParserIO "src/atoms_with_bonds.pdb" modelAndBondP `shouldReturn` True
```

2023-11-25 00:07 UTC, pluralia commented on hw7/hw7.cabal
> +    build-depends:    base ^>=4.16.4.0, containers, text, vector, array, megaparsec
`testIO` -- функция, которая как раз позволяет тебе посмотреть на вывод парсера. [Пример](https://private-user-images.githubusercontent.com/15619772/285319593-ea0e494a-82c3-48ae-96a3-4b6f7f44cadb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NzExMTAsIm5iZiI6MTcwMDg3MDgxMCwicGF0aCI6Ii8xNTYxOTc3Mi8yODUzMTk1OTMtZWEwZTQ5NGEtODJjMy00OGFlLTk2YTMtNGI2ZjdmNDRjYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAwMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzM5ZWEzYWY0MjU2ODY1NzRjOGY1YTVkOGRiNWFkYzkzZjliYmU4YTExZjdlOWZhZjFlYzgyNThiMjM4OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cuvYdfuG1q0aNGHmqh2uENTY6IVrV00TxMYC5oTtyTs)

2023-11-25 00:19 UTC, pluralia commented
> Я просто вызываю вот так в тестах

`testParserIO` вернет `True` даже, если распарсилась только часть входа. Смотри на вывод `testIO` ([комментарий](https://github.com/pluralia/fp-fall-2023/pull/53#discussion_r1404683980)). Если тебе вернулась пара, завернутая в `Just`, второй элемент которой -- пустая строка, то парсер отработал верно

Вот тебе альтернативная функция для тестов, которая проверяет, что парсер распарсил весь вход
```haskell
testFullyParsedIO :: FilePath -> Parser a -> IO Bool
testFullyParsedIO filePath parser = maybe False (null . snd) <$> testIO filePath parser
```

> И я не очень понимаю почему строка не парсится

Потому что баг в `signedFloatP` ([комментарий](https://github.com/pluralia/fp-fall-2023/pull/53#discussion_r1403779793))

2023-11-26 23:29 UTC, pluralia commented
Не добила парсеры, поэтому -1 балл за 2 задание и -1,5 за 3 задание. Итого -- 7,5 за домашку

2023-11-26 23:29 UTC, closed without merging