HW8_DmitrievOS
pluralia/fp-fall-2023 pull request #57
Opened 2023-11-23 16:12 UTC by qilowoq

Там много ворнингов. И hlint ругается, но это все специально

2023-11-28 01:15 UTC, pluralia requested changes
Классная идея с Either и тестов много написал -- молодец!

2023-11-29 16:44 UTC, qilowoq commented on hw8/src/MyLib.hs
> +{-# LANGUAGE InstanceSigs, MultiParamTypeClasses, FlexibleInstances, LambdaCase #-}
LambdaCase для того, чтобы юзать `\case`

MultiParamTypeClasses для того, чтобы определять классы типов с несколькими параметрами.  

`instance (Monoid w) => MonadWriter w (Writer' w) where`

2023-11-29 16:53 UTC, qilowoq commented on hw8/src/MyLib.hs
> +-- Traversable позволяет вам применять функцию к значению в контексте и собирать результаты в другой контекст
У нас есть функция из значения без контекста во что-то в контексте. Но применяется эта функция к чему-то в другом контексте.

 Под сибирает результаты я имел в виду, что после применения функции мы к полученному результату применяем контекст который был в функции.

2023-11-29 16:54 UTC, qilowoq commented on hw8/src/MyLib.hs
> +                [cM] >>= \case -- hlint предложил \case
LambdaCase

2023-11-29 16:58 UTC, qilowoq commented on hw8/src/MyLib.hs
> +-- Я не понят причем тут Foldable. Ведь он позволяет свернуть структуру данных в одно значение.
Нашел такой от ответ: 

Traversable использует fmap из Functor для применения функции к каждому элементу структуры данных.

Traversable использует операции свертки из Foldable для обработки элементов структуры данных в определенном порядке.

2023-11-29 17:04 UTC, qilowoq commented on hw8/src/MyLib.hs
> +      helper :: (d -> a -> b) -> (d -> a) -> d -> b
<*> применяет ff к aa, используя одно и то же значение d для обеих функций. 

Можно комбинировать функции, которые работают с одним и тем же d.

2023-11-29 17:13 UTC, qilowoq commented on hw8/src/MyLib.hs
> +-- Эффект: мы храним функцию. При вызове runWithData мы передаем в нее данные и получаем результат.
Если так рассматривать, то можно написать так
```haskell
instance MonadFail (WithData d) where
  fail :: String -> WithData d a
  fail _ = WithData $ const $ error "Key error"
```

2023-11-30 08:04 UTC, pluralia commented on hw8/src/MyLib.hs
> +      helper :: (d -> a -> b) -> (d -> a) -> d -> b
Замени, пожалуйста, на лямбду -- здесь она не нужна: слишком короткая и ухудшает читаемость

2023-11-30 08:05 UTC, pluralia commented on hw8/src/MyLib.hs
> +      helper :: (d -> a) -> (a -> WithData d b) -> d -> b
Замени, пожалуйста, на лямбду -- здесь она не нужна: слишком короткая и ухудшает читаемость

2023-11-30 08:05 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- Эффект: мы храним функцию. При вызове runWithData мы передаем в нее данные и получаем результат.
Если кидаешь `error`, можно не оборачивать в `WithData $ const`

2023-11-30 08:11 UTC, pluralia commented
Закрою тебе эту домашку без фиксов мелких комментариев. Обрати внимание, что, если функциональность совсем небольшая, ее лучше прописывать в виде лямбд, а не выносить в отдельные функции, потому что лямбды в этом случае лучше читаются

2023-11-30 08:11 UTC, closed without merging