HW1
pluralia/fp-fall-2023 pull request #6
Opened 2023-10-05 10:42 UTC by SophiaLaz

Shishkina hw1

2023-10-05 20:46 UTC, pluralia requested changes

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +fibHelper :: Int -> Int -> Int -> Int
`fibHelper` не используется глобально -- перенеси ее, пожалуйста, в блок `where` или `let-in` внутрь `fibTail`

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +-- Хвостовая рекурсия работает значительно быстрее, так как ей не требуется дважды рекурсивно вычислять саму себя.
Дважды?

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +-- Хвостовая рекурсия работает значительно быстрее, так как ей не требуется дважды рекурсивно вычислять саму себя.
Какой результат эта функция выдает на 1500 и почему?

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +myLength :: [a] -> Int
Как будет выглядеть эта функция с хвостовой рекурсией?

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +myInit (x : xs) = mapMaybe (\t -> x : t) (myInit xs)
Молодец 👍

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +myReverseHelper :: [a] -> [a] -> [a]
Сделай, пожалуйста, эту функцию локальной

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +elemByIndexHealper :: [a] -> Int -> Maybe a
Для чего нужна эта функция?

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +chPrev :: ChurchNumber -> Maybe ChurchNumber
Maybe 👍

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +data Point = Point Float Float
С рекордами было бы прикольнее

2023-10-05 20:46 UTC, pluralia commented on homework1.hs
> +move :: Point -> Float -> Point
Что выдает эта функция при вычислении?

2023-10-11 20:00 UTC, SophiaLaz commented on homework1.hs
> +move :: Point -> Float -> Point
тип данных Point: координаты точки, данной на вход, но сдвинутыми по обеим осям на заданное расстояние

2023-10-11 21:56 UTC, pluralia commented on homework1.hs
> +-- а функцияция с хвостовой рекурсией всё хорошо считает - дело в асимптотике).
Проблема не в асимптотике -- количество вычислений там одинаковое, -- а в переполнении стека. При не хвостовой рекурсии вычисления накапливаются, и память заканчивается. Хвостовую же рекурсию компилятор умеет оптимизировать.

2023-10-11 21:56 UTC, closed without merging

2023-10-12 13:37 UTC, SophiaLaz commented on homework1.hs
> +-- а функцияция с хвостовой рекурсией всё хорошо считает - дело в асимптотике).
поняла, спасибо.