hw8_Pushkina
pluralia/fp-fall-2023 pull request #60
Opened 2023-11-24 07:24 UTC by forestcream

Вроде все ворнинги и Hlint из той части, что я не трогала
Чего-то мне монады тут оказались прямо тяжкими, я не сумела добить 8 задание 
Так же у меня почему-то выдавали ошибки тесты про то, что variable not in the scope

2023-11-28 01:34 UTC, pluralia requested changes
> Чего-то мне монады тут оказались прямо тяжкими, я не сумела добить 8 задание

У тебя отличная идея про 8 задание и ты единственная, предложил такое решение -- добивай!

Напиши мне в личку, если после 9 домашки с монадами будет по-прежнему тяжело -- будем разбираться

2023-11-28 01:34 UTC, pluralia commented on hw8/test/TestSpec.hs
> +-- Task 3
Какая проблема возникла в этом тесте?

2023-11-28 01:34 UTC, pluralia commented on hw8/test/TestSpec.hs
> +-- getSum Variable not in scope
Нужно импортировать моноид Sum в этот файл

2023-11-28 01:34 UTC, pluralia commented on hw8/test/TestSpec.hs
> +-- tell, listen, pass - Variable not in scope:
Нужно импортировать Control.Monad.Writer -- тогда все заработает

2023-11-28 01:34 UTC, pluralia commented on hw8/test/TestSpec.hs
> +-- local Variable not in scope
Нужно импортировать Control.Monad.Reader -- тогда все заработает

2023-11-28 18:19 UTC, forestcream commented on hw8/src/MyLib.hs
> +{-# LANGUAGE FlexibleInstances, MultiParamTypeClasses, InstanceSigs #-}
Он дает разрешение, чтобы определять классы типов с более, чем одним параметром, как вот здесь например
```haskell
instance MonadReader r (Reader' r) where
    ask :: Reader' r r
    ask = reader'
        where
            reader' = Reader' $ \r -> Identity r

    local :: (r -> r) -> Reader' r a -> Reader' r a
    local f reader' = Reader' h
        where
            h r = runReader' reader' (f r)
```

2023-11-28 18:24 UTC, forestcream commented on hw8/src/MyLib.hs
> +    traverse f (List xs) = List <$> traverse f xs
```haskell
instance Traversable List where
    traverse :: Applicative f => (a -> f b) -> List a -> f (List b)
    traverse f (List xs) = List <$> myTraverse f xs
      where
        myTraverse :: Applicative f => (a -> f b) -> [a] -> f [b]
        myTraverse _ [] = pure []
        myTraverse g (y:ys) = (:) <$> g y <*> myTraverse g ys
```

2023-11-28 18:50 UTC, forestcream commented on hw8/src/MyLib.hs
> +-- обойти весь тот тип данных который у нас есть, плюс он оставляет контекст
Контекстом может быть любой тип, который нам нужен. Functor при этом определяет fmap, а Foldable дает возможность использовать свертку

2023-11-28 18:54 UTC, forestcream commented on hw8/src/MyLib.hs
> +rejectWithNegatives xs = if foldr ((&&) . isJust . deleteIfNegative) True xs then Just xs else Nothing
```haskell
rejectWithNegatives :: (Num a, Ord a) => [a] -> Maybe [a]
rejectWithNegatives = traverse deleteIfNegative
  where
    deleteIfNegative :: (Num a, Ord a) => a -> Maybe a
    deleteIfNegative x = if x < 0 then Nothing else Just x
```

2023-11-28 18:56 UTC, forestcream commented on hw8/src/MyLib.hs
> +-- для того, чтобы ловить ошибки в do-нотации, чтобы она вся не полтела
Про ошибки - скорее всего это любые не совпадения типов
Про использование не в do-нотации - ощущение, что ничего от этого не останавливает, но не очень понятно зачем

2023-11-28 18:57 UTC, forestcream commented on hw8/src/MyLib.hs
> +-- получается, что мы можем делать какие-то вычисления, таская за собой d. Так же мы можем d использовать его где угодно в процессе вычислений
А у нас тогда получается, что не возможно один ключ к разным значениям? или так нельзя в key-value storage

2023-11-28 19:01 UTC, forestcream commented on hw8/src/MyLib.hs
> +    fail _ = WithData (error "Sonething went wrong")
Исправила
```haskell
instance MonadFail (WithData d) where
    fail :: String -> WithData d a
    fail _ = error "WithData failed"
```

2023-11-28 19:04 UTC, forestcream commented on hw8/src/MyLib.hs
> +pythagoreanTriples n = nub $ do
Вот так вроде не должны
```haskell
pythagoreanTriples :: Int -> [(Int, Int, Int)]
pythagoreanTriples n = nub $ do
  a <- [1..n]
  b <- [1..a]
  c <- [1..b]
  if a*a + b*b == c*c
    then return (a, b, c)
    else []
```

2023-11-28 19:06 UTC, forestcream commented on hw8/test/TestSpec.hs
> +-- Task 3
если я запускаю с ним тесты у меня бесконечно они висят
![image](https://github.com/pluralia/fp-fall-2023/assets/20926830/6dfc8b1a-14b7-4a8d-ada7-1acbf6e018ad)

2023-11-29 16:39 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- обойти весь тот тип данных который у нас есть, плюс он оставляет контекст
Сравни, пожалуйста, fmap и свертку: что происходит при использовании каждой из функций?

2023-11-29 16:44 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- для того, чтобы ловить ошибки в do-нотации, чтобы она вся не полтела
> Про ошибки - скорее всего это любые не совпадения типов

Ошибка -- фейл паттерн матчинга. Например, [здесь](https://github.com/pluralia/fp-fall-2023/blob/hw8/prac8.hs#L81) мы можем продолжать работу только, если нам пришел список из 2 элементов. Если придет что-то еще, паттерн матчинг зафейлится и `fail` будет вызван автоматически

> Про использование не в do-нотации - ощущение, что ничего от этого не останавливает, но не очень понятно зачем

Чтобы обработать ошибку так, как это задумал создатель монады. Монадой может стать любой кастомный тип, для которого возможно создать инстанс монады, удовлетворяющий законам

2023-11-29 16:49 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- получается, что мы можем делать какие-то вычисления, таская за собой d. Так же мы можем d использовать его где угодно в процессе вычислений
Можно так задать:
```haskell
mySuperMap :: WithData k a
mySuperMap = WithData $ (!) myMap -- частично применяем оператор `!`
  where
    myMap :: Map k a
    myMap = fromList [(<key>, <value>), ...] -- заполняем мапу значениями
```

2023-11-29 16:54 UTC, pluralia commented
@forestcream, не пушила новые коммиты? У меня ничего не отображается

2023-11-29 16:55 UTC, pluralia commented on hw8/test/TestSpec.hs
> +-- Task 3
Должно само пофиксится, когда добьешь решение 👍

2023-11-29 17:10 UTC, forestcream commented
Не, я еще ничего не пушила - все что исправила, добавила просто в ответы на комментарии

2023-12-01 18:33 UTC, forestcream commented on hw8/src/MyLib.hs
> +    aM Control.Monad.Reader.>>= f . (+ 10)
Я вроде разобралась, но не уверена. Я не очень поняла куда `pure(c, b)` девать
```haskell
fromDo11 aM bM =
  fmap (+ 10) aM >>= (\a ->
              let aL [a, a, a] in
              a = a + lenght aL
            pure a)

            >> bM
            (\aL' ->
              case aL' of
                [a, b, c] -> Just aL') >>=(\bM' ->
                                            case \bM' of
                                              b -> fmap (<> "abcd") bM')
                                              _ -> fail ""
                _         -> fail ""
            pure (c, b)
```

2023-12-01 18:44 UTC, forestcream commented on hw8/src/MyLib.hs
> +            case cM of
```haskell
fromDo12 isL cM = 
  isL >>= (\curI -> 
    tail isL >>= \nextI
    if nextI > curI
      then 
        let a = curI + nextI in
        tail $ tail isL >>= \nextNextI ->
          case [cM]) of
            Just ch -> case (curI, nextI, nextNextI) of
                            (0, 0, 0) -> pure (ch, a)
                            _         -> fail ""

            _       -> fail ""
```

2023-12-01 18:49 UTC, forestcream commented on hw8/src/MyLib.hs
> +        let n = fromMaybe 0 result  -- Используем 0, если вычисление не удалось
Это поменять с `Maybe Int` на `Maybe String`? у меня же просто и так вроде `Maybe`

2023-12-01 19:08 UTC, forestcream commented
Запушила коммит, я переделала 8, но у меня теперь все падает с ошибкой просто :(

2023-12-06 00:00 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- fromDo12 isL cM =
Раскомментируй, пожалуйста, -- должен получиться корректный код

2023-12-06 00:01 UTC, pluralia commented on hw8/src/MyLib.hs
> +        let n = fromMaybe 0 result  -- Используем 0, если вычисление не удалось
https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#v:maybe

2023-12-06 00:09 UTC, pluralia commented on hw8/src/MyLib.hs
> +-- Ощущение, что просто логичнее и удобнее если трезультат идет первее
Давай посмотрим на класс типов `Functor`: https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#t:Functor

Видишь `f :: Type-> Type`? Это значит, что наш класс типов может быть реализован только для типа, который параметризован одним типом, а Writer у нас парамеризован двумя. Поэтому, чтобы написать инстанс для Writer, нам нужно зафиксировать один его тип, т.е. частично применить. И тут становится важно, какой тип у нас указан первым -- именно его мы и можем зафиксировать, а оставшийся тип -- тип значения, которое мы и будем изменять в функциях Functor.

Соответственно, если я поменять их местами, мы получим возможность изменять лог, а не значение, а значение менять уже не сможем

2023-12-06 01:12 UTC, pluralia commented
@forestcream, не добито 8 задание (поставлю за него 0,5/2) и 6 задание (поставлю 0,25/1) -- итого 7,75

Можешь попробовать добить 6 (поставлю +0,5) и 8 (поставлю +1)

2023-12-06 01:12 UTC, closed without merging