Add files via upload
pluralia/fp-fall-2023 pull request #61
Opened 2023-11-24 07:54 UTC by Artem9999999999999999999999

1. Hlint ругается на функцию fromDo11 из 6 задания, менять не стал, потому что это условие задания
2. Пока реализованы только с 6 по 10 задания
3. Есть ворнинги на те же функции из 6 задания, трогать не стал по тем же причинам
4. Есть ворнинги на функции из первой половины заданий (с 1 по 5), их тоже видел, но исправлять не стал, потому что буду сдавать их в субботу
5. Местами не очевидно на что писать тесты, постарался сделать по максимуму, если где-то не доглядел дайте пожалуйста знать

2023-11-25 12:28 UTC, Artem9999999999999999999999 commented
Добавил оставшуюся половину заданий

2023-11-28 01:41 UTC, pluralia requested changes
-0,5 -- 9с

> Местами не очевидно на что писать тесты, постарался сделать по максимуму, если где-то не доглядел дайте пожалуйста знать

Не хватает тестов для 9c

2023-11-28 01:41 UTC, pluralia commented on hw8/src/MyLib.hs
> +    extractValue :: Maybe Int -> Int
Можно заменить на функцию `maybe` -- помнишь, на паре использовали?

2023-11-28 01:41 UTC, pluralia commented on hw8/test/TestSpec.hs
> +        -- Оригинальная функция зависает на любом запросе:
👍

2023-11-28 01:41 UTC, pluralia commented on hw8/test/TestSpec.hs
> +      it "ReturnableCalculation tests" $ do
Неверное имя группы тестов

2023-12-01 10:46 UTC, Artem9999999999999999999999 commented
Сделал коммит со всеми исправлениями и ответами на вопросы

2023-12-06 01:28 UTC, pluralia commented
-0,5 за 9с и -0,25 за неточности в ответах на вопросы и небольшой недочет в 6 -- 9,25 за домашку

2023-12-06 01:28 UTC, closed without merging