HW9_ShchukinIA
pluralia/fp-fall-2023 pull request #65
Opened 2023-11-28 10:20 UTC by paiksonn

- Ворнингов нет, Hlint выдает несколько хинтов, я в коде объяснил их (они в основном по базовому коду дз, который исходно там был, поэтому ничего не менял) 
- Не написаны функции groupSame (задание 1) и fib (задание 4.4), потому что пока не получается, заапдейчу, если что-то получится
- Все тесты на месте, кроме тестов на функции whileM_ и forM_, потому что я так и не понял (даже с пояснениями из ТГ) как их проверить, как написать функции не трогающие IO и при этом работающие с этим всем

2023-12-05 01:42 UTC, pluralia requested changes
Молодец, что все рекомендации hlint описываешь!

Как писать тесты вместе разберемся -- ты начал разбираться до дедлайна, поэтому поставлю полный балл, если напишешь до дедлайна по исправлениям

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +incVar varName amount = do
Можно использовать [`alter`](https://hackage.haskell.org/package/containers-0.7/docs/Data-Map-Internal.html#v:alter)

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +-- plusOneInState = state $ \currentState -> ((), M.map (+1) currentState)
Здесь тебе поможет `incVar`

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +-- checkLessThanOrEqual n = do
А здесь нужно использовать `getVar`

Для примера:
```haskell
do
  i <- getVar "i"
  pure $ i < n
```

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +--     let c = cur
`c` -- переменная, которую нужно задать в state, поэтому тебе нужна `setVar`

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +--     incVar "prev" c
Почему `incVar`?

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +-- Реализуйте инстанс Monad для StateWithError
Не хватает сигнатур

2023-12-05 01:42 UTC, pluralia commented on lib/MyLib.hs
> +  when (length sstate < 5) $ modifyState "Error: State length too short"
Как будто в случае ошибки должно возвращаться `Left`

2023-12-06 16:34 UTC, paiksonn commented on lib/MyLib.hs
> +-- тут Hlint предлагает заменить then на when, я попробовал, но тогда у меня ничего не работает
Я потом еще покопался и нашел почему: 
если просто прописать `import Control.Monad`, то компилятор не "видит" `when` из него 
но если добавить `import Control.Monad (when)`, то все работает 
Поэтому добавил `(when)` и исправил все рекомендации Hlint, теперь их совсем нет

2023-12-06 16:34 UTC, paiksonn commented on lib/MyLib.hs
> +-- почему-то мой компилятор when не распознает, поэтому оставил так
Ответил выше

2023-12-06 16:37 UTC, paiksonn commented on lib/MyLib.hs
> +match [] _ = Nothing  -- Если список правил пуст, возвращаем Nothing
Find? Сейчас перепишу через нее и заапдейчу код

2023-12-06 16:50 UTC, paiksonn commented on lib/MyLib.hs
> +          logMsg $ "Packet from " ++ show (pSource packet) ++ " to " ++ show (pDestination packet) ++ " was accepted"
Убрал дублирование через вспомогательную функцию

2023-12-06 17:29 UTC, paiksonn commented on lib/MyLib.hs
> +mergeEntries (x:xs) (y:ys)
1. Как я понимаю - да, может. 
(Функция рекурсивно обрабатывает элементы обоих списков и объединяет их, если их сообщения (поле msg) совпадают, складывая их значения count. Функция продолжает рекурсивный обход, пока один из списков не станет пустым. Получается, что если mergeEntries вызывается на списках из 2 и более элементов, функция будет рекурсивно сравнивать и объединять элементы этих списков)
2. Потому что `tell` работает с монадой `Writer`, а она использует моноид (список) для накопления набора элементов, которые будут записаны. Поэтому-то мы и оборачиваем `Entry` в `[Entry]`

2023-12-06 19:00 UTC, pluralia commented on lib/MyLib.hs
> +mergeEntries (x:xs) (y:ys)
2. Да, мы здесь используем оборачивание в список, чтобы получить Monoid и, как следствие, возможность объединять логи автоматом
1. В теории может, а на практике -- нет. `mergeEntries` существует для `groupSame`, а `groupSame` вызывает `mergeEntries`, чтобы замержить один входящий `Entry` с текущим `Entry` в `initial`. Т.e. без ограничения от `Writer` работать только с `Monoid` в качестве лога мы бы спокойно обходились просто `Entry`, вместо `[Entry]`

Отсюда следует, что в `mergeEntries` достаточно обработать случаи, когда списки содержат 0 или 1 элемент

2023-12-06 19:04 UTC, pluralia commented on lib/MyLib.hs
> +mergeEntries [] ys = tell ys >> return []
Можно упростить:
```haskell
| msg == msg' = return [(Log (count x + count y) (msg x)]
```

2023-12-06 20:25 UTC, paiksonn commented on lib/MyLib.hs
> +  when (length sstate < 5) $ modifyState "Error: State length too short"
Да, немного странно реализовал, согласен

2023-12-06 20:26 UTC, paiksonn commented
1 задания полностью доделал, осталось решить вопрос с шаблонами из 2 задания и переписать fib

2023-12-06 21:06 UTC, pluralia commented on lib/MyLib.hs
> +    mergeEntries [merged] ys
По-прежнему обрабатываешь списки большей длины, чем 1

2023-12-07 06:11 UTC, paiksonn commented on lib/MyLib.hs
> +    mergeEntries [merged] ys
Ой, я забыл заменить заменить эту строку на `| msg == msg' = return [(Log (count x + count y) (msg x)]`
В комментарии увидел, согласился, и не перенес в код

2023-12-07 06:54 UTC, paiksonn commented on lib/MyLib.hs
> +groupSame initial mergeFun values applyFun = do
Вроде бы корректно:
```haskell
ghci> show <$> snd $ runWriter $ groupSame [] mergeEntries packets (filterOne rules)                                                                             
"[Log {count = 1, msg = \"Packet from IPAddress \\\"192.168.1.1\\\" to IPAddress \\\"192.168.1.2\\\" was accepted\"},Log {count = 1, msg = \"Packet from IPAddress \\\"192.168.1.3\\\" to IPAddress \\\"192.168.1.4\\\" has no matching rule\"},Log {count = 1, msg = \"Packet from IPAddress \\\"192.168.1.3\\\" to IPAddress \\\"192.168.1.4\\\" has no matching rule\"}]"
```

2023-12-07 06:55 UTC, paiksonn commented on lib/MyLib.hs
> +  when (length sstate < 5) $ modifyState "Error: State length too short"
А что значит более качественный? 
Я не очень понимаю, почему этот пример плохой и какой тогда будет хорошим

2023-12-07 07:12 UTC, paiksonn commented on lib/MyLib.hs
> +  when (length sstate < 5) $ modifyState "Error: State length too short"
Я могу сделать что-то такое:
```haskell
-- Функция для изменения состояния
modifyState :: str -> StateWithError str err ()
modifyState newState = StateWithError $ \_ -> Right ((), newState)

-- Функция, выдающая текущее состояние
getState :: StateWithError str err str
getState = StateWithError $ \s -> Right (s, s)

-- Функция для вычислений с ошибкой
errState :: err -> StateWithError str err a
errState err = StateWithError $ \_ -> Left err

performCalculation :: Int -> StateWithError String String Int
performCalculation x = do
  sstate <- getState
  if (length sstate < 5) 
    then errState "Error: State length too short"
    else return (x * 2)
```

Чтобы через Left было понятнее, что это ошибка

2023-12-07 08:29 UTC, paiksonn commented on lib/MyLib.hs
> +resolve = resolveTemplate
В текущей реализации она бесполезна, по сути не нужна, поэтому убрал функцию `resolveTemplate` и все реализовал через `resolve`

2023-12-07 08:29 UTC, paiksonn commented on lib/MyLib.hs
> +resolveTemplate _ = return ""
Понял, спасибо!

2023-12-17 17:57 UTC, pluralia commented
👍

2023-12-17 17:57 UTC, closed without merging