hw9_Pushkina
pluralia/fp-fall-2023 pull request #67
Opened 2023-11-30 12:33 UTC by forestcream

hlint и ворнингов нет
в 5 задании не придумала как сделать монад

2023-12-05 01:46 UTC, pluralia requested changes
+0,15 за классную реализацию `filterAll` в первом задании
Про 5 задание -- в комментарии к заданию

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +whileM_ mb ma = do
Сделай, пожалуйста, названия переменных более читаемыми

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +    Control.Monad.when b $ ma >> whileM_ mb ma -- это hlint предложил, но мне кажется с If понятнее
hlint молодец -- when хорош, когда у тебя только then-ветка

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +incVar var inc = do
Можно использовать [`alter`](https://hackage.haskell.org/package/containers-0.7/docs/Data-Map-Internal.html#v:alter)

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +fib 0 = do
Почему 0?

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +--      используя монаду 'State' и функции, которые вы реализовали выше.
В этом задании нужно было использовать `get-`, `set-`, `incVar`, реализованные выше. Перепишешь?

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +        prev = cur;
В этой строчке баг -- исправишь? И в своей реализации тоже

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +    --(>>=) :: StateWithError s e a-> (a -> StateWithError s e b) -> StateWithError s e b
В чем именно возникла проблема?

2023-12-05 01:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +-- Привидите пример использования
Нет примера использования

2023-12-09 06:52 UTC, forestcream commented on hw9/src/MyLib.hs
> +  deriving (Show, Eq)
Он будет отображаться просто 4 цифрами

2023-12-09 06:56 UTC, forestcream commented on hw9/src/MyLib.hs
> +mergeEntries (x:xs) (y:ys)
1. я не вижу причин, чтобы она не могла быть вызвана на списках из 2 и более элементов
2. иначе типы не совпадают
я не смогла придумать как ее использовать в groupSame

2023-12-09 07:18 UTC, forestcream commented on hw9/src/MyLib.hs
> +mergeEntries xs [] = return xs
у нас получается
```haskell
mergeEntries :: [Entry] -> [Entry] -> Writer [Entry] [Entry]
mergeEntries xs [] = return xs                -- базовый соучай рекурсии 
mergeEntries [] (y:ys) = mergeEntries [y] ys  -- если первый список пуст, то мы берем первый элемент из второго списка и вызываемся рекурсивно на новом списке и остатке второго списка
mergeEntries (x:xs) (y:ys)
    | msg x == msg y = let newX = x {count = count x + count y} in mergeEntries (newX:xs) ys -- если сообщения равны - увеличиваем счетчик, создаем новую заппсь, и дальше вызываемся рекурсивно
    | otherwise = do -- иначе мы записываем первый список в лог с помощью tell и вызываемся рекурсивно на списке, состоящем только из y, и остатке второго списка
        tell (x:xs)
        mergeEntries [y] ys
```
или это неправильная логика?

2023-12-09 07:23 UTC, forestcream commented on hw9/src/MyLib.hs
> +  case lookupTemplate (getName name) env of
То есть функция `resolveDef ` должна использовать `resolve name`?

2023-12-09 07:26 UTC, forestcream commented on hw9/src/MyLib.hs
> +resolveDef (Definition name _) = do
а зачем оно нам там нужно?

2023-12-09 07:28 UTC, forestcream commented on hw9/src/MyLib.hs
> +resolve (Quote template) = resolve template
```haskell
resolve (Quote template) = do
  env <- ask
  case lookupTemplate (getName template) env of
    Just tmpl -> resolve tmpl
    Nothing -> return ""
```

2023-12-09 07:37 UTC, forestcream commented on hw9/src/MyLib.hs
> +resolve (Var name) = do
Вот так? 
```haskell
resolve (Var name) = do
  var <- asks $ \env -> lookupVar (getName name) env
  return $ fromMaybe "" var

2023-12-09 07:50 UTC, forestcream commented on hw9/src/MyLib.hs
> +resolve (Include template defs) = do
```haskell
resolve (Include template defs) = do
  templateName <- resolve template
  env <- ask
  case lookupTemplate templateName env of
    Nothing -> return ""
    Just tmpl -> do
      let newDefs = map (\(Definition t v) -> (getName t, getName v)) defs
      let newEnv = addDefs (M.fromList newDefs) env
      local (const newEnv) (resolve tmpl)
```

2023-12-09 07:53 UTC, forestcream commented on hw9/src/MyLib.hs
> +-- потому что он вообще не может менять никакие состояния, иначе бы были сайд эффекты
Любое нарушение чистоты - мы больше не можем утверждать, что функция будет чистой и возвращать с одним и тем же входом всегда одни и те же значения

2023-12-09 07:55 UTC, forestcream commented on hw9/src/MyLib.hs
> +-- получается, мы нарушаем правило про чистоту функций - что она должна всегда возвращть одно и то же значение при одинаковых входных данных
Ну у нас же как раз таки этот дополнительный параметр и рушит всю чистоту функции

2023-12-09 07:57 UTC, forestcream commented on hw9/src/MyLib.hs
> +whileM_ mb ma = do
```haskell
whileM_ :: (Applicative m, Monad m) => m Bool -> m a -> m ()
whileM_ conditionAction repeatAction = do
    condition <- conditionAction
    Control.Monad.when condition $ repeatAction >> whileM_ conditionAction repeatAction
```

2023-12-09 08:01 UTC, forestcream commented on hw9/src/MyLib.hs
> +incVar var inc = do
```haskell
incVar :: String -> Int -> State Context ()
incVar var inc = do
    context <- get
    let updatedContext = M.alter (\case
                                  Just value -> Just (value + inc)
                                  Nothing -> error "Variable not found in context") var context
    put updatedContext
```

2023-12-09 08:02 UTC, forestcream commented on hw9/src/MyLib.hs
> +fib 0 = do
как базовый случай

2023-12-09 08:04 UTC, forestcream commented on hw9/src/MyLib.hs
> +--      используя монаду 'State' и функции, которые вы реализовали выше.
```haskell
fib :: Int -> State Context Int
fib 0 = getVar "prev"
fib n = do
    prev <- getVar "prev"
    cur <- getVar "cur"
    setVar "prev" cur
    setVar "cur" (prev + cur)
    fib (n - 1)
```

2023-12-09 08:18 UTC, forestcream commented on hw9/src/MyLib.hs
> +    --(>>=) :: StateWithError s e a-> (a -> StateWithError s e b) -> StateWithError s e b
я на тот момент просто не поняла как его сделать. Вроде будет вот так
```haskell
instance Monad (StateWithError s e) where
    return :: a -> StateWithError s e a
    return = pure

    (>>=) :: StateWithError s e a-> (a -> StateWithError s e b) -> StateWithError s e b
    m >>= k = StateWithError $ \s1 -> case runStateWithError m s1 of
        Left e      -> Left e
        Right (s2,a) -> runStateWithError (k a) s2
```

2023-12-09 08:23 UTC, forestcream commented on hw9/src/MyLib.hs
> +-- Привидите пример использования
Пример
```haskell

data MyError = Oops deriving (Show)

type MyState = Int

increment :: StateWithError MyState MyError ()
increment = StateWithError $ \s -> if s >= 5 then Left Oops else Right (s + 1, ())

run :: StateWithError MyState MyError a -> MyState -> Either MyError (MyState, a)
run = runStateWithError

-- Пример использования
example :: Either MyError (MyState, ())
example = run (replicateM_ 6 increment) 0 -- Left Oops
```

2023-12-18 21:26 UTC, pluralia commented on hw9/src/MyLib.hs
> +mergeEntries (x:xs) (y:ys)
2) Да, мы здесь используем оборачивание в список, чтобы получить Monoid и, как следствие, возможность объединять логи автоматом
1) В теории может, а на практике -- нет. `mergeEntries` существует для `groupSame`, а `groupSame` вызывает `mergeEntries`, чтобы замержить один входящий `Entry` с текущим `Entry`. Т.e. без ограничения от `Writer` работать только с `Monoid` в качестве лога мы бы спокойно обходились просто `Entry`, вместо `[Entry]`. Отсюда следует, что в `mergeEntries` достаточно обработать случаи, когда списки содержат 0 или 1 элемент

2023-12-18 21:37 UTC, pluralia commented on hw9/src/MyLib.hs
> +  case lookupTemplate (getName name) env of
Да

2023-12-18 21:39 UTC, pluralia commented on hw9/src/MyLib.hs
> +resolveDef (Definition name _) = do
Суть функции -- зарезолвить тело шаблона на текущем Environment'e

2023-12-18 21:41 UTC, pluralia commented on hw9/src/MyLib.hs
> +resolve (Quote template) = resolve template
```haskell
resolve (Quote templ) = do
  name <- resolve templ
  body <- asks (lookupTemplate name)
  resolve $ fromMaybe (Text "") body
```

2023-12-18 21:44 UTC, pluralia commented on hw9/src/MyLib.hs
> +resolve (Include template defs) = do
Почти
```haskell
resolve (Include template defs) = do
  templateName <- resolve template
  env <- ask
  case lookupTemplate templateName env of
    Nothing -> return ""
    Just tmpl -> do
      resolvedDefs <- mapM resolveDef defs                         -- резолвим defs
      local (addDefs (M.fromList newDefs)) (resolve tmpl)   -- эти 2 строки можно замержить
```

2023-12-18 21:46 UTC, pluralia commented on hw9/src/MyLib.hs
> +-- получается, мы нарушаем правило про чистоту функций - что она должна всегда возвращть одно и то же значение при одинаковых входных данных
Важно: дополнительный параметр не рушит чистоту функции как таковую. Он рушит чистоту функции относительно основных параметров

2023-12-18 21:47 UTC, pluralia commented on hw9/src/MyLib.hs
> +--      используя монаду 'State' и функции, которые вы реализовали выше.
Ты используешь рекурсию, а хотелось именно цикл. Точнее то, что его имитирует в Haskell -- `forM_`

2023-12-18 21:52 UTC, pluralia commented
9 баллов 👍 

+0,15 за классную реализацию `filterAll` в 1 задании, пусть и без `groupSame`
-0,25 за 1 задание -- не добила `filterAll` с `groupSame`
-0,75 за 2 -- `getName` там не нужен; неполный `resolve`
-0,15 за 4.4 через рекурсию

2023-12-18 21:52 UTC, closed without merging