HW9_Dmitriev
pluralia/fp-fall-2023 pull request #69
Opened 2023-11-30 20:06 UTC by qilowoq

2023-12-05 01:49 UTC, pluralia requested changes

2023-12-05 01:49 UTC, pluralia commented on hw9/src/MyLib.hs
> +incVar s i =
Можно использовать [`alter`](https://hackage.haskell.org/package/containers-0.7/docs/Data-Map-Internal.html#v:alter)

2023-12-05 01:49 UTC, pluralia commented on hw9/src/MyLib.hs
> +      setVar "cur" =<< (+) <$> getVar "prev" <*> getVar "cur"
`incVar`?

2023-12-05 01:49 UTC, pluralia commented on hw9/src/MyLib.hs
> +      setVar "c" =<< getVar "cur"
`=<<` -- классно!

2023-12-05 01:49 UTC, pluralia commented on hw9/src/MyLib.hs
> +newtype StateWithError a
А если параметризовать типы ошибки и состояния?

2023-12-06 04:36 UTC, qilowoq commented on hw9/src/MyLib.hs
> +mergeEntries (e : es) (e' : es') =
Я не понимаю как их мерджить

2023-12-06 05:18 UTC, qilowoq commented on hw9/src/MyLib.hs
> +        case lookupVar var env of
Что вообще quote такое?

2023-12-06 05:48 UTC, qilowoq commented on hw9/src/MyLib.hs
> +      setVar "cur" =<< (+) <$> getVar "prev" <*> getVar "cur"
Не понял?

2023-12-06 05:49 UTC, qilowoq commented on hw9/src/MyLib.hs
> +newtype StateWithError a
Можно не надо. Я не хочу это все переписывать ...

2023-12-06 10:04 UTC, pluralia commented on hw9/src/MyLib.hs
> +mergeEntries (e : es) (e' : es') =
Не ответил на мои вопросы

Я намекаю на то, что у тебя невозможен случай входных списков из более 1 элемента, поэтому тебе нужно обработать всего 3 случая:
1) es []
2) [] es
3) [e1] [e2]
На оставшиеся можно кинуть ошибку

Как именно обрабатывать случай 3 (какое сообщение логировать, а какое возвращать в качестве значения) указано в описании к заданию.

2023-12-06 10:21 UTC, pluralia commented on hw9/src/MyLib.hs
> +  asks $ \env -> fromMaybe "" . lookupVar (runReader (resolve templ) env) $ env
Использует `asks`, но читается тяжело. Подразумевалось
```haskell
do
  varName  <- resolve templ
  varValue <- asks (lookupVar varName)
  return $ fromMaybe "" varValue
```

2023-12-06 10:21 UTC, pluralia commented on hw9/src/MyLib.hs
> +        case lookupVar var env of
У нас есть неизвестные 2 видов: перменные и шаблоны. Оба типа резолвятся в соответствующие значения, при этом переменные задаются `Var`, а шаблоны -- `Quote`. Почему Quote -- полагаю, потому что названия шаблонов мы подразумеваем поставлять в кавычках

2023-12-06 10:27 UTC, pluralia commented on hw9/src/MyLib.hs
> +    env' = addDefs (M.fromList $ runReader (mapM resolveDef defs) env) env
1) У тебя может быть вложенная do-нотация
2) Попробуй переписать без runReader и используй local -- нужно научиться использовать local

2023-12-06 10:33 UTC, pluralia commented on hw9/src/MyLib.hs
> +-- Грязным делает то, что мы не можем отделить чистый код от кода, который изменяет состояние. Наверное
Пойдет

2023-12-06 10:42 UTC, pluralia commented on hw9/src/MyLib.hs
> +-- Я думаю, что если состояние генератора не обновляется, то порядок вызова функций не важен
Твоя правда

2023-12-06 10:42 UTC, pluralia commented on hw9/src/MyLib.hs
> +      setVar "cur" =<< (+) <$> getVar "prev" <*> getVar "cur"
Здесь можно использовать `incVar`

2023-12-06 10:43 UTC, pluralia commented on hw9/src/MyLib.hs
> +newtype StateWithError a
Там немного: инстансы переписывать не придется. Но да, можешь забить

2023-12-06 21:32 UTC, qilowoq commented on hw9/src/MyLib.hs
> +groupSame initial merge xs fn =
У меня такой же лог сейчас.

```haskell
ghci> rules = [Rule Accept (IP 192 168 1 1) (IP 192 168 1 2)]
ghci> packets = [Packet (IP 192 168 1 1) (IP 192 168 1 2), Packet (IP 192 168 1 3) (IP 192 168 1 4), Packet (IP 192 168 1 3) (IP 192 168 1 4)]
ghci> show <$> snd $ runWriter $ groupSame [] mergeEntries packets (filterOne rules)
"[Log {count = 1, msg = \"Packet from 192.168.1.1 to 192.168.1.2 is accepted\"},Log {count = 2, msg = \"Packet from 192.168.1.3 to 192.168.1.4 is rejected\"}]"
```

2023-12-06 21:38 UTC, qilowoq commented on hw9/src/MyLib.hs
> +mergeEntries (e : es) (e' : es') =
Тогда я не понимаю зачем нам списки. 

У меня сейчас сделано, что в первом списке хранятся обработанные сообшения, а в правом поступающие. 
Я сравниваю первые сообщения в каждом списке, а после добавляю новое сообшение в начало первого списка.

Я понимаю, что от меня требовалось сделать другое, но вроде оно работает...

2023-12-06 22:28 UTC, pluralia commented on hw9/src/MyLib.hs
> +mergeEntries (e : es) (e' : es') =
Ок, в твоей реализации в `mergeEntries` действительно приходит список списков

> Тогда я не понимаю зачем нам списки.

`Writer` ставит ограничение на тип лога -- тот должен быть моноидом. При этом `Entry` сам по себе не моноид, поэтому мы оборачиваем его в список. Основная логика подразумевалась в `groupSame`, поэтому `mergeEntries` должен был бы быть проще, но твое решение тоже вполне подходит

2023-12-06 22:35 UTC, pluralia commented
Исправишь `filterAll` и зачту домашку

2023-12-07 01:04 UTC, closed without merging