HW9_Shishkina
pluralia/fp-fall-2023 pull request #71
Opened 2023-11-30 20:49 UTC by SophiaLaz

Не до конца поняла задание с шаблонами, поэтому пока не доделала
Если надо добавить тесты - сделаю

2023-12-05 01:50 UTC, pluralia requested changes

2023-12-05 01:50 UTC, pluralia commented on src/MyLib.hs
> +  -- на `when` hlint сказал исправить. + добавлены ограничения на класс типов:
👍

2023-12-05 01:50 UTC, pluralia commented on src/MyLib.hs
> +incVar name delta = do
Можно использовать [`alter`](https://hackage.haskell.org/package/containers-0.7/docs/Data-Map-Internal.html#v:alter)

2023-12-05 01:50 UTC, pluralia commented on src/MyLib.hs
> +    Just val -> state (val, )
Почему не return?

2023-12-05 01:50 UTC, pluralia commented on src/MyLib.hs
> +-- Привидите пример использования
Не нашла примера использования

2023-12-06 16:20 UTC, SophiaLaz commented on src/MyLib.hs
> +newtype IP = IP Int
Потому что IP адрес состоит из 4х чисел до 256 (то есть требуют по одному байту памяти) - всего 4 байта получается. `Int` тоже 4 байта занимает

2023-12-08 18:07 UTC, SophiaLaz commented on src/MyLib.hs
> +mergeEntries (log1 : logs1) (log2 : logs2) = do
Задание было немного сложным из-за формулировки
Изначально я подумала, что у нас есть два списка логов и их нужно попарно сравнить. Но эти вопросы помогли понять ситуацию)
1. нет, мы должны сравнить два пришедших лога, которые завёрнуты в лист
2. чтобы можно было их конкатенировать

2023-12-08 18:09 UTC, SophiaLaz commented on src/MyLib.hs
> +mergeEntries _ [] = pure []
Потому что не с чем было сравнивать первое сообщение
Поправлю

2023-12-08 18:15 UTC, SophiaLaz commented on src/MyLib.hs
> +mergeEntries _ [] = pure []
Нет, поправила

2023-12-08 21:16 UTC, SophiaLaz commented on src/MyLib.hs
> +      local (addDefs $ M.fromList templsPairs) $ pure . show $ incVal -- добавляем их в окружение
Надо зарезолвить `incVal`

2023-12-08 21:33 UTC, SophiaLaz commented on src/MyLib.hs
> +    Just tempVal -> pure $ show tempVal
Думала, что надо вывести шаблон
Исправила на `resolve`

2023-12-08 22:10 UTC, SophiaLaz commented on src/MyLib.hs
> +--    потому что одной переменной не может быть присвоено два разных значения
Все переменные в Haskell неизменяемые. Кроме того, Haskell - чистый функциональный язык, это значит, что если одной и той же функции дать одинаковые аргументы, то она выдаст одинаковый результат, так что переменные можно рассматривать как константные функции (переменная символизирует результат готовых вычислений)

2023-12-09 09:29 UTC, SophiaLaz commented on src/MyLib.hs
> +getAny = state R.random
Если запустить этот пример, то видно, что состояние обновляется
```haskell
doubleGetAny :: State R.StdGen (Int, Int)
doubleGetAny = do
  r1 <- (getAny :: State R.StdGen Int)
  r2 <- (getAny :: State R.StdGen Int)
  pure (r1, r2)
```

2023-12-09 09:31 UTC, SophiaLaz commented on src/MyLib.hs
> +getAny = state R.random
```haskell
ghci> let r = R.mkStdGen 42
ghci> runState doubleGetAny r
((1275548033995301424,-8029435041741618537),StdGen {unStdGen = SMGen 18209985878117922550 13679457532755275413})
```

2023-12-09 09:35 UTC, SophiaLaz commented on src/MyLib.hs
> +getOne bounds = state $ R.randomR bounds
И на этом примере видно, что возвращаются разные результаты:
```haskell
doubleGetOne :: (Int, Int) -> State R.StdGen (Int, Int)
doubleGetOne bound = do
  r1 <- (getOne bound :: State R.StdGen Int)
  r2 <- (getOne bound :: State R.StdGen Int)
  pure (r1, r2)

ghci> let bound = (7, 16)
ghci> let r = R.mkStdGen 52
ghci> runState (doubleGetOne bound) r
((14,8),StdGen {unStdGen = SMGen 17143425344897783250 17993093053756489803})
```

2023-12-09 09:36 UTC, SophiaLaz commented on src/MyLib.hs
> +getAny = state R.random
Но если вызывать дважды подряд из консоли функцию `getAny` или `getOne` с одним и тем же аргументом, то да, состояние не будет обновляться (я думаю, что это из-за того, что мы передаём один и тот же `MkStdGen` для запуска, так что логично, что окружение как будто не изменённое).
Всё ещё надо что-то исправить?

2023-12-09 10:05 UTC, SophiaLaz commented on src/MyLib.hs
> +-- Привидите пример использования
В тестах лежат
Мне показалось слишком длинным писать `runStateWithError`, поэтому я заменила на `MyState`

2023-12-09 10:07 UTC, SophiaLaz commented on src/MyLib.hs
> +    Just val -> state (val, )
Исправила

2023-12-18 22:07 UTC, pluralia commented on src/MyLib.hs
> +mergeEntries (log1 : logs1) (log2 : logs2) = do
> Задание было немного сложным из-за формулировки

@SophiaLaz, согласна. Я обновила формулировки [здесь](https://github.com/pluralia/fp-fall-2023/blob/hw9/hw9.hs)

2023-12-18 22:11 UTC, pluralia commented on src/MyLib.hs
> +getAny = state R.random
Ты разобралась, в чем суть, поэтому не нужно

2023-12-18 22:13 UTC, pluralia commented
👍

2023-12-18 22:13 UTC, closed without merging