HW10_Dmitriev
pluralia/fp-fall-2023 pull request #74
Opened 2023-12-07 02:23 UTC by qilowoq

там hlint ругается, но я не понимаю почему

2023-12-13 04:21 UTC, pluralia requested changes
Нет 4 задания -> 7 за дз

Можешь доделать 4 задание до дедлайна по исправлениям

2023-12-13 04:21 UTC, pluralia commented on hw10/app/Task2.hs
> +-- To run:
Как запустить без cabal?

2023-12-13 04:21 UTC, pluralia commented on hw10/app/Task3.hs
> +-- How to run:
Как запустить без cabal?

2023-12-14 12:33 UTC, qilowoq commented on hw10/src/MyLib.hs
> +-- По скорости работы разницы особой я не заметил. Мб с буфером чуть медленнее
- Данные временно хранятся в "буфере" перед тем, как они будут записаны в файл.
- `hFlush` нужна для принудительной записи данных из буфера в файл.
- Потому, что `LineBuffering` в данном примере ничем не отличается от записи без буфера.
- По сути дела тут они одинаковые.

2023-12-14 13:33 UTC, qilowoq commented on hw10/app/Task2.hs
> +-- To run:
```
> ghc Task1.hs 
> Task1
```

Просто так он создает лишние файлы

2023-12-14 13:36 UTC, qilowoq commented on hw10/app/Task3.hs
> +-- How to run:
```
> ghc app/Task2.hs -package bytestring
> app/Task2 ../example.txt
```

2023-12-15 06:39 UTC, pluralia commented on hw10/src/MyLib.hs
> +-- По скорости работы разницы особой я не заметил. Мб с буфером чуть медленнее
> Потому, что LineBuffering в данном примере ничем не отличается от записи без буфера.

Что это значит?

> Какой способ самый быстрый и почему?
> > По сути дела тут они одинаковые. Но вообще быстрее с буферезацией, тк меньше обращений к файлу.

Уточню вопрос. Какой способ самый быстрый: c буфером или без и, если с буфером, то какого типа?

2023-12-15 06:40 UTC, pluralia commented on hw10/app/Task2.hs
> +-- To run:
> Просто так он создает лишние файлы

Так уж и лишние?

2023-12-15 06:47 UTC, pluralia commented
@qilowoq, 7,5 за дз (+0,5 за 2/4 ответа на вопроса ко 2 заданию) -- готова закрыть PR

Планируешь делать 4 задание и/или доотвечать на вопросы?

2023-12-15 06:47 UTC, qilowoq commented on hw10/src/MyLib.hs
> +-- По скорости работы разницы особой я не заметил. Мб с буфером чуть медленнее
`LineBuffering` добавляет в буфер до тех пор пока не встретит `\n`. Затем записывает буфер в файл.  `hPutStrLn` встречается на каждой итерации цикла. Эта функция добавляет `\n ` в конец строки. Тем самым Мы заставляем буфер записаться в файл на каждой итерации цикла как и без буфера.

В данном примере `LineBuffering `< Без буфера < `BlockBuffering`. LineBuffering просто будет работать медленнее из-за оверхеда при работе с буфером. `BlockBuffering` быстрее тк меньше раз обращаемя к файлу

2023-12-15 06:50 UTC, qilowoq commented
>  2/4 ответа

Можно по подробнее где я не правильно ответил

2023-12-15 06:51 UTC, pluralia commented
Сейчас 3/4. На 3 в первый раз ответил недостаточно развернуто (сейчас ок), на 4 -- уточнила вопрос

2023-12-15 06:53 UTC, qilowoq commented
Можно закрывать PR

2023-12-15 06:55 UTC, pluralia commented
7,75 👍

2023-12-15 06:55 UTC, closed without merging