HW10_ShchukinIA
pluralia/fp-fall-2023 pull request #75
Opened 2023-12-07 10:21 UTC by paiksonn

Hlint молчит, компилятор дает два ворнинга на функции `writeToFile` и `writeToFileWithBuffer`, но это не на мои действия, а на исходный код дз, поэтому ничего не трогал
Пока что не получается сделать task3, task4, если получится, то залью код, все остальное работает, запускается и вообще красота

2023-12-13 04:04 UTC, pluralia requested changes
Пока 5,5 за дз -- можешь попробовать доделать 3 и 4 задания до дедлайна по исправлениям, тем более, что 11 дз ты уже прислал

2023-12-13 04:04 UTC, pluralia commented on io_hw/task2.hs
> +  let filePath = "example.txt" -- устанавливаем путь к файлу, который нужно обработать
Нужно написать скрипт так, чтобы передавать ему путь до файла в качестве аргумента

2023-12-13 05:36 UTC, paiksonn commented on test/TestSpec.hs
> +    True `shouldBe` True
Я думал, что в этом дз тесты не нужны, но по привычке создал тестовый файл
Поэтому чтобы не ловить за него ворнинги, я эту заглушку прописал 
Тесты написал, будут в заапдейченом файле

2023-12-13 05:39 UTC, paiksonn commented on lib/MyLib.hs
> +processInput Locked Coin = (Unlocked, [Thank])
Да, но я не стал этого делать, чтобы визуально было видно разделение по условиям задания, потому что там прописаны отдельно условия:
--   1. Если опускают монету в заблокированный турникет, то нужно поблагодарить, и турникет разблокируется
--   2. Если монету опускают в разблокированный турникет, то нужно поблагодарить, но состояние турникета не изменяется

2023-12-13 05:43 UTC, paiksonn commented on lib/MyLib.hs
> +processInput Unlocked Push = (Locked, [Open, Tut])
Может быть я неверно понял условие?
Как я это понял:
Если толкнуть рычаг, когда турникет разблокирован (т.е. на вход пришли условия Unlocked Push), то рычаг откроется, чтобы пропустить его (т.е. даст состояние Open), а затем закроется (т.е. даст состояние Tut), чтобы не пропустить никого другого

2023-12-13 05:50 UTC, paiksonn commented on lib/MyLib.hs
> +processInput :: TurnstileState -> TurnstileInput -> (TurnstileState, [TurnstileOutput])
Можно было бы сделать просто TurnstileOutput, если бы у меня не было вот такой строки:
```haskell
processInput Unlocked Push = (Locked, [Open, Tut])
```
Т.к. тут я возвращаю список из нескольких действий, поэтому и поставил [TurnstileOutput]

Но, как я понял, тут есть вопрос к самому этому условию (один из комментариев выше), потому что, возможно, у меня другое понимание условия "--   3. Если толкнуть рычаг, когда турникет разблокирован, рычаг откроется, чтобы пропустить его, а затем закроется, чтобы не пропустить никого другого"

Надо разобраться с этим моментом,  и как только мы сойдемся в понимании условия задачи, если будет нужно, я исправлю все

2023-12-13 05:51 UTC, paiksonn commented on lib/MyLib.hs
> +-- Приведите пример запуска на последовательности действий [Coin, Coin, Push, Push, Coin]
Не знал, что он нужен, думал exampleInput'а будет достаточно 
Добавлю в тесты

2023-12-13 05:55 UTC, paiksonn commented on lib/MyLib.hs
> +-- С учетом моего processInput должна на выходе быть последовательность Thank,Thank,Open,Tut,Tut,Thank
Для этого конкретного примера нет разницы, будет начальное состояние `locked/unlocked`, т.к. в начале, первым действием, опускается монета (причем даже два раза подряд), поэтому, даже если начальное состояние было `locked`, оно после первого `coin` сменится на `unlocked`

2023-12-13 06:03 UTC, paiksonn commented on io_hw/task1.hs
> +    then do -- если равна, закрываем файл и завершаем цикл
Нет, но просто я написал так, как обычно пишу в императивных языках а-ля 
`
if ... then do ... else do ...
`
Это ведь особо не влияет на перфоманс кода, но мне лично так больше по душе :)

2023-12-13 06:15 UTC, paiksonn commented on io_hw/task2.hs
> +  let filePath = "example.txt" -- устанавливаем путь к файлу, который нужно обработать
А, ну это не сложно, просто я так прописал, чтобы быстрее было запускать task2.hs и не прописывать каждый раз путь к до файла 
Просто поменять на такой код:
```haskell
import System.Environment (getArgs)

main :: IO ()
main = do
  [filePath] <- getArgs
  countFile filePath
```

2023-12-13 06:31 UTC, paiksonn commented on io_hw/task2.hs
> +  let filePath = "example.txt" -- устанавливаем путь к файлу, который нужно обработать
![image](https://github.com/pluralia/fp-fall-2023/assets/113239177/35988d80-0ebb-45a6-8a70-86f2a7528e62)

2023-12-13 07:18 UTC, paiksonn commented on lib/MyLib.hs
> +    let (outputs, newState) = foldl (\(outs, sstate) inp ->
1. 1 Переписанный вариант через foldl':
```haskell
turnstile :: [TurnstileInput] -> State TurnstileState [TurnstileOutput]
turnstile inputs = do
    currentState <- get
    let (outputs, newState) = foldl' (\(outs, sstate) inp ->
            let (newsState, newOutputs) = processInput sstate inp
            in (outs ++ newOutputs, newsState)) ([], currentState) inputs
    put newState
    return outputs
```
1.2 Асимптотика O(n^2) получалась из-за конкатенации списков `outs ++ newOutputs` на каждом шаге свертки

2. Новый вариант функции `turnstile`:
```haskell
processInputM :: TurnstileInput -> State TurnstileState [TurnstileOutput]
processInputM input = do
  currentState <- get
  let (newState, outputs) = processInput currentState input
  put newState
  return outputs

turnstile :: [TurnstileInput] -> State TurnstileState [TurnstileOutput]
turnstile inputs = do
  outputLists <- mapM processInputM inputs
  return (concat outputLists)
```

2023-12-13 08:01 UTC, paiksonn commented on lib/MyLib.hs
> +-- 2. Запись в файл с буфером и без (0,5 балла)
1. Она помогает (в некоторых случаях) сильно быстрее записывать данные в файл (в примере из [этой статьи](https://mmhaskell.com/blog/2022/5/16/bufferingplease-wait) правильный выбор буфера привел к увеличению скорости работы скрипта в 17 раз). 
Существует 3 опции работы буфера - это:
- NoBuffering (буфер есть, но в нем ничего не хранится, данные будут записываться в файл сразу, как только поступают в него)
- LineBuffering  (записи в буфере будут накапливаться до тех пор, пока не встретят newline символ, и только затем запишутся в файл)
- BlockBuffering (записи в буфере будут копиться, пока не достигнут определенного количества байтов, либо их принудительно не зафлашат)

Соответственно правильный выбор buffer option иногда может сыграть существенную роль в скорости работы программы

2. Чтобы принудительно записывать данные из буфера в файл, а не ждать, пока их накопится на нужное число байтов (а еще, согласно все [этой же статье](https://mmhaskell.com/blog/2022/5/16/bufferingplease-wait), можно вообще не писать `hFlush`, потому что он автоматически выполнится при `hClose `)

3. Вопрос с подвохом. 
Функция `writeToFile` пишет данные в файл сразу посимвольно (т.е. это равносильно тому, что используется NoBuffering), функция `writeToFileWithBuffer` пишет данные в файл по достижении newline character (еще и делает дополнительный дамп буффера, чтобы в нем не накапливались уж очень большие данные, а потом еще и автоматический дамп произойдет на `hClose`). Исходя из логики - функции не работают одинаково по времени. По идее, должно быть как в примере из приведенной статьи -  `writeToFile` работает медленнее, чем `writeToFileWithBuffer`, но чтобы честно это проверить, можно было бы прописать вручную в функции `writeToFile` `hSetBuffering h NoBuffering` и затем замерить время выполнения функции. Далее замерить время выполнения функции `writeToFileWithBuffer` и сравнить их (вероятнее всего результат бы получился аналогичен результату статьи)

4. Если вопрос про то, кто быстрее из функций `writeToFile` и `writeToFileWithBuffer`, то в предыдущем пункте ответил на него.
Если вопрос про способы буферизации, то ответом будет BlockBuffering, потому что "doing fewer writes with larger amounts of data tends to be more efficient than doing more writes with smaller amounts of data".

2023-12-13 10:08 UTC, paiksonn commented
Добавил реализованное 3 задание и поменял ввод аргумента во 2 задании

2023-12-14 09:35 UTC, paiksonn commented on lib/MyLib.hs
> +processInput Unlocked Push = (Locked, [Open, Tut])
Я посмотрел, как это делали другие ребята, и понял, что я некорректно понял и переусложнил условие)
Оказывается, если приходят Unlocked Push, достаточно просто открыть рычаг (т.е. Open) и всё
Переписал код с учётом этого момента и добавил тесты
Сейчас заапдейчу код

2023-12-14 09:37 UTC, paiksonn commented on test/TestSpec.hs
> +    True `shouldBe` True
UPD: там чуть ниже в другом комментарии написал, что были за вопросы и что они решились, тесты добавил в новом коде

2023-12-14 09:38 UTC, paiksonn commented on lib/MyLib.hs
> +processInput :: TurnstileState -> TurnstileInput -> (TurnstileState, [TurnstileOutput])
UPD: со всем разобрался, список там теперь не нужен, новая версия кода заапдейчена

2023-12-14 09:40 UTC, paiksonn commented on lib/MyLib.hs
> +    let (outputs, newState) = foldl (\(outs, sstate) inp ->
UPD: переделал код, теперь там нет списков, новые реализации лежат в заапдейченом коде

2023-12-14 10:02 UTC, paiksonn commented on lib/MyLib.hs
> +-- Первое - это тот факт, что во второй функции мы флашим те значения, которые делятся на 10000, а в первой - нет
согласен, написал некорректно

2023-12-18 23:32 UTC, pluralia commented on lib/MyLib.hs
> +-- 2. Запись в файл с буфером и без (0,5 балла)
2. Можно и не писать, но, если нам хочется досрочно опустошить буфер, то можно использовать `hFlush`. Собственно, в оригинальном задании нам захотелось это делать по условию "когда достигаем 10000 строки, флашим *все* существующее в буфере

2023-12-18 23:34 UTC, pluralia commented on io_hw/task1.hs
> +    then do -- если равна, закрываем файл и завершаем цикл
Мы на Haskell пишем 🤔

2023-12-18 23:36 UTC, pluralia commented
👍 
-3 -- нет 4 задания
+0,75 -- за ответы на вопросы (зачла 3/4)

2023-12-18 23:36 UTC, closed without merging