HW10_ManasyanAL
pluralia/fp-fall-2023 pull request #76
Opened 2023-12-07 15:14 UTC by Artem9999999999999999999999

2023-12-13 04:36 UTC, pluralia requested changes
Дз качественно выполнил -- умничка!
4 задание не проверяла -- подожду, если кто-то еще сдаст

2023-12-13 04:36 UTC, pluralia commented on io_hw/task3.hs
> +endsWith :: FilePath -> String -> Bool
Можно заменить на библиотечную функцию

2023-12-13 04:36 UTC, pluralia commented on io_hw/task3.hs
> +startsWith :: FilePath -> String -> Bool
Можно заменить на библиотечную функцию

2023-12-13 10:16 UTC, Artem9999999999999999999999 commented on hw10/src/MyLib.hs
> +-- 00:32:92
Измерял чуть-чуть костыльно через ```bash```. Сделал отдельные скрипты с каждой из функций и запускал их через ./buf и ./no_buf, время определял следующим образом:
```bash
start_time=$(date +%s)
# тут скрипт 
end_time=$(date +%s)
echo "Общее время работы: $((end_time - start_time)) секунд"
```

2023-12-13 10:16 UTC, Artem9999999999999999999999 commented on hw10/src/MyLib.hs
> +-- но тогда вопрос зачем нужна функция hSetBuffering, если без нее работает быстрее
1.  Запись с буфером означает, что данные не записываются в файл сразу после вызова соответствующей функции (```hPutStrLn``` в данном случае), а добавляются в буфер обработки. Реальная запись в файл происходит либо при достижении определенного размера буфера, либо при явном вызове функции ```hFlush```.
2.  Функция ```hFlush``` используется для явного сброса буфера обработки в файл. Это гарантирует, что все данные, находящиеся в буфере, будут немедленно записаны в файл. Это особенно полезно при работе с буферизованным выводом, когда мы хотим удостовериться, что все данные записаны перед закрытием файла или важной операцией.
3. В данном случае обе функции работают почти одинаково по времени, потому что ```writeToFileWithBuffer``` использует буфер, но вызывает ```hFlush``` после каждой 10,000 записи. Это частично уменьшает эффект буферизации, поскольку данные частично сбрасываются на диск. В результате, производительность становится близкой к ```writeToFile```, которая записывает данные без буферизации.
4. Исходя из данных статьи, использование ```BlockBuffering Nothing``` оказалось самым быстрым, потому что буферизация происходит, но запись в файл происходит только после достижения определенного объема данных в буфере (или автоматически при закрытии файла). Это уменьшает количество операций записи и, следовательно, повышает производительность при записи больших объемов данных.

2023-12-13 10:17 UTC, Artem9999999999999999999999 commented
Сделал коммит, заменил свои функции на библиотечные

2023-12-18 22:52 UTC, pluralia commented on hw10/src/MyLib.hs
> +-- 00:32:92
Можно использовать `time`

2023-12-18 23:06 UTC, pluralia commented on io_hw/task4.hs
> +-- это вылетает с ошибкой на этапе компиляции
Все скомпилится, если напишешь первые 2 строки так
```haskell
    let fsKVS = createFileSystemKVS "data" :: FileSystemKVS String Int
    put fsKVS "key1" 42
```

2023-12-18 23:06 UTC, pluralia commented
+1 за ответы на вопросы, молодец, что сделал 4 задание 👍

2023-12-18 23:06 UTC, closed without merging