hw10_Pushkina
pluralia/fp-fall-2023 pull request #77
Opened 2023-12-07 19:03 UTC by forestcream

Ворнингов и hlint нет
Я не очень поняла как доделывать task4, остальные task`и проверяла - работают

2023-12-13 04:23 UTC, pluralia requested changes
Нет 4 задания, копипаста неполного решения 1 задания -> 5,5 за дз

Можешь доделать 1 и 4 задания до дедлайна по исправлениям

2023-12-13 04:23 UTC, pluralia commented on hw10/io_hw/task2.hs
> +    content <- Data.ByteString.readFile "D:/Study/fp-fall-2023-1/hw10/text_copy_0.log"
Скрипт должен принимать путь до файла в качестве аргумента

2023-12-13 04:23 UTC, pluralia commented on hw10/io_hw/task3.hs
> +    if matches pattern (takeFileName file)
Почему `takeFileName`? Нам же нужно проверять полные пути файлов на матч

2023-12-15 06:59 UTC, forestcream commented on hw10/test/TestSpec.hs
> +-- import Test.Hspec
добавила в коммит

2023-12-15 07:00 UTC, forestcream commented on hw10/src/MyLib.hs
> +trans Coin Locked   = ([Thank], Unlocked)
```haskell
trans :: TurnstileInput -> TurnstileState -> ([TurnstileOutput], TurnstileState)
trans Coin _   = ([Thank], Unlocked)
trans Push Locked   = ([Tut], Locked)
trans Push Unlocked = ([Open], Locked)
```

2023-12-15 07:17 UTC, forestcream commented on hw10/src/MyLib.hs
> +-- 2. Запись в файл с буфером и без (0,5 балла)
1. Когда мы вызываем `hPutStr` или `hPutStrLn` у нас не идет запись прямо в это же время - строка добавляется в буффер и дальше в зависимости от типа буффера, который мы выбрали, будет добавляться в файл. Если мы используем `NoBuffering `, то строчка будет записывать по символьно
2. `hFlush` помогает предотвратить ситуацию, когда мы используем `BlockBuffering` и число реальных записей меньше чем у нас указан блок. То есть мы можем сделать `flush` (смыть? промыть?) и заставить записать информацию (`hClose ` так делает)
3. В статье, они измеряют время выполнения схожей программы и там разница в милисекунды, что просто наблюдательно не поймешь. но если надо нужно прямо очень много чего записать, то с буффером будет быстрее
4. Самый быстрый будет `BlockBuffering ` , потому что он получается еще реже чем построчная буфферизация обращается к файлу, что ускоряет его время работы

2023-12-15 07:22 UTC, forestcream commented on hw10/src/MyLib.hs
> +turnstile inputs = mapM (state . trans) inputs Data.Functor.<&> concat
Это перевернутый `<$>`, то есть он применяет `concat ` к результату `mapM (state . trans) inputs`. мне ее hlint исправлял, но я сейчас смотрю и логичнее выглядит `concat <$> mapM (state . trans) inputs
` вот такая версия функции

2023-12-15 07:26 UTC, forestcream commented on hw10/src/MyLib.hs
> +trans :: TurnstileInput -> TurnstileState -> ([TurnstileOutput], TurnstileState)
Потому что я сначала подумала, что у нас может быть несколько выходов одновременно (Открыть и поблагодарить), а потом потом забыла исправить

2023-12-15 07:27 UTC, forestcream commented on hw10/src/MyLib.hs
> +turnstile inputs = mapM (state . trans) inputs Data.Functor.<&> concat
А вот это не считается? я просто не очень поняла, что является примером запуска
```haskell
inputs' :: [TurnstileInput]
inputs' = 
  [         -- initial: Locked
    Coin    -- Thank, Unlocked
  , Coin    -- Thank, Unlocked
  , Push    -- Open, Locked
  , Coin    -- Thank, Unlocked
  , Push    -- Open, Locked
  , Push    -- Tut, Locked
  ]
```

2023-12-15 07:50 UTC, forestcream commented on hw10/io_hw/task1.hs
> +main = loop 0 0
```haskell
loop :: Int -> Int -> Handle -> IO ()
loop n i h = do
    input <- getLine
    hPutStrLn h input
    putStrLn input
    let nextI = i + 1
    if nextI >= 1000
        then do
            hClose h
            newH <- openFile ("text_copy_" ++ show (n + 1) ++ ".log") AppendMode
            loop (n + 1) 0 newH
        else loop n nextI h

main :: IO ()
main = do
    h <- openFile "text_copy_0.log" AppendMode
    loop 0 0 h
```

2023-12-15 14:56 UTC, pluralia commented on hw10/src/MyLib.hs
> +turnstile inputs = mapM (state . trans) inputs Data.Functor.<&> concat
Что выдаст `turnstile inputs'`? Похоже ли это на ответ?

2023-12-15 15:33 UTC, forestcream commented on hw10/io_hw/task2.hs
> +    content <- Data.ByteString.readFile "D:/Study/fp-fall-2023-1/hw10/text_copy_0.log"
```haskell
main :: IO ()
main = do
    args <- getArgs
    let filePath = Prelude.head args
    doStuff filePath
    

doStuff :: String -> IO()
doStuff filePath = do
    content <- Data.ByteString.readFile filePath
    let text = E.decodeUtf8 content
    let linesCount = T.count(T.pack "\n") text
    let wordsCount = (Prelude.length . T.words) text
    let bytesCount = Data.ByteString.length content
    putStrLn $ "\t " ++ "\t " ++ show   linesCount ++ "\t " ++ show wordsCount ++ "\t " ++ show bytesCount ++ "\t " ++ filePath
```

2023-12-15 15:35 UTC, forestcream commented on hw10/io_hw/task3.hs
> +    if matches pattern (takeFileName file)
Исправила
```haskell 
processFile :: String -> FilePath -> IO ()
processFile pattern file =
    if matches pattern  file
        then putStrLn file
        else return ()
```

2023-12-18 23:16 UTC, pluralia commented on hw10/src/MyLib.hs
> +-- 2. Запись в файл с буфером и без (0,5 балла)
3. не ответ на вопрос
0,75 / 1

2023-12-18 23:23 UTC, pluralia commented
+0,75 за ответы на вопросы (не зачла ответ на 3 вопрос)
-0,25 за 1 (про state) -- нет примера запуска
+1,5 за 1 (про io)

5,5 - 0,25 + 0,75 + 1,5 = 7,5 за домашку 👍

2023-12-18 23:23 UTC, closed without merging