HW10_Shishkina
pluralia/fp-fall-2023 pull request #78
Opened 2023-12-07 21:01 UTC by SophiaLaz

1. Не очень поняла, как тестировать, кроме как запускать скрипты из консоли - поэтому тестов пока нет
2. hlint ругается в одном месте, просит исправить `traverse` на `traverse_`, но это порождает ошибку, которую не знаю как править, так что оставила так
3. 4е задание в файле `app/Main.hs`, потому что `cabal build` всегда хотел файл `Main`
4. Ворниги не по смыслу, так что остались

2023-12-13 04:38 UTC, pluralia requested changes
1. Никто не сделал тесты на IO, поэтому никому не снижала. Покажу на следующей паре
2. Ответила про `traverse_` в комментариях

4 задание не проверяла (подожду, если кто-то еще сдаст), но оставила коммент на счет `main`

2023-12-13 04:38 UTC, pluralia commented on app/Task2.hs
> +main fileName = do
Как вызвать этот скрипт так, чтобы передать ему файл?

2023-12-13 04:38 UTC, pluralia commented on app/Task3.hs
> +    helper (startPath :: FilePath) pat
Действительно ли `helper` здесь нужен?

2023-12-13 04:38 UTC, pluralia commented on app/Task3.hs
> +                    _ <- traverse (\ f -> helper (path ++ "/" ++ f) pat') ls
По поводу `traverse_`: заимпорти `import Data.Foldable (traverse_)`, и ошибка должна уйти. Если нет, запости, пожалуйста, ее в коммент сюда

2023-12-13 04:38 UTC, pluralia commented on app/Task3.hs
> +                    pure ()
Для чего?

2023-12-13 04:38 UTC, pluralia commented on app/Task3.hs
> +            pure ()
Для чего?

2023-12-13 04:38 UTC, pluralia commented on app/Task3.hs
> +          | pat' !! (length pat' - 1) == '*'  = T.isPrefixOf (T.pack $ init pat') (T.pack str)
Нет необходимости паковать в Text, чтобы использовать isPrefixOf

2023-12-13 04:38 UTC, pluralia commented on app/Main.hs
> +main = undefined
Было бы классно увидеть наполнение здесь: так можно было бы посмотреть примеры использования

2023-12-13 17:52 UTC, SophiaLaz commented on src/MyLib.hs
> +-- Запись в файл с буфером работает дольше - это происходит из-за того, что буфер по умолчанию работает эффективнее.
У меня `writeToFile` отработала за 9 секунд, а `writeToFileWithBuffer` за 26 секунд. Я сделала вывод, что Haskell когда записывает в файл использует какой-то буфер по умолчанию, и он эффективнее, чем использование `LineBuffering`

2023-12-13 18:04 UTC, SophiaLaz commented on app/Task1.hs
> +    where
У меня почему-то VS Code то ставит 2 пробела при нажатии `Tab`, то 4

2023-12-13 18:10 UTC, SophiaLaz commented on app/Task2.hs
> +    pure ()
Не нужна, убрала
Писала по инерции, возвращала всё в нужную монаду `IO`. Но с типами и так всё хорошо (`putStrLn` возвращает тип `IO ()`)

2023-12-13 18:23 UTC, SophiaLaz commented on app/Task2.hs
> +main fileName = do
Можно так:
```haskell
ghci> :l app/Task2.hs 
[1 of 1] Compiling Task2            ( app/Task2.hs, interpreted )
Ok, one module loaded.

ghci> main "example.txt"
        9       97      640
```

2023-12-13 18:28 UTC, SophiaLaz commented on app/Task2.hs
> +main fileName = do
Кажется, поняла, в чём проблема была - функция `main` не должна ничего принимать. Поправила (теперь имя файла считывается с консоли после запуска программы)

2023-12-13 18:30 UTC, SophiaLaz commented on app/Task3.hs
> +                    _ <- traverse (\ f -> helper (path ++ "/" ++ f) pat') ls
Исправила, работает! Странно, что в прошлый раз не получилось (наверное импорт не оттуда делала)

2023-12-13 18:30 UTC, SophiaLaz commented on app/Task3.hs
> +                    pure ()
Убрала

2023-12-13 18:31 UTC, SophiaLaz commented on app/Task3.hs
> +            pure ()
Убрала

2023-12-13 18:33 UTC, SophiaLaz commented on app/Task3.hs
> +          | pat' !! (length pat' - 1) == '*'  = T.isPrefixOf (T.pack $ init pat') (T.pack str)
Да, почему-то когда искала в `Data.List`, проглядела эти функции

2023-12-13 18:36 UTC, SophiaLaz commented on app/Task3.hs
> +    helper (startPath :: FilePath) pat
Я его использую для рекурсивного спуска в поддиректрории

2023-12-13 20:57 UTC, SophiaLaz commented on src/MyLib.hs
> +-- 2. Запись в файл с буфером и без (0,5 балла)
1. Информация записывается в буфер, пока не выполнится условие для записи в файл (в случае `LineBuffering` это наличие символа новой строки, а в случае `BlockBuffering` - пока не наберётся нужное число байт). Если выбран режим `NoBuffering`, то информация будет сразу же записана в файл. 
Так как запись в файл - долгая и сложная операция (с точки зрения ОС), записывать с буфером гораздо эффективнее в случае больших объёмов данных.
2. `hFlush` очищает буфер -- то есть записывает всё, что в нём есть, в файл (также она автоматически вызывается при `hClose`)
3. У меня `writeToFile` работает чуть быстрее, чем `writeToFileWithBuffer`, потому что по умолчанию Haskell использует `BlockBuffering`, который оказывается эффективнее `LineBuffering`
4. Всё зависит от ситуации - в случае маленького количества данных разница будет не очень ощутима. На не очень больших объёмах данных (и если информация не разбита посимвольно на строки) `LineBuffering` и `BlockBuffering`  должны работать примерно одинаково. В случае же больших наборов данных самый быстрый способ - записывать с использованием `BlockBuffering`. Но тут наверняка нужно быть осторожным с подбором размера блоков.

2023-12-15 06:31 UTC, pluralia commented on src/MyLib.hs
> +-- Запись в файл с буфером работает дольше - это происходит из-за того, что буфер по умолчанию работает эффективнее.
Верный вывод!

2023-12-15 06:34 UTC, pluralia commented on app/Task2.hs
> +main fileName = do
Можно так, а можно использовать `getArgs`, чтобы отправлять название файла прямо в исполняемый файл -- это ближе к тому, что требовалось в задании: "Реализуйте скрипт, который работает так же, как Unix-скрипт wc"

Попробовала ли ты скомпилировать ли ты свой код до исполняемого файла, чтобы получился скрипт?

2023-12-15 08:05 UTC, SophiaLaz commented on app/Task2.hs
> +main fileName = do
Да, поняла о чём речь - если с `getArgs` можно передавать аргументы прямо при запуске, так что поправила. 
Да, запускать пробовала вот так (переименовав сначала `Task2 -> Main`):
1. делаю `cabal build`
2. копирую ссылку на исполняемый файл и передаю ему аргументы
3. он возвращает ответ :)
```haskell
[6 of 6] Linking /home/sepofia/../hw10 [Objects changed]
(base) sepofia@sepofia-KLVD-WXX9:~/haskell/fp-fall-2023$   /home/sepofia/../hw10  example.txt 
        9       97      640
```

2023-12-18 22:44 UTC, pluralia commented
+1 балл за ответы на вопросы, по 4 заданию вопросов нет, молодец 👍

2023-12-18 22:44 UTC, closed without merging