HW02_ShchukinIA
pluralia/fp-fall-2023 pull request #8
Opened 2023-10-11 07:28 UTC by paiksonn

```haskell
main :: IO ()
main = putStrLn "Это немного, но это честная работа"
```

2023-10-12 11:59 UTC, pluralia requested changes
1. Исправь, пожалуйста, комментарии hlint`a: понятны ли тебе его предложения?
2. Что выдает `cabal test` при текущем состоянии репозитория в ветке?

2023-10-12 11:59 UTC, pluralia commented on src/MyLib.hs
> +        nodeValue (Node val _) = val
Ты реализовал здесь 2 функции: `nodeValue` и `nodeChildren`. Эти функции экстрактят значения соответствующих полей -- можешь ли ты чуть иначе задать тип `Tree`, чтобы он уже содержал в себе функции, которые экстрактят значения полей?

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +      or [True, False] `shouldBe` (True :: Bool)
Потестировал библиотечную функцию ;)

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +      or [True, True] `shouldBe` (True :: Bool)
Потестировал библиотечную функцию ;)

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +  describe "test `or'" $ do
Не хватает тестов на списки разной длины

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +      -- а можно просто * x
Это вопрос?

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +    it "Case 1" $ do
Можно дать имя получше по предикату / функции. Например `it "> 0"` ...

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +    it "Waba laba dab dab" $ do
<img width="567" alt="Screenshot 2023-10-12 at 13 58 55" src="https://github.com/pluralia/fp-fall-2023/assets/15619772/96a7adfb-da5e-460a-9e4d-1a98426200cf">

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +  describe "test bfs" $ do
Добавь, пожалуйста, больше различных деревьев

2023-10-12 11:59 UTC, pluralia commented on test/TestSpec.hs
> +  describe "test dfs" $ do
Добавь, пожалуйста, больше различных деревьев

2023-10-12 15:47 UTC, paiksonn commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Потому что он правосторонний и мы будем идти до первого True, а как только найдем сразу можем дать результат, не досчитывая все остальное

2023-10-12 15:47 UTC, paiksonn commented on hw2.cabal
> +executable hw2
не понял, кто не нужен?

2023-10-12 15:48 UTC, paiksonn commented on hw2.cabal
> +                 ,      hw02
Там, кажется, нолик лишний....
Просто hw2

2023-10-12 16:06 UTC, paiksonn commented on src/MyLib.hs
> +-- Аналогично примеру с length' дропнул xs с обеих сторон по указке hlint
быстрее вычисляется и не захламляет код

2023-10-12 16:07 UTC, paiksonn commented on test/TestSpec.hs
> +      or [True, False] `shouldBe` (True :: Bool)
Ой, поправил

2023-10-12 16:07 UTC, paiksonn commented on test/TestSpec.hs
> +      or [True, True] `shouldBe` (True :: Bool)
Точно, спасибо, исправил

2023-10-12 16:17 UTC, paiksonn commented on test/TestSpec.hs
> +    it "Case 1" $ do
Сделано!

2023-10-12 16:18 UTC, paiksonn commented on test/TestSpec.hs
> +  describe "test bfs" $ do
Да, исправил, сейчас поправлю остальные косяки и апдейтну файл

2023-10-12 16:18 UTC, paiksonn commented on test/TestSpec.hs
> +  describe "test dfs" $ do
Сейчас поправлю

2023-10-12 16:51 UTC, paiksonn commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Из-за удобства, я загуглил эту функцию `foldr1` и затем придумал с ней реализацию для `maximum'`

2023-10-12 17:00 UTC, paiksonn commented on src/MyLib.hs
> +-- Пока не придумал, как это сделать
Честно говоря - не очень :с

2023-10-12 18:16 UTC, paiksonn commented on src/MyLib.hs
> +        nodeValue (Node val _) = val
Типо вот так?
`data Tree a = Node { value :: a, children :: [Tree a] } `

2023-10-12 18:22 UTC, pluralia commented on hw2.cabal
> +executable hw2
executable модуль. Только для тестирования и библиотека

2023-10-12 18:23 UTC, pluralia commented on hw2.cabal
> +                 ,      hw02
Да, и это важно. С текущей конфигурацией тесты не должны суметь запускаться

2023-10-12 18:24 UTC, pluralia commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Как появляется True при вычислении длины списка?

2023-10-12 18:26 UTC, pluralia commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Молодец, что использовал `foldr1`.
Мой вопрос про снова на то, почему здесь выбрана правосторонняя свертка, а не левостороняя

2023-10-12 18:26 UTC, paiksonn commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
А, это вопрос был про `length'`?
я думал это про `or'`

2023-10-12 18:35 UTC, pluralia commented on src/MyLib.hs
> +-- Пока не придумал, как это сделать
Тебе приходит список чисел. Ты выбираешь из него только те числа, индекс которых -- число Фибоначчи. Сумму оставшихся чисел нужно вернуть.

Пример: [1..10], остались [1, 2, 3, 4, 6, 9], их сумма -- 25.

2023-10-12 18:37 UTC, pluralia commented on test/TestSpec.hs
> +  describe "test `or'" $ do
Как минимум. Давай добавим хотя бы для `or'`

2023-10-12 18:47 UTC, paiksonn commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Она, конечно, медленная, но вроде проверять будет также все элементы списка, как и левосторонняя, разве нет?

2023-10-12 18:51 UTC, paiksonn commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
В целом, как я понимаю, `foldr` - это как написать обычную рекурсию, а `foldl` - это хвостовая рекурсия. 
Т.е. по сути, делают одно и то же, но первый иногда может делать это медленнее (и умеет обрабатывать бесконечные списки, в отличии от второго)

2023-10-12 18:52 UTC, paiksonn commented on test/TestSpec.hs
> +  describe "test `or'" $ do
добавил, сейчас апдейтну файл

2023-10-12 18:59 UTC, paiksonn commented on hw2.cabal
> +executable hw2
А, да. 
Создал его зачем-то)

2023-10-12 19:45 UTC, pluralia commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Почти. Если посмотришь, `foldl` работает долго, потому что из-за ленивости откладывается вычисление аргументов. Именно поэтому нужно использовать энергичную версию `foldl` -- `foldl'`

2023-10-12 19:46 UTC, pluralia commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Так каков ответ на мой изначальный вопрос?

2023-10-12 19:47 UTC, pluralia commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Будет конечно. Просто по заданию нужно было выбрать где-то левостороннюю свертку, а где-то -- правостороннюю, и мне хочется узнать, какой логикой ты руководствовался при выборе сверки

2023-10-12 19:51 UTC, paiksonn commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Если список будет большИм, то потенциально `foldr` должен справиться с ним успешнее, чем `foldl`, как мне кажется

2023-10-12 19:54 UTC, paiksonn commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Честно говоря, именно для функции `maximum'`, мне кажется, что особо нет разницы брать `foldr`\`foldl`, потому что проходить весь массив придется в обоих случаях.
Но, как я писал выше, `foldr`, если я правильно понял, должен лучше справляться со списками большой длины (бесконечными), поэтому его и использовал

2023-10-12 19:56 UTC, paiksonn commented on src/MyLib.hs
> +-- Пока не придумал, как это сделать
А, вот оно что, теперь понял!

2023-10-13 06:31 UTC, paiksonn commented on src/MyLib.hs
> +-- Пока не придумал, как это сделать
Апдейтнул решение, добавив в него вычисление этой задачи

2023-10-13 06:40 UTC, pluralia commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Можно ли посчитать длину бесконечного списка? Нет. Значит, нужно использовать ту функцию, которая быстрее. Какая быстрее?

2023-10-13 06:44 UTC, paiksonn commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Быстрее будет `foldl`, тогда можно переписать функцию вот так:
```haskell
length' :: [a] -> Int
length' = L.foldl' (\count _ -> count + 1) 0
```

2023-10-13 06:45 UTC, pluralia commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
> Но, как я писал выше, foldr, если я правильно понял, должен лучше справляться со списками большой длины (бесконечными), поэтому его и использовал

`foldr` лучше справляется с бесконечными списками только, если операция сверки позволит выдать результат не обходя весь список (например, `or`). Eсли функция требует обхода всего списка (`maximum`), то `foldr` будет работать медленнее, чем энергичная версия `foldl` -- `foldl'`.

2023-10-13 06:47 UTC, pluralia commented on src/MyLib.hs
> +length' xs = foldr (\_ acc -> acc + 1) 0 xs
Да, но обрати внимание еще раз, пожалуйста: именно `foldl'` -- не `foldl`

2023-10-13 06:48 UTC, paiksonn commented on src/MyLib.hs
> +maximum' xs = Just $ foldr1 (\x acc -> if x > acc then x else acc) xs
Тогда перепишу `maximum'` через `L.foldl'`
```haskell
maximum' :: [Int] -> Maybe Int
maximum'  [] = Nothing
maximum' (x : xs) = Just (L.foldl' max x xs)
```

2023-10-13 06:49 UTC, pluralia commented
👍

2023-10-13 06:49 UTC, closed without merging