HW8 Kostina
pluralia/fp-fall-2023 pull request #80
Opened 2023-12-09 12:09 UTC by jmkostina

Я не разобралась с 8 заданием

2023-12-12 01:09 UTC, pluralia requested changes
1 за 6; 1,5 за 9; 1,75 за 10 => 4,25

Постарайся добить 8. Можешь еще 7 сделать -- оно проще, и 0,5 балла доберешь

2023-12-12 01:09 UTC, pluralia commented on src/MyLib.hs
> +        returnIntVal :: Maybe Int -> Int
Это в точности библиотечная функция `fromMaybe`

2023-12-12 01:09 UTC, pluralia commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
Ошибка у тебя в `maybe 0 show newVal`. Давай разберемся, почему она возникает

1. `maybe :: b -> (a -> b) -> Maybe a -> b`
2. `maybe 0 :: (a -> Int) -> Maybe a -> Int`, потому что `0 :: Int` => b ~ Int
3. дальше `maybe 0` ожидает функцию из `a -> Int`, а какой тип у `show`?

Понятно ли, в чем проблема? Какая функция вместо `show` тебе здесь нужна?

2023-12-13 17:45 UTC, jmkostina commented on test/TestSpec.hs
> +        fmap (*15) x `shouldBe` (Writer' (Identity 15, "x ") :: Writer' String Int)
Тестируют, как отрабатывает `fmap` и `(<*>)` для `Writer'`. Я же их инстансы для этого и задала - чтобы можно было применять? Или это нужно не так проверять?

2023-12-13 17:55 UTC, jmkostina commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
У нас `w` - это лог, который мы хотим получать на каждом шаге. Его тип не будет меняться, потому что нам этого не надо; точно также как у нас у `Either` не меняется тип у `Left`. 
А вот `a` - это уже параметр, который может быть любого типа, поэтому для работы с ним мы инстанс и прописываем

2023-12-13 18:32 UTC, jmkostina commented on src/MyLib.hs
> +-- я не поняла как задать
Мне не понятно, как это работает
```haskell
-- c предложенным типом как-то так выглядит, но мне не понятно, 
-- зачем здесь Bool - зачем так задавать, если у нас при проверке на  a == 0 pure возвращается в любом случае, мы же a задаем через let
data ReturnableCalculation a = ReturnableCalculation { val ::  a, returned :: Bool}
  deriving (Show, Eq)

instance Functor ReturnableCalculation where
    fmap :: (a -> b) -> ReturnableCalculation a -> ReturnableCalculation b
    fmap f (ReturnableCalculation x b) = ReturnableCalculation (f x) b

-- здесь и в Monad c realReturn прописала (ReturnableCalculation x True), потому что у нас тип данных задан таким образом, что обязательно нужен второй аргумент
-- но я не понимаю, зачем здесь Bool
instance Applicative ReturnableCalculation where
    pure :: a -> ReturnableCalculation a
    pure x = ReturnableCalculation x True

    (<*>) :: ReturnableCalculation (a -> b) -> ReturnableCalculation a -> ReturnableCalculation b
    ReturnableCalculation f True <*> ReturnableCalculation x True = ReturnableCalculation (f x) True

instance Monad ReturnableCalculation where
    (>>=) :: ReturnableCalculation a -> (a -> ReturnableCalculation b) -> ReturnableCalculation b
    ReturnableCalculation x True >>= f = f x

realReturn :: a -> ReturnableCalculation a
realReturn x = ReturnableCalculation x True
```

2023-12-13 18:34 UTC, jmkostina commented on src/MyLib.hs
> +
это самое простое задание в этой дз
```haskell
pythagoreanTriples :: Int -> [(Int, Int, Int)]
pythagoreanTriples n = do
  c <- [1..n]
  b <- [1..c]
  a <- [1..b]
  if a^2 + b^2 == c^2
    then return (a, b, c)
    else []
```

2023-12-13 18:44 UTC, jmkostina commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
1. тип `show :: a-> String` 
2. я отправила в hoogle `a -> Int`, получила `fromEnum`. Вроде даже правильно в итоге

2023-12-13 18:48 UTC, jmkostina commented on src/MyLib.hs
> +        returnIntVal :: Maybe Int -> Int
тогда так:
```haskell
import           Data.Maybe

evalStmts :: [Stmt] -> Reader' Environment (Maybe Int)
evalStmts [] = pure Nothing
evalStmts (x : xs) = do
    case xs of
        [] -> eval (expr x)
        _ -> do
            env <- ask
            let newVal = runIdentity (runReader' (eval (expr x)) env)
                updEnv = M.insert (name x) (fromMaybe 0 newVal) env
            local (const updEnv) (evalStmts xs)
```

2023-12-13 18:51 UTC, jmkostina commented
@pluralia Все исправления в новом файле

2023-12-20 14:49 UTC, pluralia commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Верно! Дополню

Давай посмотрим на класс типов Functor: https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#t:Functor (аналогично для Applicative, Monad ...)

Видишь f :: Type-> Type? Это значит, что наш класс типов может быть реализован только для типа, который параметризован одним типом, а Writer у нас парамеризован двумя. Поэтому, чтобы написать инстанс для Writer, нам нужно зафиксировать один его тип, т.е. частично применить. И тут становится важно, какой тип у нас указан первым -- именно его мы и можем зафиксировать, а оставшийся тип -- тип значения, которое мы и будем изменять в функциях Functor.

Соответственно, если я поменять их местами, мы получим возможность изменять лог, а не значение, а значение менять уже не сможем

2023-12-20 15:03 UTC, pluralia commented on src/MyLib.hs
> +-- я не поняла как задать
Давай разбираться. На лекции я рассказывала, что `return` из `Monad` в Haskell делает не то, что делает `return` в императивных языках
* В императивных языках, если мы встречаем `return` выполнение программы завершается (или возвращаемся из функции) и все последующие statement'ы игнорируются
* В Haskell, встретив return, мы продолжим выполнение программы (смотри [пример](https://github.com/pluralia/fp-fall-2023/blob/hw8/prac8.hs#L6) в лекции)

Т.e. `return` в Haskell как бы ненастоящий. В этом задании мы хотим создать особый тип для которого можно было бы определить `realReturn`: встретив такой мы бы вернули результат и не продолжали вычисление последующих statement'ов -- т.е. поддержали бы поведение return из императивных языков. Вопрос только в том, как это сделать?

Для этого мы в особом типе данных `ReturnableCalculation` будем хранить значение И информацию о том, был ли вызван `realReturn`. Идея в том, что, пока `realReturn` не вызван, мы храним False и ведем себя со всеми вычислениями как обычно в Haskell (что соответствует стандартной реализации Monad, Functor ...). Когда же `realReturn` вызван, мы ставим True, а реализация Monad, Functor ... начинает игнорировать манипуляции со значением.

Стало ли понятнее?

2023-12-20 15:18 UTC, pluralia commented on test/TestSpec.hs
> +        fmap (*15) x `shouldBe` (Writer' (Identity 15, "x ") :: Writer' String Int)
Все верно, но у тебя там в 9с `sumAndTraceInOrder` есть -- было бы интересно ее потестировать

2023-12-20 15:21 UTC, pluralia commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
2. В чем смысл того, что ты перевела в enum? Что мы принципиально хотим сделать в этой строчке?
```haskell
updEnv = M.insert (name x) (maybe 0 fromEnum (newVal)) env
```

2023-12-20 15:23 UTC, pluralia commented
@jmkostina, выставила +0,5 за 7 задание, но нужно доотвечать на вопросы

Сейчас у тебя 4,75 первичных балла из возможных 6,75 за это задание. Если добьешь 8 задание, поставлю еще. Итоговый (вторичный) балл за эту и оставшиеся домашки будет максимум 9. Соответственно, сейчас за эту домашку у тебя 7. Если сдашь хорошо оставшиеся домашки, то будет 8 баллов итоговая

2023-12-23 11:02 UTC, jmkostina commented on src/MyLib.hs
> +-- я не поняла как задать
Я понимаю смысл `return` - это то, что программа (кусочек программы) выдает на выход. Здесь у меня нет понимания, почему дальше (после `return`) мы вдруг (!) на `if a == 0` падаем не в ветку `then`, а в ветку `else`, если мы в программе прописываем `let a = 0`? Она же без `in`, что бы дальше вдруг не действовать

2023-12-23 11:09 UTC, jmkostina commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
Я обновляю окружение. По типам -> `type Environment = M.Map String Int`, значит нужно, чтобы второй элемент пары был `Int`. По определению [maybe](https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#v:maybe ) берет дефолтное значение, функцию и какое-то обернутое в монаду значение, к которому я хочу применить функцию:
- дефолтное значение - 0
- функция - `fromEnum`
- значение - `newVal`, которое я перед этим получила через `Reader`, а это строка, что нас не устраивает из-за типа `Environment`, поэтому я его делаю числом через `fromEnum`

2023-12-23 11:10 UTC, jmkostina commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Не сможем менять значение или тип значения?

2023-12-23 11:49 UTC, jmkostina commented on test/TestSpec.hs
> +        fmap (*15) x `shouldBe` (Writer' (Identity 15, "x ") :: Writer' String Int)
тесты должны быть такими (добавила в файл), но я не понимаю, почему у меня 0 в сумме при использовании этой функции
```haskell
sumAndTraceInOrder tree1 `shouldBe` (Writer' (Identity [1, 2, 3, 4, 11, 5, 13, 12, 14], Sum 65) :: Writer' (Sum Int) [Int])
sumAndTraceInOrder tree2 `shouldBe` (Writer' (Identity [], Sum 0) :: Writer' (Sum Int) [Int])
sumAndTraceInOrder tree3 `shouldBe` (Writer' (Identity [10, 50, 5, 150], Sum 215) :: Writer' (Sum Int) [Int])
```

2023-12-23 22:53 UTC, pluralia commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Ни то, ни другое

2023-12-23 22:59 UTC, pluralia commented on src/MyLib.hs
> +-- я не поняла как задать
> Я понимаю смысл return - это то, что программа (кусочек программы) выдает на выход.

Да, но не в Haskell! Перечитай, пожалуйста, [этот](https://github.com/pluralia/fp-fall-2023/pull/80#discussion_r1432830010) комментарий еще раз

> почему дальше (после return) мы вдруг (!) на if a == 0 падаем не в ветку then, а в ветку else, если мы в программе прописываем let a = 0? Она же без in, что бы дальше вдруг не действовать

В do-нотации после let in не нужен. Если твой вопрос о том, почему мы впринципе после return полезли что-то выполнять, то еще раз отправляю тебя перечитать тот комментарий. Если после этого останутся вопросы, то задавай

2023-12-23 23:07 UTC, pluralia commented on test/TestSpec.hs
> +        fmap (*15) x `shouldBe` (Writer' (Identity 15, "x ") :: Writer' String Int)
У тебя баг в реализации `Monad` для `Writer'`: теряешь лог. Исправишь баг и все заработает

2023-12-23 23:08 UTC, pluralia commented
Планируешь добивать задание про `ReturnableCalculation`?

2023-12-23 23:22 UTC, pluralia commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
> По типам -> type Environment = M.Map String Int, значит нужно, чтобы второй элемент пары был Int

Верно!

> По определению [maybe](https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#v:maybe) берет дефолтное значение, функцию и какое-то обернутое в монаду значение, к которому я хочу применить функцию:

Верно!

> дефолтное значение - 0

Допустим

> функция - fromEnum

Почему? Кто еще может дать тебе перевод в Int? Нужен ли он тебе вообще? Что такое тип `a`, если подставить реальный тип?

2023-12-24 10:14 UTC, jmkostina commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Но мы же можем менять содержание лога, если таким образом прописываем - иначе весь смысл лога теряется, мы не сможем отследить, что там происходило, если не менять его значение/содержание. 
Почему не сработает также для значения? Или я неправильно опять поняла?

2023-12-24 10:28 UTC, jmkostina commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
1. > Почему? Кто еще может дать тебе перевод в Int?
У нас требование к `Int` значению в` Environment`, я в любом случае должна получить `Int`. Кроме `fromEnum` выданные мне hoogle'ом функции мне не знакомы и выглядят сложными/лишними здесь
2. > Нужен ли он тебе вообще? 
Нужен, или будет ошибка в типах
3. > Что такое тип` a`, если подставить реальный тип?
Не совсем поняла вопрос. 
`а` - это просто обозначение какого-то типа. То есть если написано `someF :: a -> a`, то какая-то функция принимает на вход значение типа `а` и возвращает значение такого же типа `а`, при этом входной тип может быть `Int`, `Char`  и т.д.

2023-12-24 10:32 UTC, jmkostina commented on src/MyLib.hs
> +-- я не поняла как задать
Я понимаю комментарий. И понимаю, что мы не заканчиваем вычисления после `return`. 
Я не понимаю, почему у нас при присваивании `let a = 0` мы падаем в другую ветку. В haskell все операции выполняются последовательно, после строки `let a = 0` у `а` есть значение (мы его больше не меняем), и на нем у нас сравнение `if`, каким образом мы упали в ветку с `realReturn`

2023-12-24 10:34 UTC, jmkostina commented
Я не понимаю, как работает `ReturnableCalculation`, поэтому если не пойму (а времени осталось не много), то и добить его не смогу. Поэтому имеет смысл закрыть PR если по остальным заданиям мои ответы достаточны

2023-12-24 10:51 UTC, jmkostina commented on test/TestSpec.hs
> +        fmap (*15) x `shouldBe` (Writer' (Identity 15, "x ") :: Writer' String Int)
Я ошиблась в `instance Monoid` - там лог надо конкатенировать

2023-12-24 19:18 UTC, jmkostina commented on src/MyLib.hs
> +-- я не поняла как задать
Мне Соня пояснила смысл этого задания, я поняла, что нужно сделать, но в моей реализации ошибки в типах инстансов, происхождение которых мне понятно, но не понятно как их убрать, что бы моя реализация была верной.
Новая версия в файле

2023-12-24 22:24 UTC, pluralia commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Ключевой момент -- средствами класса Functor и другими, которые ожидают f :: Type-> Type). Пример такого средства -- fmap. Он будет работать только для "свободного", оставшегося типа. Если таким типом будет значение -- сможем менять значение при помощи fmap (а лог fmap менять не сможет). Если таким типом будет лог, то fmap сможет менять его, но не значение)

При этом это не значит, что мы не сможем менять лог или значение, залезая внутрь самого объекта по старинке паттерн-матчингом или функциями класса `MonadWriter`

Стало понятнее?

2023-12-24 22:25 UTC, pluralia commented on src/MyLib.hs
> +-- я не поняла как задать
Нужно ли ответить на [этот](https://github.com/pluralia/fp-fall-2023/pull/80#discussion_r1435801330) вопрос?

Спасибо Соне! Посмотрю сейчас

2023-12-24 22:30 UTC, pluralia commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
> Не совсем поняла вопрос.
> а - это просто обозначение какого-то типа.

Да, но вместо `a` при вызове этой функции `someF` подставится какой-то реальный тип. Функция `maybe` вызывается на конкретных значениях и, соответственно, ее обобщенный тип на типовых переменных обретет вполне себе конкретные типы: вместо `a` и `b` подставятся конкретные типы. Какие?

Действительно ли тебе нужна здесь функция из Hoogle?

2023-12-24 23:18 UTC, pluralia requested changes
У тебя верные комментарии, поэтому мне кажется, что твоя текущая проблема в том, что ты не определилась, что такое `returned`. Есть ли конкретные вопросы?

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +-- True - у нас прошло значение
Скорее, был ли вызван `realReturn`. `True`, если был, но можешь выбрать другую логику -- главное, остановись на чем-то одном. Мои комментарии ниже к логике `returned == True`, если хотя бы раз был вызван `realReturn`

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +-- нужно с False, потому что значение закреплено
Зависит от той логики, которую выбираешь

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +    -- если True, то нельзя менять значение
Верно!

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
>      pure x = ReturnableCalculation x True
Изначально `False` -- `realReturn` еще не был вызван

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +    -- все остальные варианты
Тут наоборот: если у обоих `False` (обычное вычисление, потому что ни на ком не был вызван `realReturn`), то вызвать `<*>`, а иначе -- вернуть первый, у кого `returned` -- `True`

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +    ReturnableCalculation x True >>= ReturnableCalculation f True = ReturnableCalculation x True
`ReturnableCalculation f True` после `>>=` -- неверно. Там функция ожидается

2023-12-24 23:18 UTC, pluralia commented on src/MyLib.hs
> +    ReturnableCalculation x False >>= _ = ReturnableCalculation x False
Перепутана реализация для True/False

2023-12-25 10:06 UTC, jmkostina commented on src/MyLib.hs
> +-- мы фиксируем тип одного из параметров (так в Either a b -> два параметра, но мы можем менять тип b)
Да, теперь понятно)

2023-12-25 10:07 UTC, jmkostina commented on src/MyLib.hs
> +-- я не поняла как задать
Нет, я поняла, что происходит

2023-12-25 10:12 UTC, jmkostina commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
Да, у нас же тип 
`maybe :: b -> (a -> b) -> Maybe a -> b  -- Defined in ‘Data.Maybe’`
Самой функции `maybe` нужно передать функцию, которая преобразует `(a -> b) `, без нее просто не заработает, я не могу ничего не передать

2023-12-25 10:23 UTC, jmkostina commented
Я поправила по вашим комментариям, но там все равно ошибки в ожидаемых типах. 
Предлагаю закрыть PR, потому что сейчас сидеть только над этим заданием не очень много смысла

2023-12-25 21:06 UTC, pluralia commented on src/MyLib.hs
> +                updEnv = M.insert (name x) (maybe 0 show (newVal)) env
Подсказки
* Тип `a` может быть равен типу `b`
* Более того: того, что тебе приходит здесь для распаковки из `Just` -- это `Int`. И ровно его ты и хочешь положить в environment

2023-12-25 21:12 UTC, pluralia commented
> Я поправила по вашим комментариям, но там все равно ошибки в ожидаемых типах.

Не везде доправила

> Предлагаю закрыть PR, потому что сейчас сидеть только над этим заданием не очень много смысла

Хорошо, закрываю

2023-12-25 21:12 UTC, closed without merging