HW11_ShchukinIA
pluralia/fp-fall-2023 pull request #82
Opened 2023-12-12 09:21 UTC by paiksonn

Как хорошо, когда не нужно писать тесты...

2023-12-20 13:37 UTC, pluralia requested changes

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- Тут `seq` помогает, он гарантирует, что пара p и значение n' будут вычислены перед рекурсивным вызовом baz
После разбора 2 предыдущих заданий подумай, пожалуйста, над ответом еще раз. Помогает ли здесь seq?

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- Аналогично предыдущему, тут `seq` помогает, он гарантирует, что x', y', n' будут вычислены перед рекурсивным вызовом baz
Вот тут это правда: мы вычисляем именно x' и y', а не p
Единственное -- n' вычислился бы и без seq из-за паттер-матчинга

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- потому что когда Haskell вычисляет кортеж (result + n, ()), он оценивает result + n до WHNF из-за того,
Т.е. ты помнишь про это? В предыдущем задании с `baz` то же самое

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- что кортеж является строгой структурой данных. Получается, что оператор $! не несет дополнительной нагрузки в данной ситуации,
> что кортеж является строгой структурой данных

А какие есть нестрогие? А список -- строгая?

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- Каждый раз, когда вызывается mySum, Haskell сразу обрабатывает выражение (result + n, ()) до WHNF,
В какой форме находится `(result + n, ())`? В какой момент происходит вычисление `result + n`?

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- Арифметические операции в Haskell применимы только к вычисленным (оцененным) значениям, следовательно, n будет вынужденно вычислен перед каждым рекурсивным вызовом mySum
Ну, почти. Оно все могло бы и отложиться, но не отложится из-за паттерн-матчинга.
Продолжи это объяснение самостоятельно -- после объяснений в задании 5 про `foo` должно быть понятно, как это сделать

2023-12-20 13:37 UTC, pluralia commented on hw11.hs
> +-- let small' = small seq fst (small, large) in ... small' ...
Ну, тут будет вычислен small, а large останется нетронутым. Понимаешь, почему? Есть другие варианты?

2023-12-20 17:41 UTC, paiksonn commented on hw11.hs
> +-- Тут `seq` помогает, он гарантирует, что пара p и значение n' будут вычислены перед рекурсивным вызовом baz
После разбора мне стало понятнее и теперь могу сказать, что нет, тут seq никак не помогает, ведь n вычисляется явно (спасибо паттерн-матчинг), а также seq не требует вычисления x' и y' до конечных значений; он просто убедится, что p — это кортеж
Значит тут seq не нужен

2023-12-20 17:41 UTC, paiksonn commented on hw11.hs
> +-- Аналогично предыдущему, тут `seq` помогает, он гарантирует, что x', y', n' будут вычислены перед рекурсивным вызовом baz
Да, именно в явном вычислении x', y' тут отличие от предыдущего примера и тут seq работает 
Теперь я это понимаю :)

2023-12-20 17:41 UTC, paiksonn commented on hw11.hs
> +-- что кортеж является строгой структурой данных. Получается, что оператор $! не несет дополнительной нагрузки в данной ситуации,
Я тут коряво написал, теперь знаю, что это неверно

2023-12-20 17:41 UTC, paiksonn commented on hw11.hs
> +-- Каждый раз, когда вызывается mySum, Haskell сразу обрабатывает выражение (result + n, ()) до WHNF,
1. кортеж (result + n, ()) уже находится в WHNF независимо от вычисления result + n
2. вычисление result + n не произойдет до того, как это значение не будет явно использовано

2023-12-20 17:41 UTC, paiksonn commented on hw11.hs
> +-- let small' = small seq fst (small, large) in ... small' ...
Да, понимаю
Можно по-другому сделать так:
`let !small' = fst (small, large) in ... small' ...`

Хотя все еще кажется, что в этом примере самый простой вариант - не создавать себе лишних проблем и сделать так: 
`let small' = small in ... small' ...`

2023-12-20 22:36 UTC, pluralia commented on hw11.hs
> +-- Арифметические операции в Haskell применимы только к вычисленным (оцененным) значениям, следовательно, n будет вынужденно вычислен перед каждым рекурсивным вызовом mySum
Не продолжил объяснение

2023-12-20 22:37 UTC, pluralia commented on hw11.hs
> +-- Каждый раз, когда вызывается mySum, Haskell сразу обрабатывает выражение (result + n, ()) до WHNF,
2. Когда оно будет явно использовано?
3. Как тогда выглядит ответ на исходный вопрос 6b?

2023-12-20 22:37 UTC, pluralia commented on hw11.hs
> +-- что кортеж является строгой структурой данных. Получается, что оператор $! не несет дополнительной нагрузки в данной ситуации,
А как верно?

2023-12-20 22:39 UTC, pluralia commented on hw11.hs
> +    -- Это WHNF по определению WHNF
Да, редексов тут нет, поэтому это в первую очередь NF. Строго говоря, любая NF -- это еще и WHNF, но в задании мы хотим, очевидно, наиболее узкую подгруппу указать

2023-12-20 22:41 UTC, pluralia commented on hw11.hs
> +-- Она не может привести к расходимости, потому что не производит никаких вычислений со своим аргументом, а просто его возвращает
Верно говоришь, но дело в том, что нас как раз расхождение в момент вызова и интересует

2023-12-20 22:41 UTC, pluralia commented on hw11.hs
> +-- Таким образом, функция grault не содержит никаких вызовов, которые могли бы привести к расходимости и она всегда возвращает первый аргумент
https://github.com/pluralia/fp-fall-2023/pull/82#discussion_r1433252054

2023-12-20 22:42 UTC, pluralia commented on hw11.hs
> +-- Тут просто всегда будет возвращаться символ 'q', игнорируя аргумент типа Integer
Намудрил. Что будет, если вторым аргументом отправить undefined?

2023-12-21 05:42 UTC, paiksonn commented on hw11.hs
> +    -- Это WHNF по определению WHNF
Ну, да, это так, я согласен 
Я изначально просто опирался на определение WHNF, которое представлено чуть выше в коде, поэтому и написал так

2023-12-21 05:46 UTC, paiksonn commented on hw11.hs
> +-- Она не может привести к расходимости, потому что не производит никаких вычислений со своим аргументом, а просто его возвращает
А, ну тогда это другой вопрос, если в момент вызова, то можно придумать, какие доп функции использовать, чтобы сломать (вызвать расхождение) и я даже привел пример в прошлом ответе
Просто задание звучит как `Какие из нижеперечисленных функций не могут привести к расходимости (неостановке вычисления)? Почему?` и я отсюда не понял, что это не про функцию конкретно, а про ее контекст использования

2023-12-21 05:52 UTC, paiksonn commented on hw11.hs
> +-- Таким образом, функция grault не содержит никаких вызовов, которые могли бы привести к расходимости и она всегда возвращает первый аргумент
Ну, ответ, собственно, будет как в моем комментарии выше.
Если мы выдумываем, какие функции можно применить, чтобы сломать нашу исходную функцию, а не рассматриваем только ее саму, то вариантов масса
Например:
`main = print $ length (grault [1..] 5)`

2023-12-21 06:02 UTC, paiksonn commented on hw11.hs
> +-- Тут просто всегда будет возвращаться символ 'q', игнорируя аргумент типа Integer
Функция `garply` принимает один аргумент типа `Integer` и возвращает `Char`
Если мы дадим ей `undefined` на вход, то она у нас вызовет `grault` с аргументами 'q' undefined
А т.к. undefined - не число, хаскель не сможет сравнить его с нулем и вылетит с ошибкой

2023-12-21 06:05 UTC, paiksonn commented on hw11.hs
> +-- что кортеж является строгой структурой данных. Получается, что оператор $! не несет дополнительной нагрузки в данной ситуации,
потому что когда Haskell вычисляет кортеж (result + n, ()), он оценивает result + n до WHNF, а оператор $! вычисляет аргумент до WHNF перед передачей его в функцию, и значит ему тут делать нечего

2023-12-21 06:31 UTC, paiksonn commented on hw11.hs
> +-- Каждый раз, когда вызывается mySum, Haskell сразу обрабатывает выражение (result + n, ()) до WHNF,
2.  Когда мы вызовем функцию `goSum` с каким-нибудь аргументом `n :: Integer` и затем в стеке рекурсивных вызовов функции `mySum` по паттерн-матчингу n == 0 и тогда вычисления развернутся 
3. Да, отложенные вычисления будут накапливаться, ведь на каждом шаге рекурсии создается новый thunk для result + n, и эти thunk'и будут накапливаться, формируя цепочку невычисленных операций

2023-12-21 06:31 UTC, paiksonn commented on hw11.hs
> +-- Арифметические операции в Haskell применимы только к вычисленным (оцененным) значениям, следовательно, n будет вынужденно вычислен перед каждым рекурсивным вызовом mySum
Не совсем понимаю, а что именно тут продолжить
Действительно всё так - отложенные вычисления по второму аргументу накапливаться не будут, ведь там есть паттерн-матчинг на условие равенства нулю второго аргумента и он будет вычисляться на каждом шаге рекурсии и это ровно такая же ситуация, что и в 5 задании в функции `foo` с первым аргументом
Т.е. мы получим строго убывающую последовательность чисел до тех пор, пока n не дойдет до нуля вследствие выполнения вычитания

2023-12-21 10:57 UTC, pluralia commented on hw11.hs
> +-- Тут просто всегда будет возвращаться символ 'q', игнорируя аргумент типа Integer
Что это означает для функции garply? Расходится ли она?

2023-12-21 11:00 UTC, pluralia commented on hw11.hs
> +-- Тут просто всегда будет возвращаться символ 'q', игнорируя аргумент типа Integer
@paiksonn, раз мы вылетели с ошибкой, значит, разошлись

2023-12-21 11:00 UTC, pluralia commented
👍

2023-12-21 11:00 UTC, closed without merging

2023-12-21 11:06 UTC, paiksonn commented on hw11.hs
> +-- Тут просто всегда будет возвращаться символ 'q', игнорируя аргумент типа Integer
Получается что так. Значит, в теории, функция `garply` может разойтись