hw11_Pushkina
pluralia/fp-fall-2023 pull request #83
Opened 2023-12-14 12:48 UTC by forestcream

2023-12-20 13:35 UTC, pluralia requested changes

2023-12-25 07:05 UTC, forestcream commented on hw11.hs
> +    -- fst (1,0) - NF, может быть полностью вычислено
Сейчас оно еще не вычислено, но оно как будто просто выражение ни в какой форме (типа просто thunk?)

2023-12-25 07:10 UTC, forestcream commented on hw11.hs
> +-- не может, так как мы на вход подаем строго целые числа, и не получится сделать бесконечные вычисления
сам foo да, принимает не обязательно целые числа 
![image](https://github.com/pluralia/fp-fall-2023/assets/20926830/66f9d190-b941-4303-bad3-b6bf706b3302)
но con же уже дает ограничения. и con. foo тоже уже работает с целыми числами 
![Uploading image.png…]()

2023-12-25 07:14 UTC, forestcream commented on hw11.hs
> +-- видно, не может, у меня при вызове на бесконечных списках вылетала ошибка
Что определен Num, но не определен Foldable, из-за этого бесконечный список не может вычиститься

2023-12-25 07:15 UTC, forestcream commented on hw11.hs
> +-- возможно это связано с ограничением Num
Что определен Num, но не определен Foldable, из-за этого бесконечный список не может вычиститься

2023-12-25 07:17 UTC, forestcream commented on hw11.hs
> +-- так же не может, все время возвращает 'q'
нет, если приходит 0, то мы просто возвращаем первый аргумент, если что-то другое, то нам все равно не нужно это вычислять и мы можем просто вернуть первый аргумент

2023-12-25 07:22 UTC, forestcream commented on hw11.hs
> +-- не может, вызываемся только на числах
Вообще по логике не должно - нам не нужно "вычислять" undefined, чтобы вернуть q, но у меня выдается ошибка при попытке вызвать
![Uploading image.png…]()

2023-12-25 07:30 UTC, forestcream commented on hw11.hs
> +-- мы заставляем вычислить p и n перед тем, как вызвать рекурсивно функцию, что тоже не дает накапливать стэк вычислений
нет, потому что опять из-за вычисления только до WHNF у нас вычисления baz будут накапливаться до конца

2023-12-25 07:35 UTC, forestcream commented on hw11.hs
> +-- потому что у нас и так рекурсивный вывод, ради которого нужно вычислить аргументы, которые передать дальше
`(result + n, ())?` в WHNF, который бы и так вычислялся без форсирования

2023-12-25 07:36 UTC, forestcream commented on hw11.hs
> +-- нет, они будут вычисляться на каждом шаге, так как мы передаем в рекурсивный вызов уже result + n
сразу при уменьшении n

2023-12-25 07:37 UTC, forestcream commented on hw11.hs
> +-- да, будут, так как нам нужен результат n, только в конце  и пока он не потребуется, вычисления будут откладываться
не будут, так как нам иначе паттерн-матчинг не сравнить

2023-12-25 08:07 UTC, forestcream commented on hw11.hs
> +-- исправить можно просто используя не кортеж, а все по отдельности
```haskell
-- let large' = large
-- let small' = small in ... small' ...
```

2023-12-25 18:18 UTC, pluralia commented on hw11.hs
> +    -- fst (1,0) - NF, может быть полностью вычислено
Да, это thunk, но важно, что thunk, NF и WHNF все же не на одном уровне концепций: thunk -- не форма выражения

2023-12-25 18:20 UTC, pluralia commented on hw11.hs
> +-- возможно это связано с ограничением Num
С Foldable тут бы спас, да. Или тип `p -> [a] -> p`

2023-12-25 18:21 UTC, pluralia commented on hw11.hs
> +-- так же не может, все время возвращает 'q'
Как насчет `prod [1..]` или `undefined`?

2023-12-25 18:23 UTC, pluralia commented on hw11.hs
> +-- не может, вызываемся только на числах
undefined придется вычислять, потому что он отправится в функцию `grault` в качестве второго аргумента, где появится необходимость его паттернматчить

2023-12-25 18:23 UTC, pluralia commented on hw11.hs
> +-- потому что у нас и так рекурсивный вывод, ради которого нужно вычислить аргументы, которые передать дальше
Да

2023-12-25 18:26 UTC, pluralia commented on hw11.hs
> +-- нет, они будут вычисляться на каждом шаге, так как мы передаем в рекурсивный вызов уже result + n
Вычисления будут накапливаться и произойдут только в самом конце, потому что их некому форсировать

2023-12-25 18:30 UTC, pluralia commented on hw11.hs
> +-- исправить можно просто используя не кортеж, а все по отдельности
> Можешь прямо код написать, который бы использовал пройденные инструменты форсирования?

Твой код не использует. Проблема в том, что нам мог прийти именно кортеж, из которого бы нужно было достать 1 элемент, поэтому использовать let не вариант

2023-12-25 18:31 UTC, pluralia commented
* Не везде правильно ответила на вопросы и нет времени доотвечать, поэтому -1
* -1 за 7
* 8 баллов в итоге

2023-12-25 18:31 UTC, closed without merging