HW11_Shishkina
pluralia/fp-fall-2023 pull request #85
Opened 2023-12-14 21:21 UTC by SophiaLaz

2023-12-20 13:34 UTC, pluralia requested changes

2023-12-20 13:34 UTC, pluralia commented on src/MyLib.hs
> +            in f' `seq` x' `seq` bar x' f' v
`seq` вычисляет только до WHNF.
`f'` -- это WHNF и не вычислится дальше, а `x'` -- вычислится и без `seq` из-за паттерн-матчинга при рекурсивном вызове `bar`. Поэтому здесь оба использования `seq` ничего не дают

Если бы паттерн-матчинга не было, то seq был бы полезен для `x'`

2023-12-20 13:34 UTC, pluralia commented on src/MyLib.hs
> +baz :: (Eq t, Num t, Num a) => t -> (a, a) -> a         -- Тут не помогает для `p`, потому что мы форсируем вычисления `p` до WHNF,
Молодец!

2023-12-20 13:34 UTC, pluralia commented on src/MyLib.hs
> +mySum (result, ()) n = (mySum $! let !x' = result + n in (x', ())) $ n - 1
Верно!

2023-12-20 13:34 UTC, pluralia commented on src/MyLib.hs
> +-- 2.  Не накапливать вычисления `large`, а форсировать их (если когда-то он нам всё же может пригодиться) -> это позволит
Как? Хочется увидеть использование пройденных инструментов

2023-12-20 13:34 UTC, pluralia commented on src/MyLib.hs
> +-- 3.* Установить следующий флаг в сборочном файле .cabal:
❤️

2023-12-21 18:33 UTC, SophiaLaz commented on src/MyLib.hs
> +            in f' `seq` x' `seq` bar x' f' v
точно, забыла про паттерн-матчинг
тогда не помогает в обоих случаях, да

2023-12-23 20:41 UTC, SophiaLaz commented on src/MyLib.hs
> +    -- \x -> x                  -- WHNF, так как просто возвращаем x, не обращая внимания на то, какой он
Поняла ошибку. Тут ничего нельзя больше вычислить, значит это нормальная форма (NF)

2023-12-23 20:42 UTC, SophiaLaz commented on src/MyLib.hs
> +                                            -- с конечным аргументом, который и вернётся в качестве результата исходной функции
Да, может, так как мы паттерн-матчимся по `y` (была невнимательна в прошлый раз и не заметила этого))

2023-12-23 20:51 UTC, SophiaLaz commented on src/MyLib.hs
> +myFoldl' f !ini (!x:xs) = myFoldl' f (f ini x) xs
Так как у нас есть паттерн-матчинг на проверку наличия головы списка, то мы должны будем проверить это (то есть раскроем `(:)`). Но проверка будет на уровне thunk'ов - т.е. есть ли голова `thunk: someFunc(x) >` или там просто `[]`. Для случая, если голова есть, мы не будем форсировать вычисления, так как нам не важно конкретное значение головы, а `!x` форсирует их. 
Пример (подаём список с невычисленными элементами): `[1 + 2, 2 + 3, ...]`

2023-12-23 20:58 UTC, SophiaLaz commented on src/MyLib.hs
> +-- 2.  Не накапливать вычисления `large`, а форсировать их (если когда-то он нам всё же может пригодиться) -> это позволит
```haskell
let !small' = fst (small, large) in ... small' ...  
let small' = fst (small, large) in small'  `seq` ... small' ...   
```

2023-12-23 20:59 UTC, pluralia commented on src/MyLib.hs
> +                                            -- с конечным аргументом, который и вернётся в качестве результата исходной функции
Приведи, пожалуйста, пример такого аргумента

2023-12-25 09:00 UTC, SophiaLaz commented on src/MyLib.hs
> +                                            -- с конечным аргументом, который и вернётся в качестве результата исходной функции
`prod [1..]`

2023-12-25 10:26 UTC, pluralia commented
👍

2023-12-25 10:26 UTC, closed without merging