HW11_ManasyanAL
pluralia/fp-fall-2023 pull request #86
Opened 2023-12-15 09:55 UTC by Artem9999999999999999999999

2023-12-20 13:32 UTC, pluralia requested changes

2023-12-20 13:32 UTC, pluralia commented on hw11.hs
> +В этой функции seq перед f' и x' имеет смысл. Он заставляет вычислить f' и x' до WHNF, прежде чем продолжить вычисление. Это может предотвратить накопление отложенных вычислений.
`seq` вычисляет только до WHNF.
`f'` -- это WHNF и не вычислится дальше, а `x'` -- вычислится и без `seq` из-за паттерн-матчинга при рекурсивном вызове `bar`. Поэтому здесь оба использования `seq` ничего не дают

Если бы паттерн-матчинга не было, то seq был бы полезен для `x'`

2023-12-20 13:32 UTC, pluralia commented on hw11.hs
> +В данной функции использование seq перед p и n' имеет смысл. Это может предотвратить накопление отложенных вычислений, так как p зависит от (x', y'), и n' зависит от n - 1.
Объяснения довольно формальные: все под копирку без объяснения сути. Как именно seq помогает?

После разбора 2 предыдущих заданий подумай, пожалуйста, над ответом еще раз

2023-12-20 13:32 UTC, pluralia commented on hw11.hs
> +Это происходит потому, что второй аргумент mySum уже является значением типа (), который является типом данных с единственным конструктором, не имеющим полей.
Посмотри, пожалуйста, внимательнее. У нас здесь частичное применение и второй аргумент `mySum` имеет тип `a` -- это первый аргумент `goSum`.

Попробуй ответить на исходный вопрос еще раз.

2023-12-20 13:32 UTC, pluralia commented on hw11.hs
> +В данной рекурсивной функции mySum, накопление отложенных вычислений будет происходить в первом аргументе (result, ()).
Верно!

2023-12-20 13:32 UTC, pluralia commented on hw11.hs
> +Нет, отложенные вычисления не будут накапливаться во втором аргументе mySum, поскольку тип () не имеет полей,
Здесь та же проблема, что и в 6a: второй аргумент mySum имеет тип a. Ответь, пожалуйста, еще раз на этот вопрос

2023-12-21 19:16 UTC, Artem9999999999999999999999 commented on hw11.hs
> +В WHNF, так как это лямбда-выражение.
Да, вы правы тут уже нечего вычислять, значит это NF форма, если бы мы каким-то образом модифицировали значение, например, ```\x -> x * 2 ```, то было бы WHNF

2023-12-21 19:16 UTC, Artem9999999999999999999999 commented on hw11.hs
> +может уйти в бесконечную рекурсию, если аргумент отрицательный
Функция игнорирует первый аргумент типа b и возвращает функцию, которая соответствует сигнатуре функции foo. Это значит, что возвращаемая функция ожидает два целочисленных аргумента и вернет целое число. В данном конкретном случае, con всегда будет возвращать функцию foo, независимо от значения первого аргумента. При этом, если сама функция foo является расходящейся, то и con будет таковой

2023-12-21 19:16 UTC, Artem9999999999999999999999 commented on hw11.hs
> +Не вызовет расходимость. Она просто вызывает grault 'q', что является безопасным вызовом функции grault.
Да, можем подать на вход underfined, так как он не является числом, то мы не сможем сравнить его с 0 и функция отработает с ошибкой, то есть получим расхождение

2023-12-21 19:17 UTC, Artem9999999999999999999999 commented on hw11.hs
> +В данной функции использование seq перед p и n' имеет смысл. Это может предотвратить накопление отложенных вычислений, так как p зависит от (x', y'), и n' зависит от n - 1.
Получается, что благодаря паттерн-матчингу n вычисляется явно, при этом вычислять x' и y' до конца seq не требует, ему достаточно проверки на то, что p является кортежем, а значит, что и seq здесь не нужен

2023-12-21 19:17 UTC, Artem9999999999999999999999 commented on hw11.hs
> +Это происходит потому, что второй аргумент mySum уже является значением типа (), который является типом данных с единственным конструктором, не имеющим полей.
В этом примере (result + n, ()) уже вычислено до WHNF, то есть вычисление и так будет строгим, а значит оператор $! тут redundant

2023-12-21 19:18 UTC, Artem9999999999999999999999 commented on hw11.hs
> +Нет, отложенные вычисления не будут накапливаться во втором аргументе mySum, поскольку тип () не имеет полей,
Все еще нет, но потому что паттерн-матчинг происходит по значению второго аргумента явно, а значит он будет вычисляться до конца

2023-12-21 19:26 UTC, closed without merging

2023-12-21 19:26 UTC, pluralia commented
👍