HW11_Dmitriev
pluralia/fp-fall-2023 pull request #87
Opened 2023-12-16 08:53 UTC by qilowoq

2023-12-20 13:31 UTC, pluralia requested changes

2023-12-20 13:31 UTC, pluralia commented on hw11.hs
> +-- поможет. тк f' и x' будут вычислены до WHNF
`seq` вычисляет только до WHNF.
`f'` -- это WHNF и не вычислится дальше, а `x'` -- вычислится и без `seq` из-за паттерн-матчинга при рекурсивном вызове `bar`. Поэтому здесь оба использования `seq` ничего не дают

Если бы паттерн-матчинга не было, то seq был бы полезен для `x'`

2023-12-20 13:31 UTC, pluralia commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
В какой форме находится `p`?

После разбора 2 предыдущих заданий подумай, пожалуйста, над ответом еще раз. Обрати внимание на форсирование вычислений из-за паттерн-матчинга

2023-12-20 13:31 UTC, pluralia commented on hw11.hs
> +-- Чтобы исправить можно написать
А если мы так не можем написать? `(small, large)` пришло нам в качестве аргумента. Как исправить проблему с утечкой, используя изученные инструменты?

2023-12-21 10:17 UTC, qilowoq commented on hw11.hs
> +    -- fst (1,0) - WHNF - можно упростить
Пон. Я написал в файлике условия для WHNF. Но эта штука не выполняет их и о чевидно она не в NF. Значит и не и не NF, и не WHNF

2023-12-21 10:47 UTC, qilowoq commented on hw11.hs
> +-- может. например con 1 (- 1) 10
Я вроде написал с чем связано, а foo определена ниже по дз

2023-12-21 10:49 UTC, qilowoq commented on hw11.hs
> +-- не может.
Нет не может. Компилятор не будет трогать второй аргумент каким бы целым числом он ни был.

2023-12-21 10:59 UTC, qilowoq commented on hw11.hs
> +-- поможет. тк f' и x' будут вычислены до WHNF
Пон

2023-12-21 11:03 UTC, pluralia commented on hw11.hs
> +-- может. например con 1 (- 1) 10
> С чем это связано? Что такое foo?

Тут хотелось, чтобы ты про foo порассуждал: почему foo расходится?

2023-12-21 11:03 UTC, pluralia commented on hw11.hs
> +-- не может.
Что будет, если я отправлю в качестве второго аргумента undefined?

2023-12-21 11:12 UTC, qilowoq commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
`p` - кортеж `(x', y')`, а `x'` и `y'` являются вычисленными значениями. Это означает, что `p` находится в NF, так как все его подвыражения вычислены.

2023-12-21 11:15 UTC, qilowoq commented on hw11.hs
> +-- Чтобы исправить можно написать
Так наверное
```haskell
let small' = fst (small, large) in small' `seq` ... small' ...

```

2023-12-21 11:37 UTC, qilowoq commented on hw11.hs
> +-- может. например con 1 (- 1) 10
Это все про foo 

```
-- если y < 0 то расходится тк при каждом вызове con
-- y <- y - 1 и так до бесконечности тк единственный способ остановиться это y == 0
```

Я не думаю, что могу написать еще подробнее

2023-12-21 11:38 UTC, qilowoq commented on hw11.hs
> +-- не может.
Ошибка

```
ghci> garply undefined
*** Exception: Prelude.undefined
CallStack (from HasCallStack):
  undefined, called at <interactive>:2:8 in interactive:Ghci1
```

2023-12-21 11:55 UTC, pluralia commented on hw11.hs
> +-- не может.
Это и есть расходимость. Т.е. garply расходится

2023-12-21 11:57 UTC, pluralia commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
> x' и y' являются вычисленными значениями

Кто их вычислил?

2023-12-21 12:26 UTC, qilowoq commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
Согласен. Не являются вычисленными. Ну как минимум в WHNF `p` находится

2023-12-21 12:59 UTC, pluralia commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
Вернемся к исходному вопросу: поможет ли тогда seq в этом примере?

2023-12-21 14:50 UTC, qilowoq commented on hw11.hs
> +-- поможет. тк p и n' будут вычислены до WHNF
Из-за того, что мы паттернматчимся по аргументам `baz`, то оба `seq` не нужны

2023-12-21 15:04 UTC, pluralia commented
👍

2023-12-21 15:04 UTC, closed without merging