HW02_Dmitriev
pluralia/fp-fall-2023 pull request #9
Opened 2023-10-12 15:30 UTC by qilowoq

2023-10-13 18:02 UTC, pluralia requested changes
Хочется более разнообразных тестов: длину списков поинтереснее, например

2023-10-13 18:02 UTC, pluralia commented on hw2/test/TestSpec.hs
> +    it "returns the correct result" $ do
Больше списков разной длины

2023-10-13 18:02 UTC, pluralia commented on hw2/test/TestSpec.hs
> +    it "returns the correct result" $ do
Более длинные списки?

2023-10-13 18:02 UTC, pluralia commented on hw2/test/TestSpec.hs
> +    it "returns the correct result" $ do
Более длинные списки?

2023-10-13 18:02 UTC, pluralia commented on hw2/test/TestSpec.hs
> +    it "returns the correct result" $ do
Больше тестов на различные деревья

2023-10-13 18:02 UTC, pluralia commented on hw2/test/TestSpec.hs
> +    it "returns the correct result" $ do
Больше тестов на различные деревья

2023-10-13 23:22 UTC, qilowoq commented on hw2/src/MyLib.hs
> +    y  = last xs
Из-за того, что У нас Linked List, то вытащить last получается только за O(n). А init видимо создает новый список тоже за O(n). И это на каждом шагу

2023-10-13 23:25 UTC, qilowoq commented on hw2/src/MyLib.hs
> +-- С левой сверткой не заходил
Я уже не помню что мне не понравилось. Я хотел использовать `L.foldl'`

2023-10-13 23:26 UTC, qilowoq commented on hw2/src/MyLib.hs
> +last' = foldl (\_ y -> Just y) Nothing
Можем воспользоваться ленивостью

2023-10-13 23:31 UTC, qilowoq commented on hw2/src/MyLib.hs
> +head' :: [a] -> Maybe a
Используем ленивость. `foldr` возмет самый левый элемент и не будет трогать другие. С `last` все наоборот

2023-10-13 23:32 UTC, qilowoq commented on hw2/src/MyLib.hs
> +take' n = L.foldl' (\x y -> if length' x < n then x ++ [y] else x) []
`:` работает за O(1). А `++` за O(length x) получается.

2023-10-13 23:34 UTC, qilowoq commented on hw2/src/MyLib.hs
> +insert xs val = foldr helper [val] xs
Я специально делал со сверткой . . .

2023-10-14 15:44 UTC, pluralia commented on hw2/src/MyLib.hs
> +last' = foldl (\_ y -> Just y) Nothing
Зачем нам здесь ленивость?

2023-10-14 15:44 UTC, pluralia commented on hw2/src/MyLib.hs
> +insert xs val = foldr helper [val] xs
Окей )

2023-10-14 16:16 UTC, qilowoq commented on hw2/src/MyLib.hs
> +last' = foldl (\_ y -> Just y) Nothing
Наверное, все же будет лучше без нее. Чтобы память не засорять, тк нам все равно прохрдиться по всем элементам

2023-10-15 14:12 UTC, pluralia requested changes
👍

2023-10-15 14:12 UTC, closed without merging