HW12_ShchukinIA
pluralia/fp-fall-2023 pull request #91
Opened 2023-12-21 14:57 UTC by paiksonn

No warnings and 1 hlint suggestion described in code

2023-12-23 22:26 UTC, pluralia requested changes
Планируешь добить 8 задание?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +  lift m = LoggerT $ m >>= \a -> return (Logged [] a)
Верно, но можно использовать fmap

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +modifyingLogging def p f = do
Можно ли здесь убрать lift? Почему?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +import Control.Monad.Trans.State (get, put)
У тебя тут State из обоих пакетов. Какой оставить лучше?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +    then do
Нужно ли do?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +    then do
Нужно ли do?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +  log level message = LoggerT $ return (Logged [(level, message)] ())
writeLog?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
Нужно выбрать какой-нибудь один пакет. Какой? В чем между ними разница?

2023-12-23 22:26 UTC, pluralia commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
Поясни, пожалуйста, выбор порядка заворачивания монад

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +  (LoggerT mfunc) <*> (LoggerT mval) = LoggerT $ (combineLogs <$> mfunc) <*> mval
Да, чтобы компилятор понимал правильный порядок операций

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +  fail msg = LoggerT $ fail msg >>= return . Logged []
Вот так?
```haskell
instance MonadFail m => MonadFail (LoggerT m) where
  fail :: String -> LoggerT m a
  fail msg = LoggerT $ fail msg
```

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +  lift m = LoggerT $ m >>= \a -> return (Logged [] a)
Вот так?
```haskell
instance MonadTrans LoggerT where
  lift :: Monad m => m a -> LoggerT m a
  lift m = LoggerT $ fmap (\a -> Logged [] a) m
```

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +    then do
Нет,  просто все еще тащу опыт/привычки из программирования в императивных языках 
Постараюсь от этого избавиться

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +modifyingLogging def p f = do
Нет, нельзя, потому что функция `modifyingLogging` работает внутри монадического трансформера `LoggerT`, который действует поверх `StateT`. Когда мы хотим выполнить действия, принадлежащие базовой монаде (StateT s m в данном случае), необходимо "поднять" их в контекст `LoggerT`

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +    then do
Аналогичный ответ, как у предыдущего комментария - нет, не нужен, это просто моя привычка так писать ифы

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +  log level message = LoggerT $ return (Logged [(level, message)] ())
Да, забыл про него совсем)
Будет так:
```haskell
instance Monad m => MonadLogger (LoggerT m) where
  log level message = writeLog level message
```

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
Разница в том, что они принадлежат разным пакетам:
- Control.Monad.Trans.State принадлежит пакету transformers
- Control.Monad.State является частью пакета mtl

Лучше, наверное, оставить Control.Monad.State, оно побогаче на инструментарий будет

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
У нас тут как бы несколько уровней монад, сейчас попробую объяснить, почему я их именно так завернул:
Верхний уровень:
Это `ExceptT` - чтобы все монады внутри могли бросать ошибки, которые, собственно,  `ExceptT` и будет обрабатывать 

Средний уровень:
Сначала идет `StateT` - чтобы возможность хранения и изменения состояния была доступной в пределах логирования и ввода/вывода
Затем идет `LoggerT` - он оборачивает монаду IO для логирования на каждом шаге выполнения IO-действий, при этом не меняя самого состояния

Нижний уровень:
Это монада `IO` - для IO-вычислений, это база

2023-12-24 08:56 UTC, paiksonn commented on lib/MyLib.hs
> +import Control.Monad.Trans.State (get, put)
Я там в одном из комментариев ниже написал, что лучше оставить `Control.Monad.State`, на мой взгляд

2023-12-24 08:59 UTC, paiksonn commented
> Планируешь добить 8 задание?

Честно говоря, я не уверен, что успею его добить нормально до дедлайна, оно довольно сложное, а подготовка к экзамену важнее
Поэтому, наверное, отвечу нет и потом, в свободное время, покопаюсь в нем спокойно  и никуда не торопясь

2023-12-24 22:02 UTC, pluralia commented
Хорошо. Пингани, если решишь доделать -- посмотрю)

2023-12-24 22:03 UTC, pluralia commented on lib/MyLib.hs
> +modifyingLogging def p f = do
Мы выше реализовали инстанс `MonadTrans` -- не поможет ли он нам здесь?

2023-12-24 22:04 UTC, pluralia commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
> Лучше, наверное, оставить Control.Monad.State, оно побогаче на инструментарий будет

Поясни, пожалуйста

2023-12-24 22:06 UTC, pluralia commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
> Это ExceptT - чтобы все монады внутри могли бросать ошибки, которые, собственно, ExceptT и будет обрабатывать

ExceptT -- не бросание ошибок (а что?)

> Затем идет LoggerT - он оборачивает монаду IO для логирования на каждом шаге выполнения IO-действий, при этом не меняя самого состояния

Но ведь мы хотим логгировать еще и изменение состояния (и может что-то еще?)

2023-12-25 09:21 UTC, paiksonn commented on lib/MyLib.hs
> +modifyingLogging def p f = do
Я, честно говоря, не понимаю, как инстанс с реализацией `lift` должен помочь убрать этот самый `lift`

2023-12-25 09:21 UTC, paiksonn commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
Я имел ввиду, что согласно тому, что было у нас в лекции, пакет transformers - это базовый пакет с голыми трансформерами (т.е. все определено на более низком уровне)
А пакет mtl - это надстройка над предыдущим пакетом, которая, по сути, расширяет возможности transformers

2023-12-25 09:21 UTC, paiksonn commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
ExceptT - это не бросание ошибок, возможно я некорректно выразился. Я имел ввиду, что он нужен для обработки вычислений, которые могли завершиться с ошибкой

Мы можем поменять местами монады `StateT` и `LoggerT`, в этом случае все логи, записанные в процессе изменения состояния, останутся внутри LoggerT, даже если операции StateT приведут к изменению состояния, которое затем отбросится из-за ошибки

2023-12-25 18:53 UTC, pluralia commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
Верно! Как именно? Если ответишь на этот вопрос, то сможешь ответить и на [этот](https://github.com/pluralia/fp-fall-2023/pull/91#discussion_r1436026671)

2023-12-25 18:54 UTC, pluralia commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
А если мы еще и ошибки логгировать хотим?

2023-12-26 07:39 UTC, paiksonn commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
В mtl реализован класс типов MonadReader

2023-12-26 07:47 UTC, paiksonn commented on lib/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType =
Для этого достаточно снова просто поменять местами и сделать так:
```haskell
type LoggingStateWithErrorInIO stateType errorType resType = 
  LoggerT (StateT stateType (ExceptT errorType IO)) resType
```

2023-12-26 08:00 UTC, paiksonn commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
Но все еще не понимаю, как отвечать на [этот](https://github.com/pluralia/fp-fall-2023/pull/91#discussion_r1436026671) вопрос

2023-12-26 09:43 UTC, pluralia commented on lib/MyLib.hs
> +  s <- Control.Monad.State.get
* Когда нам нужно писать `lift`? Когда мы хотим воспользоваться интерфейсом внутренней монады, чтобы остаться в типе внешней монады. Например, когда мы реализовали функцию `loggingModification`, мы работали в монаде `StateT s (LoggerT Identity) (Maybe s)` (внешняя -- `State`) и, чтобы использовать функции `LoggerT`, мы были должны писать `lift`. Однако, `StateT` реализует `MonadTrans`, поэтому `lift` можно убрать. Если у нас реализован `MonadTrans`, Haskell сам может вызвать `lift`
* в функции `modifyingLogging` мы работает с `LoggerT (StateT s m) ()`: теперь `LoggerT` внешняя, поэтому нужно было бы использовать `lift`, когда используем интерфейс `StateT`; однако, мы реализовали `MonadTrans` для `LoggerT`, поэтому `lift` можно убрать

Причем здесь mtl? Именно mtl представляет `MonadTrans` и его инстансы для основных трансформеров

2023-12-26 09:43 UTC, pluralia commented
-0,5 за то, что не ответил на вопрос, как mtl помогает убрать lift

2023-12-26 09:43 UTC, closed without merging