HW12_Dmitriev
pluralia/fp-fall-2023 pull request #92
Opened 2023-12-21 15:25 UTC by qilowoq

2023-12-23 22:27 UTC, pluralia requested changes
Планируешь ли доделывать 8 задание? Есть ли вопросы?

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +  s <- lift $ gets f
Можно ли здесь убрать lift? Почему?

Здесь тоже нужно добавить логирование

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +      return ()
do не нужно

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +modifyingLogging' def p f = do
Нет логирования

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +      return ()
do не нужно

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +  log = (lift .) . writeLog
ОО
Откуда такая красота? Был бы ты рад прочитать такой код при ревью своего коллеги-хаскеллиста?

Поставлю +0,5, если покажешь, как вывел

2023-12-23 22:27 UTC, pluralia commented on hw12/src/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType = StateT stateType (ExceptT errorType (LoggerT IO)) resType
Поясни, пожалуйста, выбор порядка заворачивания монад

2023-12-25 12:33 UTC, qilowoq commented on hw12/src/MyLib.hs
> +  s <- lift $ gets f
Нет. `MonadState` мы еще не определили

2023-12-25 12:35 UTC, qilowoq commented on hw12/src/MyLib.hs
> +      return ()
но без do не работает

2023-12-25 12:37 UTC, qilowoq commented on hw12/src/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType = StateT stateType (ExceptT errorType (LoggerT IO)) resType
`LoggerT IO`: база, позволяет производить запись в лог и выполнять IO-вычисления.

`ExceptT errorType (LoggerT IO)`: + возможность завершаться с ошибкой. 

`StateT stateType (ExceptT errorType (LoggerT IO))`: + возможность хранить состояние.

2023-12-25 12:45 UTC, qilowoq commented
8 задание не хватает времени сделать. много других предметов наложилось

2023-12-25 20:42 UTC, pluralia commented on hw12/src/MyLib.hs
> +      return ()
return () тоже не нужен

2023-12-25 20:42 UTC, pluralia commented
+0,5 за вывод log = (lift .) . writeLog
-3,5 за отсутствие 8 задания
7 в итоге

2023-12-25 20:48 UTC, pluralia commented on hw12/src/MyLib.hs
> +type LoggingStateWithErrorInIO stateType errorType resType = StateT stateType (ExceptT errorType (LoggerT IO)) resType
Это объяснение, что делает каждая из монад, но не объяснение, почему выбран такой порядок
Почему, например, мы не можем захотеть логировать изменение состояния или ошибки? А ведь мы не сможем это делать при текущем порядке

2023-12-25 20:48 UTC, pluralia commented
Переоткрываю через 3 минуты после закрытия:
1) Заметила, что нет ответа на один из вопросов
2) Нет тестов

2023-12-25 21:02 UTC, pluralia commented on hw12/src/MyLib.hs
> +  s <- lift $ gets f
Зато мы определили `MonadTrans LoggerT` -- может он нам поможет?

Чем помогает инстанцирование `MonadTrans`?

2023-12-26 14:43 UTC, pluralia commented
Нет ответа на вопросы и тестов -- -1 балл и 6 за домашку

2023-12-26 14:43 UTC, closed without merging