HW12_ManasyanAL
pluralia/fp-fall-2023 pull request #93
Opened 2023-12-21 16:06 UTC by Artem9999999999999999999999

1. Не догадался как тестировать функции из 4-6 заданий
2. 8 задание не осилил

2023-12-23 22:28 UTC, pluralia requested changes
Планируешь ли доделывать 8 задание? Есть ли вопросы?

По тестам ответила внутри ревью

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  lift ma = LoggerT $ do
do не нужно

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  currentState <- lift get
Можно ли здесь убрать lift? Почему?

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  put s = lift $ put s
Можно убрать аргумент

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +      return ()
Для чего нужна эта строчка?

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +      return ()
Для чего нужна эта строчка?

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  let modifiedState = f currentState
Можно использовать modify

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  log level msg = LoggerT $ return $ Logged [(level, msg)] ()
writeLog?

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  let modifiedState = f currentState
modify?

2023-12-23 22:28 UTC, pluralia commented on hw12/src/MyLib.hs
> +  ExceptT errorType (LoggerT (StateT stateType IO)) resType
Поясни, пожалуйста, выбор порядка заворачивания монад

2023-12-25 15:10 UTC, Artem9999999999999999999999 commented
Сделал коммит, в нем ответил на все вопросы

2023-12-25 20:51 UTC, pluralia commented on hw12/src/MyLib.hs
> +-- Этот порядок позволяет сначала выполнять IO-вычисления, затем обрабатывать состояние, записывать лог и, наконец, обрабатывать ошибки.
Можем ли мы захотеть записывать ошибки в лог?

2023-12-26 08:13 UTC, Artem9999999999999999999999 commented on hw12/src/MyLib.hs
> +-- Этот порядок позволяет сначала выполнять IO-вычисления, затем обрабатывать состояние, записывать лог и, наконец, обрабатывать ошибки.
Мне кажется, что логгировать возникающие ошибки полезная практика, поэтому внес изменения в код

2023-12-26 09:28 UTC, pluralia commented
👍

2023-12-26 09:28 UTC, closed without merging