HW10_Kostina
pluralia/fp-fall-2023 pull request #95
Opened 2023-12-22 12:50 UTC by jmkostina

Задания 1 и 2 из папки IO

2023-12-22 13:55 UTC, pluralia commented
@jmkostina, на всякий случай: мы договаривались на 3 задания

2023-12-22 14:37 UTC, jmkostina commented
Я помню. Я просто пока не поняла, как его сделать

2023-12-23 23:28 UTC, pluralia requested changes
Задание выполнено спустя рукава: я уменьшила до минимума количество заданий и готова поставить тебе за них полный балл, но только, если ты сделаешь их качественно.

Постарайся, пожалуйста, сделать их хорошо. Если есть вопросы (любые!), не стесняйся их задать

2023-12-23 23:28 UTC, pluralia commented on HW_io/task1.hs
> +    withFile logFile AppendMode $ \handle -> do
В чем разница между AppendMode и WriteMode?

2023-12-23 23:28 UTC, pluralia commented on HW_io/task1.hs
> +infLoop n count = do
Зачем нужен count?

2023-12-23 23:28 UTC, pluralia commented on HW_io/task2.hs
> +-- Реализуйте скрипт, который работает так же, как Unix-овский скрипт wc: выводит число слов, строк и байт в файле.
Нужна работа с файлом

2023-12-23 23:28 UTC, pluralia commented on HW_io/task2.hs
> +main = do
Работает вообще не как `wc`

2023-12-24 09:38 UTC, jmkostina commented on HW_io/task1.hs
> +    withFile logFile AppendMode $ \handle -> do
`WriteMode` - при повторной записи в файл все ранее записанные в него данные удаляются
`AppendMode` - при повторной записи в файл все записывается в конец, ранее имеющиеся данные не удаляются

2023-12-24 09:39 UTC, jmkostina commented on HW_io/task1.hs
> +infLoop n count = do
я ввела счетчик - количество введенных с клавиатуры записей, чтобы можно было оценивать, сколько записей у нас уже есть и не нужно ли открывать новый лог-файл

2023-12-24 09:40 UTC, jmkostina commented on HW_io/task2.hs
> +-- Реализуйте скрипт, который работает так же, как Unix-овский скрипт wc: выводит число слов, строк и байт в файле.
какая именно?

2023-12-24 09:58 UTC, jmkostina commented on HW_io/task2.hs
> +main = do
почему? Я передаю данные из файла, обрабатываю их (анализирую число строк, слов и байтов), возвращаю результат. Функционально выполняется тоже самое, что в `wc`. Если речь идет о выводе, как в `wc`, то я не поняла, что это был принципиальный момент

2023-12-24 09:59 UTC, jmkostina commented on HW_io/task2.hs
> +-- Реализуйте скрипт, который работает так же, как Unix-овский скрипт wc: выводит число слов, строк и байт в файле.
Обновила файл

2023-12-24 09:59 UTC, jmkostina commented on HW_io/task2.hs
> +main = do
Обновила файл

2023-12-24 10:03 UTC, jmkostina commented
Я сделала те задания, которые смогла. Теоретическое понимание (не полное, но лучше чем с Writer и Reader) не гарантирует способности применить все на практике
К тому же, я не прошу Вас выставлять полный балл. 2 балла из 10 - это тоже оценка. К тому же она будет справедливой по отношению к остальным ребятам

2023-12-24 22:59 UTC, pluralia commented
> Я сделала те задания, которые смогла. Теоретическое понимание (не полное, но лучше чем с Writer и Reader) не гарантирует способности применить все на практике

Ок, тогда можно сделать консультацию

> К тому же, я не прошу Вас выставлять полный балл.

Это правда, но, так как ты писала, что заинтересована в осознании материала, мне хочется помочь тебе и сделать это не через прессинг от экзамена/0 за дз, а через положительную мотивацию

> 2 балла из 10 - это тоже оценка. К тому же она будет справедливой по отношению к остальным ребятам

Cпорно. Бэкграунд у всех разный и так получилось, что тебе в настоящий момент тяжелее разбираться в этом материале. Ты стараешься, а потому я считаю, что сильно снижать тебе баллы за дз тоже несправедливо. Нет, я не буду завышать баллы на экзамене (там уже с чем придешь), но я могу попробовать помочь получить необходимые знания менее стрессово

2023-12-24 23:20 UTC, pluralia commented on HW_io/task2.hs
> +main = do
Так лучше уже

2023-12-24 23:21 UTC, pluralia commented on HW_io/task2.hs
> +-- Реализуйте скрипт, который работает так же, как Unix-овский скрипт wc: выводит число слов, строк и байт в файле.
Ты сделала запрашиваемое

2023-12-24 23:22 UTC, pluralia commented on HW_io/task1.hs
> +infLoop n count = do
1) count у тебя не обновляется
2) ты бы могла использовать n

2023-12-25 10:29 UTC, jmkostina commented on HW_io/task1.hs
> +infLoop n count = do
1. Да, увидела, поправила в новом файле.
2. Можно было, а потом обновлять дописку к имени файла лога через `mod 999`, но я решила разнести эти значения

2023-12-25 10:51 UTC, jmkostina commented
Я сделала 3е задание по IO. Артем сказал, что можно использовать встроенные функции (флаги существования директорий и файлов, FilePath и др.)

2023-12-25 21:16 UTC, pluralia commented on HW_io/task3.hs
> +      if getPatternMatch f pattern
Можно использовать `when`, чтобы не писать пустой `else return ()`

2023-12-25 21:18 UTC, pluralia commented
Ответь на вопрос и закрою PR: как ты компилировала файлы и запускала полученные скрипты? Приведи, пожалуйста, пример 2 или 3 заданий

2023-12-25 21:26 UTC, jmkostina commented
1. Компиляция `ghc task2.hs` или `ghc task3.hs`. В целом, все так компилируется
2. Запуск:
`./task2 task2.hs`  или `./task3 /Users/juliakostina/Desktop/Haskell/hw10 "*.hs"`
здесь для 2 задания:
-`./task2` - скомпилированная программа, которую я запускаю
- `task2.hs` - аргумент для программы (файл, который нужно "обсчитать"). То, с чем программа работает, в общем случае
для 3 задания:
-`./task3` - скомпилированная программа, которую я запускаю
- `/Users/juliakostina/Desktop/Haskell/hw10 "*.hs"` - аргументы (путь и паттерн), которые обрабатываются программой (внутри нее)

2023-12-25 21:30 UTC, pluralia commented
👍

2023-12-25 21:30 UTC, closed without merging

2023-12-25 21:34 UTC, jmkostina commented on HW_io/task3.hs
> +      if getPatternMatch f pattern
тогда кусок
```haskell
myFindFiles :: FilePath -> String -> IO ()
myFindFiles curDir pattern = do
    -- все, что есть в текущей директории + имя
    ls <- listDirectory curDir
    let ethFounded = map (curDir </>) ls
    -- файлы
    -- фильтр https://hackage.haskell.org/package/base-4.19.0.0/docs/Control-Monad.html#v:filterM
    foundFiles <- filterM doesFileExist ethFounded
    -- https://hackage.haskell.org/package/base-4.19.0.0/docs/Control-Monad.html#v:forM_
    forM_ foundFiles $ \f -> when (getPatternMatch f pattern) (putStrLn f)
    
    -- поддиректории
    subDirs <- filterM doesDirectoryExist ethFounded
    forM_ subDirs $ \d -> myFindFiles d pattern
```